dependencies:
- condition: eric-sc.logging.enabled
  import-values:
  - child: logShipper.config
    parent: global.logShipper.config
  name: eric-log-shipper
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 17.3.0+20
- condition: eric-sc.logging.enabled
  name: eric-log-transformer
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 15.1.0+38
- condition: eric-sc.logging.enabled
  name: eric-data-search-engine
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 13.2.0+36
- condition: eric-sc.logging.enabled
  name: eric-cnom-server
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-pc-rs-released-helm/
  version: 2.11.2+31
- name: eric-pm-bulk-reporter
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 10.5.0+7
- name: eric-data-document-database-pg
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm//
  version: 8.21.0+24
- name: eric-cm-mediator
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm//
  version: 9.0.0+9
- name: eric-sec-certm
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm//
  version: 9.2.0+59
- name: eric-sec-key-management
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 7.5.0+57
- name: eric-sec-sip-tls
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 10.1.0+23
- name: eric-data-distributed-coordinator-ed
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm//
  version: 10.6.0+13
- alias: eric-data-distributed-coordinator-ed-sc
  name: eric-data-distributed-coordinator-ed
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm//
  version: 10.6.0+13
- name: eric-data-coordinator-zk
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm//
  version: 3.1.0+8
- name: eric-data-message-bus-kf
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm//
  version: 2.21.0+17
- name: eric-fh-alarm-handler
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 14.3.0+19
- name: eric-fh-snmp-alarm-provider
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 11.0.0+6
- name: eric-pm-server
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 12.2.0+34
- name: eric-cm-yang-provider
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm//
  version: 20.1.0+122
- condition: eric-tm-ingress-controller.enabled
  name: eric-tm-ingress-controller-cr
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 14.5.0+37
- name: eric-lm-combined-server
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 9.12.0+25
- name: eric-ctrl-bro
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 9.5.0+26
- name: eric-sec-ldap-server
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 11.23.0+26
- name: eric-sec-admin-user-management
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 4.20.0+24
- condition: global.ericsson.ddc.enabled
  name: eric-odca-diagnostic-data-collector
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 9.2.0+25
- condition: global.ericsson.objectStorage.enabled
  name: eric-data-object-storage-mn
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 2.10.0+1954
- condition: global.ericsson.sftp.enabled
  name: eric-data-sftp-server
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 1.31.0+206
- name: eric-si-application-sys-info-handler
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-eric-application-sys-info-handler-released-helm/
  version: 2.20.0+29
- condition: global.ericsson.pvtb.enabled
  name: eric-probe-virtual-tap-broker
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-pc-released-helm/
  version: 4.9.0+46
- condition: global.ericsson.bsfdiameter.enabled
  name: eric-stm-diameter
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 1.46.0+11
- condition: global.ericsson.wcdb.enabled
  name: eric-data-wide-column-database-cd
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 7.5.0+64
- condition: eric-sc-hcagent.enabled
  name: eric-sc-hcagent
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-sc-hcagent-drop-helm/
  version: 1.3.0-3
- name: eric-sc-manager
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-sc-manager-drop-helm/
  version: 1.5.0-7
- condition: eric-sc-license-consumer.enabled
  import-values:
  - child: licenseconsumer.config
    parent: global.licenseconsumer.config
  name: eric-sc-license-consumer
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-sc-license-consumer-drop-helm/
  version: 1.1.0-4
- condition: global.ericsson.bsf.enabled
  name: eric-bsf
  repository: https://armdocker.rnd.ericsson.se/artifactory/proj-5g-bsf-helm/
  version: 1.15.25-935
- condition: global.ericsson.bsfdiameter.enabled
  name: eric-bsf-diameter
  repository: https://armdocker.rnd.ericsson.se/artifactory/proj-5g-bsf-helm/
  version: 1.15.25-935
- condition: global.ericsson.scp.enabled
  name: eric-scp
  repository: https://armdocker.rnd.ericsson.se/artifactory/proj-5g-bsf-helm/
  version: 1.15.25-935
- condition: global.ericsson.sepp.enabled
  name: eric-sepp
  repository: https://armdocker.rnd.ericsson.se/artifactory/proj-5g-bsf-helm/
  version: 1.15.25-935
- condition: global.ericsson.nlf.enabled
  name: eric-sc-nlf
  repository: https://armdocker.rnd.ericsson.se/artifactory/proj-5g-bsf-helm/
  version: 1.15.25-935
- condition: global.ericsson.rlf.enabled
  name: eric-sc-rlf
  repository: https://armdocker.rnd.ericsson.se/artifactory/proj-5g-bsf-helm/
  version: 1.15.25-935
- condition: global.ericsson.slf.enabled
  name: eric-sc-slf
  repository: https://armdocker.rnd.ericsson.se/artifactory/proj-5g-bsf-helm/
  version: 1.15.25-935
- name: eric-sc-monitor
  repository: https://armdocker.rnd.ericsson.se/artifactory/proj-5g-bsf-helm/
  version: 1.15.25-935
