#
# Dockerfile for EJBCA server container
#
FROM armdockerhub.rnd.ericsson.se/primekey/ejbca-ce

# Configure environment variables
ENV IMAGE_NAME ejbca

# Expose ports
EXPOSE 8080 8442 8443

# Configure default command
CMD [ "run" ]
