global:
  ipFamilyPolicy: PreferDualStack

eric-cm-yang-provider:
  service:
    externalIPv4:
      enabled: false
    externalIPv6:
      enabled: false

eric-data-sftp-server:
  service:
    externalIPv4:
      enabled: false
    externalIPv6:
      enabled: false

eric-fh-snmp-alarm-provider:
  service:
    externalIPv4:
      enabled: false
    externalIPv6:
      enabled: false

eric-pm-bulk-reporter:
  service:
    externalIPv4:
      enabled: false
    externalIPv6:
      enabled: false

eric-tm-ingress-controller-cr:
  service:
    externalIPv4:
      enabled: false
    externalIPv6:
      enabled: false

eric-stm-diameter:
  service:
    externalIPv4:
      enabled: true
    externalIPv6:
      enabled: true
