{{- $key := index .Values "certificates" "nrf" "key" }}
{{- $certificate := index .Values "certificates" "nrf" "certificate" }}
apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata: 
  name: {{ template "eric-sc-slf.name" . }}-nrf-client-certificate
  annotations:
{{- include "eric-sc-slf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-slf.config-annotations" . | indent 4 }}
  labels:
{{- include "eric-sc-slf.labels" . | indent 4 }}
spec: 
  generated-secret-name: {{ template "eric-sc-slf.name" . }}-nrf-client-certificate
  generated-secret-type: tls
  asymmetric-key-certificate-name:  {{ printf "%s/%s" $key $certificate | quote }}