FROM ###JAVA_JRE_DOCKER_IMG###

COPY build/libs /tmp
RUN mkdir -p /root/java-exec && mv /tmp/lib /tmp/###JAR### /root/java-exec
WORKDIR /root/java-exec

EXPOSE 8080

CMD java -jar ###JAR###

# Using this makes the image grow to > 600 Mbytes. Use it only if you really need it.
#CMD apt-get update && apt-get install -y jq net-tools tcpdump vim nghttp2-client && java -jar ###JAR###
