/*
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29502.nsmf.pdusession;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.DddTrafficDescriptor;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DDN Failure Subscription Information
 */
@ApiModel(description = "DDN Failure Subscription Information")
@JsonPropertyOrder({ DdnFailureSubInfo.JSON_PROPERTY_NOTIFY_CORRELATION_ID, DdnFailureSubInfo.JSON_PROPERTY_DDD_TRAFFIC_DESCRIPTOR_LIST })
public class DdnFailureSubInfo
{
    public static final String JSON_PROPERTY_NOTIFY_CORRELATION_ID = "notifyCorrelationId";
    private String notifyCorrelationId;

    public static final String JSON_PROPERTY_DDD_TRAFFIC_DESCRIPTOR_LIST = "dddTrafficDescriptorList";
    private List<DddTrafficDescriptor> dddTrafficDescriptorList = null;

    public DdnFailureSubInfo()
    {
    }

    public DdnFailureSubInfo notifyCorrelationId(String notifyCorrelationId)
    {

        this.notifyCorrelationId = notifyCorrelationId;
        return this;
    }

    /**
     * Get notifyCorrelationId
     * 
     * @return notifyCorrelationId
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_NOTIFY_CORRELATION_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getNotifyCorrelationId()
    {
        return notifyCorrelationId;
    }

    @JsonProperty(JSON_PROPERTY_NOTIFY_CORRELATION_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNotifyCorrelationId(String notifyCorrelationId)
    {
        this.notifyCorrelationId = notifyCorrelationId;
    }

    public DdnFailureSubInfo dddTrafficDescriptorList(List<DddTrafficDescriptor> dddTrafficDescriptorList)
    {

        this.dddTrafficDescriptorList = dddTrafficDescriptorList;
        return this;
    }

    public DdnFailureSubInfo addDddTrafficDescriptorListItem(DddTrafficDescriptor dddTrafficDescriptorListItem)
    {
        if (this.dddTrafficDescriptorList == null)
        {
            this.dddTrafficDescriptorList = new ArrayList<>();
        }
        this.dddTrafficDescriptorList.add(dddTrafficDescriptorListItem);
        return this;
    }

    /**
     * Get dddTrafficDescriptorList
     * 
     * @return dddTrafficDescriptorList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_DDD_TRAFFIC_DESCRIPTOR_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<DddTrafficDescriptor> getDddTrafficDescriptorList()
    {
        return dddTrafficDescriptorList;
    }

    @JsonProperty(JSON_PROPERTY_DDD_TRAFFIC_DESCRIPTOR_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDddTrafficDescriptorList(List<DddTrafficDescriptor> dddTrafficDescriptorList)
    {
        this.dddTrafficDescriptorList = dddTrafficDescriptorList;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        DdnFailureSubInfo ddnFailureSubInfo = (DdnFailureSubInfo) o;
        return Objects.equals(this.notifyCorrelationId, ddnFailureSubInfo.notifyCorrelationId)
               && Objects.equals(this.dddTrafficDescriptorList, ddnFailureSubInfo.dddTrafficDescriptorList);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(notifyCorrelationId, dddTrafficDescriptorList);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class DdnFailureSubInfo {\n");
        sb.append("    notifyCorrelationId: ").append(toIndentedString(notifyCorrelationId)).append("\n");
        sb.append("    dddTrafficDescriptorList: ").append(toIndentedString(dddTrafficDescriptorList)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
