/*
 * Nsmf_PDUSession
 * 
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * 
 * This file has been auto-generated by the yaml2java script.
 */

package com.ericsson.cnal.openapi.r17.ts29502.nsmf.pdusession;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RequestIndication
 */
public class RequestIndication
{
    public static final String UE_REQ_PDU_SES_MOD = "UE_REQ_PDU_SES_MOD";
    public static final String UE_REQ_PDU_SES_REL = "UE_REQ_PDU_SES_REL";
    public static final String PDU_SES_MOB = "PDU_SES_MOB";
    public static final String NW_REQ_PDU_SES_AUTH = "NW_REQ_PDU_SES_AUTH";
    public static final String NW_REQ_PDU_SES_MOD = "NW_REQ_PDU_SES_MOD";
    public static final String NW_REQ_PDU_SES_REL = "NW_REQ_PDU_SES_REL";
    public static final String EBI_ASSIGNMENT_REQ = "EBI_ASSIGNMENT_REQ";
    public static final String REL_DUE_TO_5G_AN_REQUEST = "REL_DUE_TO_5G_AN_REQUEST";

}
