/*
 * Nsmf_PDUSession
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29502.nsmf.pdusession;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.PlmnIdNid;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.NgApCause;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.AccessType;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.TraceData;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.MoExpDataCounter;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.PcfUeCallbackInfo;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Snssai;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Guami;
import com.ericsson.cnal.openapi.r17.ts29518.namf.communication.NgRanTargetId;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.BackupAmfInfo;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.RefToBinaryData;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.UserLocation;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data within Update SM Context Request
 */
@ApiModel(description = "Data within Update SM Context Request")
@JsonPropertyOrder({ SmContextUpdateData.JSON_PROPERTY_PEI,
                     SmContextUpdateData.JSON_PROPERTY_SERVING_NF_ID,
                     SmContextUpdateData.JSON_PROPERTY_GUAMI,
                     SmContextUpdateData.JSON_PROPERTY_SERVING_NETWORK,
                     SmContextUpdateData.JSON_PROPERTY_BACKUP_AMF_INFO,
                     SmContextUpdateData.JSON_PROPERTY_AN_TYPE,
                     SmContextUpdateData.JSON_PROPERTY_ADDITIONAL_AN_TYPE,
                     SmContextUpdateData.JSON_PROPERTY_AN_TYPE_TO_REACTIVATE,
                     SmContextUpdateData.JSON_PROPERTY_RAT_TYPE,
                     SmContextUpdateData.JSON_PROPERTY_PRESENCE_IN_LADN,
                     SmContextUpdateData.JSON_PROPERTY_UE_LOCATION,
                     SmContextUpdateData.JSON_PROPERTY_UE_TIME_ZONE,
                     SmContextUpdateData.JSON_PROPERTY_ADD_UE_LOCATION,
                     SmContextUpdateData.JSON_PROPERTY_UP_CNX_STATE,
                     SmContextUpdateData.JSON_PROPERTY_HO_STATE,
                     SmContextUpdateData.JSON_PROPERTY_TO_BE_SWITCHED,
                     SmContextUpdateData.JSON_PROPERTY_FAILED_TO_BE_SWITCHED,
                     SmContextUpdateData.JSON_PROPERTY_N1_SM_MSG,
                     SmContextUpdateData.JSON_PROPERTY_N2_SM_INFO,
                     SmContextUpdateData.JSON_PROPERTY_N2_SM_INFO_TYPE,
                     SmContextUpdateData.JSON_PROPERTY_TARGET_ID,
                     SmContextUpdateData.JSON_PROPERTY_TARGET_SERVING_NF_ID,
                     SmContextUpdateData.JSON_PROPERTY_SM_CONTEXT_STATUS_URI,
                     SmContextUpdateData.JSON_PROPERTY_DATA_FORWARDING,
                     SmContextUpdateData.JSON_PROPERTY_N9_FORWARDING_TUNNEL,
                     SmContextUpdateData.JSON_PROPERTY_N9_DL_FORWARDING_TNL_LIST,
                     SmContextUpdateData.JSON_PROPERTY_N9_UL_FORWARDING_TNL_LIST,
                     SmContextUpdateData.JSON_PROPERTY_N9_DL_FORWARDING_TUNNEL,
                     SmContextUpdateData.JSON_PROPERTY_N9_INACTIVITY_TIMER,
                     SmContextUpdateData.JSON_PROPERTY_EPS_BEARER_SETUP,
                     SmContextUpdateData.JSON_PROPERTY_REVOKE_EBI_LIST,
                     SmContextUpdateData.JSON_PROPERTY_RELEASE,
                     SmContextUpdateData.JSON_PROPERTY_CAUSE,
                     SmContextUpdateData.JSON_PROPERTY_NG_AP_CAUSE,
                     SmContextUpdateData.JSON_PROPERTY_5G_MM_CAUSE_VALUE,
                     SmContextUpdateData.JSON_PROPERTY_S_NSSAI,
                     SmContextUpdateData.JSON_PROPERTY_TRACE_DATA,
                     SmContextUpdateData.JSON_PROPERTY_EPS_INTERWORKING_IND,
                     SmContextUpdateData.JSON_PROPERTY_AN_TYPE_CAN_BE_CHANGED,
                     SmContextUpdateData.JSON_PROPERTY_N2_SM_INFO_EXT1,
                     SmContextUpdateData.JSON_PROPERTY_N2_SM_INFO_TYPE_EXT1,
                     SmContextUpdateData.JSON_PROPERTY_MA_RELEASE_IND,
                     SmContextUpdateData.JSON_PROPERTY_MA_NW_UPGRADE_IND,
                     SmContextUpdateData.JSON_PROPERTY_MA_REQUEST_IND,
                     SmContextUpdateData.JSON_PROPERTY_EXEMPTION_IND,
                     SmContextUpdateData.JSON_PROPERTY_SUPPORTED_FEATURES,
                     SmContextUpdateData.JSON_PROPERTY_MO_EXP_DATA_COUNTER,
                     SmContextUpdateData.JSON_PROPERTY_EXTENDED_NAS_SM_TIMER_IND,
                     SmContextUpdateData.JSON_PROPERTY_FORWARDING_F_TEID,
                     SmContextUpdateData.JSON_PROPERTY_FORWARDING_BEARER_CONTEXTS,
                     SmContextUpdateData.JSON_PROPERTY_DDN_FAILURE_SUBS,
                     SmContextUpdateData.JSON_PROPERTY_SKIP_N2_PDU_SESSION_RES_REL_IND,
                     SmContextUpdateData.JSON_PROPERTY_SECONDARY_RAT_USAGE_DATA_REPORT_CONTAINER,
                     SmContextUpdateData.JSON_PROPERTY_SM_POLICY_NOTIFY_IND,
                     SmContextUpdateData.JSON_PROPERTY_PCF_UE_CALLBACK_INFO,
                     SmContextUpdateData.JSON_PROPERTY_SATELLITE_BACKHAUL_CAT })
public class SmContextUpdateData
{
    public static final String JSON_PROPERTY_PEI = "pei";
    private String pei;

    public static final String JSON_PROPERTY_SERVING_NF_ID = "servingNfId";
    private UUID servingNfId;

    public static final String JSON_PROPERTY_GUAMI = "guami";
    private Guami guami;

    public static final String JSON_PROPERTY_SERVING_NETWORK = "servingNetwork";
    private PlmnIdNid servingNetwork;

    public static final String JSON_PROPERTY_BACKUP_AMF_INFO = "backupAmfInfo";
    private JsonNullable<List<BackupAmfInfo>> backupAmfInfo = JsonNullable.<List<BackupAmfInfo>>undefined();

    public static final String JSON_PROPERTY_AN_TYPE = "anType";
    private AccessType anType;

    public static final String JSON_PROPERTY_ADDITIONAL_AN_TYPE = "additionalAnType";
    private AccessType additionalAnType;

    public static final String JSON_PROPERTY_AN_TYPE_TO_REACTIVATE = "anTypeToReactivate";
    private AccessType anTypeToReactivate;

    public static final String JSON_PROPERTY_RAT_TYPE = "ratType";
    private String ratType;

    public static final String JSON_PROPERTY_PRESENCE_IN_LADN = "presenceInLadn";
    private String presenceInLadn;

    public static final String JSON_PROPERTY_UE_LOCATION = "ueLocation";
    private UserLocation ueLocation;

    public static final String JSON_PROPERTY_UE_TIME_ZONE = "ueTimeZone";
    private String ueTimeZone;

    public static final String JSON_PROPERTY_ADD_UE_LOCATION = "addUeLocation";
    private UserLocation addUeLocation;

    public static final String JSON_PROPERTY_UP_CNX_STATE = "upCnxState";
    private String upCnxState;

    public static final String JSON_PROPERTY_HO_STATE = "hoState";
    private String hoState;

    public static final String JSON_PROPERTY_TO_BE_SWITCHED = "toBeSwitched";
    private Boolean toBeSwitched = false;

    public static final String JSON_PROPERTY_FAILED_TO_BE_SWITCHED = "failedToBeSwitched";
    private Boolean failedToBeSwitched;

    public static final String JSON_PROPERTY_N1_SM_MSG = "n1SmMsg";
    private RefToBinaryData n1SmMsg;

    public static final String JSON_PROPERTY_N2_SM_INFO = "n2SmInfo";
    private RefToBinaryData n2SmInfo;

    public static final String JSON_PROPERTY_N2_SM_INFO_TYPE = "n2SmInfoType";
    private String n2SmInfoType;

    public static final String JSON_PROPERTY_TARGET_ID = "targetId";
    private NgRanTargetId targetId;

    public static final String JSON_PROPERTY_TARGET_SERVING_NF_ID = "targetServingNfId";
    private UUID targetServingNfId;

    public static final String JSON_PROPERTY_SM_CONTEXT_STATUS_URI = "smContextStatusUri";
    private String smContextStatusUri;

    public static final String JSON_PROPERTY_DATA_FORWARDING = "dataForwarding";
    private Boolean dataForwarding = false;

    public static final String JSON_PROPERTY_N9_FORWARDING_TUNNEL = "n9ForwardingTunnel";
    private TunnelInfo n9ForwardingTunnel;

    public static final String JSON_PROPERTY_N9_DL_FORWARDING_TNL_LIST = "n9DlForwardingTnlList";
    private List<IndirectDataForwardingTunnelInfo> n9DlForwardingTnlList = null;

    public static final String JSON_PROPERTY_N9_UL_FORWARDING_TNL_LIST = "n9UlForwardingTnlList";
    private List<IndirectDataForwardingTunnelInfo> n9UlForwardingTnlList = null;

    public static final String JSON_PROPERTY_N9_DL_FORWARDING_TUNNEL = "n9DlForwardingTunnel";
    private TunnelInfo n9DlForwardingTunnel;

    public static final String JSON_PROPERTY_N9_INACTIVITY_TIMER = "n9InactivityTimer";
    private Integer n9InactivityTimer;

    public static final String JSON_PROPERTY_EPS_BEARER_SETUP = "epsBearerSetup";
    private List<String> epsBearerSetup = null;

    public static final String JSON_PROPERTY_REVOKE_EBI_LIST = "revokeEbiList";
    private List<Integer> revokeEbiList = null;

    public static final String JSON_PROPERTY_RELEASE = "release";
    private Boolean release = false;

    public static final String JSON_PROPERTY_CAUSE = "cause";
    private String cause;

    public static final String JSON_PROPERTY_NG_AP_CAUSE = "ngApCause";
    private NgApCause ngApCause;

    public static final String JSON_PROPERTY_5G_MM_CAUSE_VALUE = "5gMmCauseValue";
    private Integer _5gMmCauseValue;

    public static final String JSON_PROPERTY_S_NSSAI = "sNssai";
    private Snssai sNssai;

    public static final String JSON_PROPERTY_TRACE_DATA = "traceData";
    private JsonNullable<TraceData> traceData = JsonNullable.<TraceData>undefined();

    public static final String JSON_PROPERTY_EPS_INTERWORKING_IND = "epsInterworkingInd";
    private String epsInterworkingInd;

    public static final String JSON_PROPERTY_AN_TYPE_CAN_BE_CHANGED = "anTypeCanBeChanged";
    private Boolean anTypeCanBeChanged = false;

    public static final String JSON_PROPERTY_N2_SM_INFO_EXT1 = "n2SmInfoExt1";
    private RefToBinaryData n2SmInfoExt1;

    public static final String JSON_PROPERTY_N2_SM_INFO_TYPE_EXT1 = "n2SmInfoTypeExt1";
    private String n2SmInfoTypeExt1;

    public static final String JSON_PROPERTY_MA_RELEASE_IND = "maReleaseInd";
    private String maReleaseInd;

    public static final String JSON_PROPERTY_MA_NW_UPGRADE_IND = "maNwUpgradeInd";
    private Boolean maNwUpgradeInd = false;

    public static final String JSON_PROPERTY_MA_REQUEST_IND = "maRequestInd";
    private Boolean maRequestInd = false;

    public static final String JSON_PROPERTY_EXEMPTION_IND = "exemptionInd";
    private ExemptionInd exemptionInd;

    public static final String JSON_PROPERTY_SUPPORTED_FEATURES = "supportedFeatures";
    private String supportedFeatures;

    public static final String JSON_PROPERTY_MO_EXP_DATA_COUNTER = "moExpDataCounter";
    private MoExpDataCounter moExpDataCounter;

    public static final String JSON_PROPERTY_EXTENDED_NAS_SM_TIMER_IND = "extendedNasSmTimerInd";
    private Boolean extendedNasSmTimerInd;

    public static final String JSON_PROPERTY_FORWARDING_F_TEID = "forwardingFTeid";
    private byte[] forwardingFTeid;

    public static final String JSON_PROPERTY_FORWARDING_BEARER_CONTEXTS = "forwardingBearerContexts";
    private List<String> forwardingBearerContexts = null;

    public static final String JSON_PROPERTY_DDN_FAILURE_SUBS = "ddnFailureSubs";
    private DdnFailureSubs ddnFailureSubs;

    public static final String JSON_PROPERTY_SKIP_N2_PDU_SESSION_RES_REL_IND = "skipN2PduSessionResRelInd";
    private Boolean skipN2PduSessionResRelInd = false;

    public static final String JSON_PROPERTY_SECONDARY_RAT_USAGE_DATA_REPORT_CONTAINER = "secondaryRatUsageDataReportContainer";
    private List<byte[]> secondaryRatUsageDataReportContainer = null;

    /**
     * Gets or Sets smPolicyNotifyInd
     */
    public enum SmPolicyNotifyIndEnum
    {
        TRUE(true);

        private Boolean value;

        SmPolicyNotifyIndEnum(Boolean value)
        {
            this.value = value;
        }

        @JsonValue
        public Boolean getValue()
        {
            return value;
        }

        @Override
        public String toString()
        {
            return String.valueOf(value);
        }

        @JsonCreator
        public static SmPolicyNotifyIndEnum fromValue(Boolean value)
        {
            for (SmPolicyNotifyIndEnum b : SmPolicyNotifyIndEnum.values())
            {
                if (b.value.equals(value))
                {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

    public static final String JSON_PROPERTY_SM_POLICY_NOTIFY_IND = "smPolicyNotifyInd";
    private SmPolicyNotifyIndEnum smPolicyNotifyInd;

    public static final String JSON_PROPERTY_PCF_UE_CALLBACK_INFO = "pcfUeCallbackInfo";
    private JsonNullable<PcfUeCallbackInfo> pcfUeCallbackInfo = JsonNullable.<PcfUeCallbackInfo>undefined();

    public static final String JSON_PROPERTY_SATELLITE_BACKHAUL_CAT = "satelliteBackhaulCat";
    private String satelliteBackhaulCat;

    public SmContextUpdateData()
    {
    }

    public SmContextUpdateData pei(String pei)
    {

        this.pei = pei;
        return this;
    }

    /**
     * String representing a Permanent Equipment Identifier that may contain - an
     * IMEI or IMEISV, as specified in clause 6.2 of 3GPP TS 23.003; a MAC address
     * for a 5G-RG or FN-RG via wireline access, with an indication that this
     * address cannot be trusted for regulatory purpose if this address cannot be
     * used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7 of
     * 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345.
     * 
     * @return pei
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String representing a Permanent Equipment Identifier that may contain - an IMEI or IMEISV, as  specified in clause 6.2 of 3GPP TS 23.003; a MAC address for a 5G-RG or FN-RG via  wireline  access, with an indication that this address cannot be trusted for regulatory purpose if this  address cannot be used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7  of 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345.  ")
    @JsonProperty(JSON_PROPERTY_PEI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPei()
    {
        return pei;
    }

    @JsonProperty(JSON_PROPERTY_PEI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPei(String pei)
    {
        this.pei = pei;
    }

    public SmContextUpdateData servingNfId(UUID servingNfId)
    {

        this.servingNfId = servingNfId;
        return this;
    }

    /**
     * String uniquely identifying a NF instance. The format of the NF Instance ID
     * shall be a Universally Unique Identifier (UUID) version 4, as described in
     * IETF RFC 4122.
     * 
     * @return servingNfId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  ")
    @JsonProperty(JSON_PROPERTY_SERVING_NF_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getServingNfId()
    {
        return servingNfId;
    }

    @JsonProperty(JSON_PROPERTY_SERVING_NF_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setServingNfId(UUID servingNfId)
    {
        this.servingNfId = servingNfId;
    }

    public SmContextUpdateData guami(Guami guami)
    {

        this.guami = guami;
        return this;
    }

    /**
     * Get guami
     * 
     * @return guami
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_GUAMI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Guami getGuami()
    {
        return guami;
    }

    @JsonProperty(JSON_PROPERTY_GUAMI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGuami(Guami guami)
    {
        this.guami = guami;
    }

    public SmContextUpdateData servingNetwork(PlmnIdNid servingNetwork)
    {

        this.servingNetwork = servingNetwork;
        return this;
    }

    /**
     * Get servingNetwork
     * 
     * @return servingNetwork
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SERVING_NETWORK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PlmnIdNid getServingNetwork()
    {
        return servingNetwork;
    }

    @JsonProperty(JSON_PROPERTY_SERVING_NETWORK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setServingNetwork(PlmnIdNid servingNetwork)
    {
        this.servingNetwork = servingNetwork;
    }

    public SmContextUpdateData backupAmfInfo(List<BackupAmfInfo> backupAmfInfo)
    {
        this.backupAmfInfo = JsonNullable.<List<BackupAmfInfo>>of(backupAmfInfo);

        return this;
    }

    public SmContextUpdateData addBackupAmfInfoItem(BackupAmfInfo backupAmfInfoItem)
    {
        if (this.backupAmfInfo == null || !this.backupAmfInfo.isPresent())
        {
            this.backupAmfInfo = JsonNullable.<List<BackupAmfInfo>>of(new ArrayList<>());
        }
        try
        {
            this.backupAmfInfo.get().add(backupAmfInfoItem);
        }
        catch (java.util.NoSuchElementException e)
        {
            // this can never happen, as we make sure above that the value is present
        }
        return this;
    }

    /**
     * Get backupAmfInfo
     * 
     * @return backupAmfInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonIgnore

    public List<BackupAmfInfo> getBackupAmfInfo()
    {
        return backupAmfInfo.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_BACKUP_AMF_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<List<BackupAmfInfo>> getBackupAmfInfo_JsonNullable()
    {
        return backupAmfInfo;
    }

    @JsonProperty(JSON_PROPERTY_BACKUP_AMF_INFO)
    public void setBackupAmfInfo_JsonNullable(JsonNullable<List<BackupAmfInfo>> backupAmfInfo)
    {
        this.backupAmfInfo = backupAmfInfo;
    }

    public void setBackupAmfInfo(List<BackupAmfInfo> backupAmfInfo)
    {
        this.backupAmfInfo = JsonNullable.<List<BackupAmfInfo>>of(backupAmfInfo);
    }

    public SmContextUpdateData anType(AccessType anType)
    {

        this.anType = anType;
        return this;
    }

    /**
     * Get anType
     * 
     * @return anType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_AN_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AccessType getAnType()
    {
        return anType;
    }

    @JsonProperty(JSON_PROPERTY_AN_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAnType(AccessType anType)
    {
        this.anType = anType;
    }

    public SmContextUpdateData additionalAnType(AccessType additionalAnType)
    {

        this.additionalAnType = additionalAnType;
        return this;
    }

    /**
     * Get additionalAnType
     * 
     * @return additionalAnType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ADDITIONAL_AN_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AccessType getAdditionalAnType()
    {
        return additionalAnType;
    }

    @JsonProperty(JSON_PROPERTY_ADDITIONAL_AN_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAdditionalAnType(AccessType additionalAnType)
    {
        this.additionalAnType = additionalAnType;
    }

    public SmContextUpdateData anTypeToReactivate(AccessType anTypeToReactivate)
    {

        this.anTypeToReactivate = anTypeToReactivate;
        return this;
    }

    /**
     * Get anTypeToReactivate
     * 
     * @return anTypeToReactivate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_AN_TYPE_TO_REACTIVATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AccessType getAnTypeToReactivate()
    {
        return anTypeToReactivate;
    }

    @JsonProperty(JSON_PROPERTY_AN_TYPE_TO_REACTIVATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAnTypeToReactivate(AccessType anTypeToReactivate)
    {
        this.anTypeToReactivate = anTypeToReactivate;
    }

    public SmContextUpdateData ratType(String ratType)
    {

        this.ratType = ratType;
        return this;
    }

    /**
     * Indicates the radio access used.
     * 
     * @return ratType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates the radio access used.")
    @JsonProperty(JSON_PROPERTY_RAT_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getRatType()
    {
        return ratType;
    }

    @JsonProperty(JSON_PROPERTY_RAT_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRatType(String ratType)
    {
        this.ratType = ratType;
    }

    public SmContextUpdateData presenceInLadn(String presenceInLadn)
    {

        this.presenceInLadn = presenceInLadn;
        return this;
    }

    /**
     * Possible values are: -IN_AREA: Indicates that the UE is inside or enters the
     * presence reporting area. -OUT_OF_AREA: Indicates that the UE is outside or
     * leaves the presence reporting area -UNKNOW: Indicates it is unknown whether
     * the UE is in the presence reporting area or not -INACTIVE: Indicates that the
     * presence reporting area is inactive in the serving node.
     * 
     * @return presenceInLadn
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Possible values are: -IN_AREA: Indicates that the UE is inside or enters the presence reporting area. -OUT_OF_AREA: Indicates that the UE is outside or leaves the presence reporting area -UNKNOW: Indicates it is unknown whether the UE is in the presence reporting area or not -INACTIVE: Indicates that the presence reporting area is inactive in the serving node.  ")
    @JsonProperty(JSON_PROPERTY_PRESENCE_IN_LADN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPresenceInLadn()
    {
        return presenceInLadn;
    }

    @JsonProperty(JSON_PROPERTY_PRESENCE_IN_LADN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPresenceInLadn(String presenceInLadn)
    {
        this.presenceInLadn = presenceInLadn;
    }

    public SmContextUpdateData ueLocation(UserLocation ueLocation)
    {

        this.ueLocation = ueLocation;
        return this;
    }

    /**
     * Get ueLocation
     * 
     * @return ueLocation
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_UE_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UserLocation getUeLocation()
    {
        return ueLocation;
    }

    @JsonProperty(JSON_PROPERTY_UE_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUeLocation(UserLocation ueLocation)
    {
        this.ueLocation = ueLocation;
    }

    public SmContextUpdateData ueTimeZone(String ueTimeZone)
    {

        this.ueTimeZone = ueTimeZone;
        return this;
    }

    /**
     * String with format \&quot;time-numoffset\&quot; optionally appended by
     * \&quot;daylightSavingTime\&quot;, where - \&quot;time-numoffset\&quot; shall
     * represent the time zone adjusted for daylight saving time and be encoded as
     * time-numoffset as defined in clause 5.6 of IETF RFC 3339; -
     * \&quot;daylightSavingTime\&quot; shall represent the adjustment that has been
     * made and shall be encoded as \&quot;+1\&quot; or \&quot;+2\&quot; for a +1 or
     * +2 hours adjustment. The example is for 8 hours behind UTC, +1 hour
     * adjustment for Daylight Saving Time.
     * 
     * @return ueTimeZone
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "-08:00+1",
                      value = "String with format \"time-numoffset\" optionally appended by \"daylightSavingTime\", where  - \"time-numoffset\" shall represent the time zone adjusted for daylight saving time and be    encoded as time-numoffset as defined in clause 5.6 of IETF RFC 3339;  - \"daylightSavingTime\" shall represent the adjustment that has been made and shall be    encoded as \"+1\" or \"+2\" for a +1 or +2 hours adjustment.  The example is for 8 hours behind UTC, +1 hour adjustment for Daylight Saving Time. ")
    @JsonProperty(JSON_PROPERTY_UE_TIME_ZONE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUeTimeZone()
    {
        return ueTimeZone;
    }

    @JsonProperty(JSON_PROPERTY_UE_TIME_ZONE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUeTimeZone(String ueTimeZone)
    {
        this.ueTimeZone = ueTimeZone;
    }

    public SmContextUpdateData addUeLocation(UserLocation addUeLocation)
    {

        this.addUeLocation = addUeLocation;
        return this;
    }

    /**
     * Get addUeLocation
     * 
     * @return addUeLocation
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ADD_UE_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UserLocation getAddUeLocation()
    {
        return addUeLocation;
    }

    @JsonProperty(JSON_PROPERTY_ADD_UE_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAddUeLocation(UserLocation addUeLocation)
    {
        this.addUeLocation = addUeLocation;
    }

    public SmContextUpdateData upCnxState(String upCnxState)
    {

        this.upCnxState = upCnxState;
        return this;
    }

    /**
     * User Plane Connection State. Possible values are - ACTIVATED - DEACTIVATED -
     * ACTIVATING - SUSPENDED
     * 
     * @return upCnxState
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "User Plane Connection State. Possible values are - ACTIVATED - DEACTIVATED - ACTIVATING - SUSPENDED ")
    @JsonProperty(JSON_PROPERTY_UP_CNX_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUpCnxState()
    {
        return upCnxState;
    }

    @JsonProperty(JSON_PROPERTY_UP_CNX_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUpCnxState(String upCnxState)
    {
        this.upCnxState = upCnxState;
    }

    public SmContextUpdateData hoState(String hoState)
    {

        this.hoState = hoState;
        return this;
    }

    /**
     * Handover state. Possible values are - NONE - PREPARING - PREPARED - COMPLETED
     * - CANCELLED
     * 
     * @return hoState
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Handover state. Possible values are - NONE - PREPARING - PREPARED - COMPLETED - CANCELLED ")
    @JsonProperty(JSON_PROPERTY_HO_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getHoState()
    {
        return hoState;
    }

    @JsonProperty(JSON_PROPERTY_HO_STATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHoState(String hoState)
    {
        this.hoState = hoState;
    }

    public SmContextUpdateData toBeSwitched(Boolean toBeSwitched)
    {

        this.toBeSwitched = toBeSwitched;
        return this;
    }

    /**
     * Get toBeSwitched
     * 
     * @return toBeSwitched
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TO_BE_SWITCHED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getToBeSwitched()
    {
        return toBeSwitched;
    }

    @JsonProperty(JSON_PROPERTY_TO_BE_SWITCHED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setToBeSwitched(Boolean toBeSwitched)
    {
        this.toBeSwitched = toBeSwitched;
    }

    public SmContextUpdateData failedToBeSwitched(Boolean failedToBeSwitched)
    {

        this.failedToBeSwitched = failedToBeSwitched;
        return this;
    }

    /**
     * Get failedToBeSwitched
     * 
     * @return failedToBeSwitched
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_FAILED_TO_BE_SWITCHED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getFailedToBeSwitched()
    {
        return failedToBeSwitched;
    }

    @JsonProperty(JSON_PROPERTY_FAILED_TO_BE_SWITCHED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFailedToBeSwitched(Boolean failedToBeSwitched)
    {
        this.failedToBeSwitched = failedToBeSwitched;
    }

    public SmContextUpdateData n1SmMsg(RefToBinaryData n1SmMsg)
    {

        this.n1SmMsg = n1SmMsg;
        return this;
    }

    /**
     * Get n1SmMsg
     * 
     * @return n1SmMsg
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_N1_SM_MSG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public RefToBinaryData getN1SmMsg()
    {
        return n1SmMsg;
    }

    @JsonProperty(JSON_PROPERTY_N1_SM_MSG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN1SmMsg(RefToBinaryData n1SmMsg)
    {
        this.n1SmMsg = n1SmMsg;
    }

    public SmContextUpdateData n2SmInfo(RefToBinaryData n2SmInfo)
    {

        this.n2SmInfo = n2SmInfo;
        return this;
    }

    /**
     * Get n2SmInfo
     * 
     * @return n2SmInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_N2_SM_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public RefToBinaryData getN2SmInfo()
    {
        return n2SmInfo;
    }

    @JsonProperty(JSON_PROPERTY_N2_SM_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN2SmInfo(RefToBinaryData n2SmInfo)
    {
        this.n2SmInfo = n2SmInfo;
    }

    public SmContextUpdateData n2SmInfoType(String n2SmInfoType)
    {

        this.n2SmInfoType = n2SmInfoType;
        return this;
    }

    /**
     * N2 SM Information Type. Possible values are - PDU_RES_SETUP_REQ -
     * PDU_RES_SETUP_RSP - PDU_RES_SETUP_FAIL - PDU_RES_REL_CMD - PDU_RES_REL_RSP -
     * PDU_RES_MOD_REQ - PDU_RES_MOD_RSP - PDU_RES_MOD_FAIL - PDU_RES_NTY -
     * PDU_RES_NTY_REL - PDU_RES_MOD_IND - PDU_RES_MOD_CFM - PATH_SWITCH_REQ -
     * PATH_SWITCH_SETUP_FAIL - PATH_SWITCH_REQ_ACK - PATH_SWITCH_REQ_FAIL -
     * HANDOVER_REQUIRED - HANDOVER_CMD - HANDOVER_PREP_FAIL - HANDOVER_REQ_ACK -
     * HANDOVER_RES_ALLOC_FAIL - SECONDARY_RAT_USAGE - PDU_RES_MOD_IND_FAIL -
     * UE_CONTEXT_RESUME_REQ - UE_CONTEXT_RESUME_RSP - UE_CONTEXT_SUSPEND_REQ
     * 
     * @return n2SmInfoType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "N2 SM Information Type. Possible values are - PDU_RES_SETUP_REQ - PDU_RES_SETUP_RSP - PDU_RES_SETUP_FAIL - PDU_RES_REL_CMD - PDU_RES_REL_RSP - PDU_RES_MOD_REQ - PDU_RES_MOD_RSP - PDU_RES_MOD_FAIL - PDU_RES_NTY - PDU_RES_NTY_REL - PDU_RES_MOD_IND - PDU_RES_MOD_CFM - PATH_SWITCH_REQ - PATH_SWITCH_SETUP_FAIL - PATH_SWITCH_REQ_ACK - PATH_SWITCH_REQ_FAIL - HANDOVER_REQUIRED - HANDOVER_CMD - HANDOVER_PREP_FAIL - HANDOVER_REQ_ACK - HANDOVER_RES_ALLOC_FAIL - SECONDARY_RAT_USAGE - PDU_RES_MOD_IND_FAIL - UE_CONTEXT_RESUME_REQ - UE_CONTEXT_RESUME_RSP - UE_CONTEXT_SUSPEND_REQ ")
    @JsonProperty(JSON_PROPERTY_N2_SM_INFO_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getN2SmInfoType()
    {
        return n2SmInfoType;
    }

    @JsonProperty(JSON_PROPERTY_N2_SM_INFO_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN2SmInfoType(String n2SmInfoType)
    {
        this.n2SmInfoType = n2SmInfoType;
    }

    public SmContextUpdateData targetId(NgRanTargetId targetId)
    {

        this.targetId = targetId;
        return this;
    }

    /**
     * Get targetId
     * 
     * @return targetId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TARGET_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public NgRanTargetId getTargetId()
    {
        return targetId;
    }

    @JsonProperty(JSON_PROPERTY_TARGET_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTargetId(NgRanTargetId targetId)
    {
        this.targetId = targetId;
    }

    public SmContextUpdateData targetServingNfId(UUID targetServingNfId)
    {

        this.targetServingNfId = targetServingNfId;
        return this;
    }

    /**
     * String uniquely identifying a NF instance. The format of the NF Instance ID
     * shall be a Universally Unique Identifier (UUID) version 4, as described in
     * IETF RFC 4122.
     * 
     * @return targetServingNfId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  ")
    @JsonProperty(JSON_PROPERTY_TARGET_SERVING_NF_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getTargetServingNfId()
    {
        return targetServingNfId;
    }

    @JsonProperty(JSON_PROPERTY_TARGET_SERVING_NF_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTargetServingNfId(UUID targetServingNfId)
    {
        this.targetServingNfId = targetServingNfId;
    }

    public SmContextUpdateData smContextStatusUri(String smContextStatusUri)
    {

        this.smContextStatusUri = smContextStatusUri;
        return this;
    }

    /**
     * String providing an URI formatted according to RFC 3986.
     * 
     * @return smContextStatusUri
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String providing an URI formatted according to RFC 3986.")
    @JsonProperty(JSON_PROPERTY_SM_CONTEXT_STATUS_URI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSmContextStatusUri()
    {
        return smContextStatusUri;
    }

    @JsonProperty(JSON_PROPERTY_SM_CONTEXT_STATUS_URI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSmContextStatusUri(String smContextStatusUri)
    {
        this.smContextStatusUri = smContextStatusUri;
    }

    public SmContextUpdateData dataForwarding(Boolean dataForwarding)
    {

        this.dataForwarding = dataForwarding;
        return this;
    }

    /**
     * Get dataForwarding
     * 
     * @return dataForwarding
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_DATA_FORWARDING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getDataForwarding()
    {
        return dataForwarding;
    }

    @JsonProperty(JSON_PROPERTY_DATA_FORWARDING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDataForwarding(Boolean dataForwarding)
    {
        this.dataForwarding = dataForwarding;
    }

    public SmContextUpdateData n9ForwardingTunnel(TunnelInfo n9ForwardingTunnel)
    {

        this.n9ForwardingTunnel = n9ForwardingTunnel;
        return this;
    }

    /**
     * Get n9ForwardingTunnel
     * 
     * @return n9ForwardingTunnel
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_N9_FORWARDING_TUNNEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public TunnelInfo getN9ForwardingTunnel()
    {
        return n9ForwardingTunnel;
    }

    @JsonProperty(JSON_PROPERTY_N9_FORWARDING_TUNNEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN9ForwardingTunnel(TunnelInfo n9ForwardingTunnel)
    {
        this.n9ForwardingTunnel = n9ForwardingTunnel;
    }

    public SmContextUpdateData n9DlForwardingTnlList(List<IndirectDataForwardingTunnelInfo> n9DlForwardingTnlList)
    {

        this.n9DlForwardingTnlList = n9DlForwardingTnlList;
        return this;
    }

    public SmContextUpdateData addN9DlForwardingTnlListItem(IndirectDataForwardingTunnelInfo n9DlForwardingTnlListItem)
    {
        if (this.n9DlForwardingTnlList == null)
        {
            this.n9DlForwardingTnlList = new ArrayList<>();
        }
        this.n9DlForwardingTnlList.add(n9DlForwardingTnlListItem);
        return this;
    }

    /**
     * Get n9DlForwardingTnlList
     * 
     * @return n9DlForwardingTnlList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_N9_DL_FORWARDING_TNL_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<IndirectDataForwardingTunnelInfo> getN9DlForwardingTnlList()
    {
        return n9DlForwardingTnlList;
    }

    @JsonProperty(JSON_PROPERTY_N9_DL_FORWARDING_TNL_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN9DlForwardingTnlList(List<IndirectDataForwardingTunnelInfo> n9DlForwardingTnlList)
    {
        this.n9DlForwardingTnlList = n9DlForwardingTnlList;
    }

    public SmContextUpdateData n9UlForwardingTnlList(List<IndirectDataForwardingTunnelInfo> n9UlForwardingTnlList)
    {

        this.n9UlForwardingTnlList = n9UlForwardingTnlList;
        return this;
    }

    public SmContextUpdateData addN9UlForwardingTnlListItem(IndirectDataForwardingTunnelInfo n9UlForwardingTnlListItem)
    {
        if (this.n9UlForwardingTnlList == null)
        {
            this.n9UlForwardingTnlList = new ArrayList<>();
        }
        this.n9UlForwardingTnlList.add(n9UlForwardingTnlListItem);
        return this;
    }

    /**
     * Get n9UlForwardingTnlList
     * 
     * @return n9UlForwardingTnlList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_N9_UL_FORWARDING_TNL_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<IndirectDataForwardingTunnelInfo> getN9UlForwardingTnlList()
    {
        return n9UlForwardingTnlList;
    }

    @JsonProperty(JSON_PROPERTY_N9_UL_FORWARDING_TNL_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN9UlForwardingTnlList(List<IndirectDataForwardingTunnelInfo> n9UlForwardingTnlList)
    {
        this.n9UlForwardingTnlList = n9UlForwardingTnlList;
    }

    public SmContextUpdateData n9DlForwardingTunnel(TunnelInfo n9DlForwardingTunnel)
    {

        this.n9DlForwardingTunnel = n9DlForwardingTunnel;
        return this;
    }

    /**
     * Get n9DlForwardingTunnel
     * 
     * @return n9DlForwardingTunnel
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_N9_DL_FORWARDING_TUNNEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public TunnelInfo getN9DlForwardingTunnel()
    {
        return n9DlForwardingTunnel;
    }

    @JsonProperty(JSON_PROPERTY_N9_DL_FORWARDING_TUNNEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN9DlForwardingTunnel(TunnelInfo n9DlForwardingTunnel)
    {
        this.n9DlForwardingTunnel = n9DlForwardingTunnel;
    }

    public SmContextUpdateData n9InactivityTimer(Integer n9InactivityTimer)
    {

        this.n9InactivityTimer = n9InactivityTimer;
        return this;
    }

    /**
     * indicating a time in seconds.
     * 
     * @return n9InactivityTimer
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "indicating a time in seconds.")
    @JsonProperty(JSON_PROPERTY_N9_INACTIVITY_TIMER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getN9InactivityTimer()
    {
        return n9InactivityTimer;
    }

    @JsonProperty(JSON_PROPERTY_N9_INACTIVITY_TIMER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN9InactivityTimer(Integer n9InactivityTimer)
    {
        this.n9InactivityTimer = n9InactivityTimer;
    }

    public SmContextUpdateData epsBearerSetup(List<String> epsBearerSetup)
    {

        this.epsBearerSetup = epsBearerSetup;
        return this;
    }

    public SmContextUpdateData addEpsBearerSetupItem(String epsBearerSetupItem)
    {
        if (this.epsBearerSetup == null)
        {
            this.epsBearerSetup = new ArrayList<>();
        }
        this.epsBearerSetup.add(epsBearerSetupItem);
        return this;
    }

    /**
     * Get epsBearerSetup
     * 
     * @return epsBearerSetup
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_EPS_BEARER_SETUP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getEpsBearerSetup()
    {
        return epsBearerSetup;
    }

    @JsonProperty(JSON_PROPERTY_EPS_BEARER_SETUP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEpsBearerSetup(List<String> epsBearerSetup)
    {
        this.epsBearerSetup = epsBearerSetup;
    }

    public SmContextUpdateData revokeEbiList(List<Integer> revokeEbiList)
    {

        this.revokeEbiList = revokeEbiList;
        return this;
    }

    public SmContextUpdateData addRevokeEbiListItem(Integer revokeEbiListItem)
    {
        if (this.revokeEbiList == null)
        {
            this.revokeEbiList = new ArrayList<>();
        }
        this.revokeEbiList.add(revokeEbiListItem);
        return this;
    }

    /**
     * Get revokeEbiList
     * 
     * @return revokeEbiList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_REVOKE_EBI_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Integer> getRevokeEbiList()
    {
        return revokeEbiList;
    }

    @JsonProperty(JSON_PROPERTY_REVOKE_EBI_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRevokeEbiList(List<Integer> revokeEbiList)
    {
        this.revokeEbiList = revokeEbiList;
    }

    public SmContextUpdateData release(Boolean release)
    {

        this.release = release;
        return this;
    }

    /**
     * Get release
     * 
     * @return release
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_RELEASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRelease()
    {
        return release;
    }

    @JsonProperty(JSON_PROPERTY_RELEASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRelease(Boolean release)
    {
        this.release = release;
    }

    public SmContextUpdateData cause(String cause)
    {

        this.cause = cause;
        return this;
    }

    /**
     * Cause information. Possible values are - REL_DUE_TO_HO - EPS_FALLBACK -
     * REL_DUE_TO_UP_SEC - DNN_CONGESTION - S_NSSAI_CONGESTION -
     * REL_DUE_TO_REACTIVATION - 5G_AN_NOT_RESPONDING -
     * REL_DUE_TO_SLICE_NOT_AVAILABLE - REL_DUE_TO_DUPLICATE_SESSION_ID -
     * PDU_SESSION_STATUS_MISMATCH - HO_FAILURE - INSUFFICIENT_UP_RESOURCES -
     * PDU_SESSION_HANDED_OVER - PDU_SESSION_RESUMED -
     * CN_ASSISTED_RAN_PARAMETER_TUNING - ISMF_CONTEXT_TRANSFER -
     * SMF_CONTEXT_TRANSFER - REL_DUE_TO_PS_TO_CS_HO -
     * REL_DUE_TO_SUBSCRIPTION_CHANGE - HO_CANCEL - REL_DUE_TO_SLICE_NOT_AUTHORIZED
     * - PDU_SESSION_HAND_OVER_FAILURE - DDN_FAILURE_STATUS -
     * REL_DUE_TO_CP_ONLY_NOT_APPLICABLE - NOT_SUPPORTED_WITH_ISMF -
     * CHANGED_ANCHOR_SMF - CHANGED_INTERMEDIATE_SMF - TARGET_DNAI_NOTIFICATION -
     * REL_DUE_TO_VPLMN_QOS_FAILURE - REL_DUE_TO_SMF_NOT_SUPPORT_PSETR -
     * REL_DUE_TO_SNPN_SNPN_MOBILITY - REL_DUE_TO_NO_HR_AGREEMENT -
     * REL_DUE_TO_UNSPECIFIED_REASON
     * 
     * @return cause
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Cause information. Possible values are - REL_DUE_TO_HO - EPS_FALLBACK - REL_DUE_TO_UP_SEC - DNN_CONGESTION - S_NSSAI_CONGESTION - REL_DUE_TO_REACTIVATION - 5G_AN_NOT_RESPONDING - REL_DUE_TO_SLICE_NOT_AVAILABLE - REL_DUE_TO_DUPLICATE_SESSION_ID - PDU_SESSION_STATUS_MISMATCH - HO_FAILURE - INSUFFICIENT_UP_RESOURCES - PDU_SESSION_HANDED_OVER - PDU_SESSION_RESUMED - CN_ASSISTED_RAN_PARAMETER_TUNING - ISMF_CONTEXT_TRANSFER - SMF_CONTEXT_TRANSFER - REL_DUE_TO_PS_TO_CS_HO - REL_DUE_TO_SUBSCRIPTION_CHANGE - HO_CANCEL - REL_DUE_TO_SLICE_NOT_AUTHORIZED - PDU_SESSION_HAND_OVER_FAILURE - DDN_FAILURE_STATUS - REL_DUE_TO_CP_ONLY_NOT_APPLICABLE - NOT_SUPPORTED_WITH_ISMF - CHANGED_ANCHOR_SMF - CHANGED_INTERMEDIATE_SMF - TARGET_DNAI_NOTIFICATION - REL_DUE_TO_VPLMN_QOS_FAILURE - REL_DUE_TO_SMF_NOT_SUPPORT_PSETR - REL_DUE_TO_SNPN_SNPN_MOBILITY - REL_DUE_TO_NO_HR_AGREEMENT - REL_DUE_TO_UNSPECIFIED_REASON ")
    @JsonProperty(JSON_PROPERTY_CAUSE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCause()
    {
        return cause;
    }

    @JsonProperty(JSON_PROPERTY_CAUSE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCause(String cause)
    {
        this.cause = cause;
    }

    public SmContextUpdateData ngApCause(NgApCause ngApCause)
    {

        this.ngApCause = ngApCause;
        return this;
    }

    /**
     * Get ngApCause
     * 
     * @return ngApCause
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_NG_AP_CAUSE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public NgApCause getNgApCause()
    {
        return ngApCause;
    }

    @JsonProperty(JSON_PROPERTY_NG_AP_CAUSE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNgApCause(NgApCause ngApCause)
    {
        this.ngApCause = ngApCause;
    }

    public SmContextUpdateData _5gMmCauseValue(Integer _5gMmCauseValue)
    {

        this._5gMmCauseValue = _5gMmCauseValue;
        return this;
    }

    /**
     * Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
     * minimum: 0
     * 
     * @return _5gMmCauseValue
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.")
    @JsonProperty(JSON_PROPERTY_5G_MM_CAUSE_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer get5gMmCauseValue()
    {
        return _5gMmCauseValue;
    }

    @JsonProperty(JSON_PROPERTY_5G_MM_CAUSE_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void set5gMmCauseValue(Integer _5gMmCauseValue)
    {
        this._5gMmCauseValue = _5gMmCauseValue;
    }

    public SmContextUpdateData sNssai(Snssai sNssai)
    {

        this.sNssai = sNssai;
        return this;
    }

    /**
     * Get sNssai
     * 
     * @return sNssai
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_S_NSSAI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Snssai getsNssai()
    {
        return sNssai;
    }

    @JsonProperty(JSON_PROPERTY_S_NSSAI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setsNssai(Snssai sNssai)
    {
        this.sNssai = sNssai;
    }

    public SmContextUpdateData traceData(TraceData traceData)
    {
        this.traceData = JsonNullable.<TraceData>of(traceData);

        return this;
    }

    /**
     * Get traceData
     * 
     * @return traceData
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonIgnore

    public TraceData getTraceData()
    {
        return traceData.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_TRACE_DATA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<TraceData> getTraceData_JsonNullable()
    {
        return traceData;
    }

    @JsonProperty(JSON_PROPERTY_TRACE_DATA)
    public void setTraceData_JsonNullable(JsonNullable<TraceData> traceData)
    {
        this.traceData = traceData;
    }

    public void setTraceData(TraceData traceData)
    {
        this.traceData = JsonNullable.<TraceData>of(traceData);
    }

    public SmContextUpdateData epsInterworkingInd(String epsInterworkingInd)
    {

        this.epsInterworkingInd = epsInterworkingInd;
        return this;
    }

    /**
     * EPS Interworking Indication. Possible values are - NONE - WITH_N26 -
     * WITHOUT_N26 - IWK_NON_3GPP
     * 
     * @return epsInterworkingInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "EPS Interworking Indication. Possible values are - NONE - WITH_N26 - WITHOUT_N26 - IWK_NON_3GPP ")
    @JsonProperty(JSON_PROPERTY_EPS_INTERWORKING_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getEpsInterworkingInd()
    {
        return epsInterworkingInd;
    }

    @JsonProperty(JSON_PROPERTY_EPS_INTERWORKING_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEpsInterworkingInd(String epsInterworkingInd)
    {
        this.epsInterworkingInd = epsInterworkingInd;
    }

    public SmContextUpdateData anTypeCanBeChanged(Boolean anTypeCanBeChanged)
    {

        this.anTypeCanBeChanged = anTypeCanBeChanged;
        return this;
    }

    /**
     * Get anTypeCanBeChanged
     * 
     * @return anTypeCanBeChanged
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_AN_TYPE_CAN_BE_CHANGED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAnTypeCanBeChanged()
    {
        return anTypeCanBeChanged;
    }

    @JsonProperty(JSON_PROPERTY_AN_TYPE_CAN_BE_CHANGED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAnTypeCanBeChanged(Boolean anTypeCanBeChanged)
    {
        this.anTypeCanBeChanged = anTypeCanBeChanged;
    }

    public SmContextUpdateData n2SmInfoExt1(RefToBinaryData n2SmInfoExt1)
    {

        this.n2SmInfoExt1 = n2SmInfoExt1;
        return this;
    }

    /**
     * Get n2SmInfoExt1
     * 
     * @return n2SmInfoExt1
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_N2_SM_INFO_EXT1)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public RefToBinaryData getN2SmInfoExt1()
    {
        return n2SmInfoExt1;
    }

    @JsonProperty(JSON_PROPERTY_N2_SM_INFO_EXT1)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN2SmInfoExt1(RefToBinaryData n2SmInfoExt1)
    {
        this.n2SmInfoExt1 = n2SmInfoExt1;
    }

    public SmContextUpdateData n2SmInfoTypeExt1(String n2SmInfoTypeExt1)
    {

        this.n2SmInfoTypeExt1 = n2SmInfoTypeExt1;
        return this;
    }

    /**
     * N2 SM Information Type. Possible values are - PDU_RES_SETUP_REQ -
     * PDU_RES_SETUP_RSP - PDU_RES_SETUP_FAIL - PDU_RES_REL_CMD - PDU_RES_REL_RSP -
     * PDU_RES_MOD_REQ - PDU_RES_MOD_RSP - PDU_RES_MOD_FAIL - PDU_RES_NTY -
     * PDU_RES_NTY_REL - PDU_RES_MOD_IND - PDU_RES_MOD_CFM - PATH_SWITCH_REQ -
     * PATH_SWITCH_SETUP_FAIL - PATH_SWITCH_REQ_ACK - PATH_SWITCH_REQ_FAIL -
     * HANDOVER_REQUIRED - HANDOVER_CMD - HANDOVER_PREP_FAIL - HANDOVER_REQ_ACK -
     * HANDOVER_RES_ALLOC_FAIL - SECONDARY_RAT_USAGE - PDU_RES_MOD_IND_FAIL -
     * UE_CONTEXT_RESUME_REQ - UE_CONTEXT_RESUME_RSP - UE_CONTEXT_SUSPEND_REQ
     * 
     * @return n2SmInfoTypeExt1
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "N2 SM Information Type. Possible values are - PDU_RES_SETUP_REQ - PDU_RES_SETUP_RSP - PDU_RES_SETUP_FAIL - PDU_RES_REL_CMD - PDU_RES_REL_RSP - PDU_RES_MOD_REQ - PDU_RES_MOD_RSP - PDU_RES_MOD_FAIL - PDU_RES_NTY - PDU_RES_NTY_REL - PDU_RES_MOD_IND - PDU_RES_MOD_CFM - PATH_SWITCH_REQ - PATH_SWITCH_SETUP_FAIL - PATH_SWITCH_REQ_ACK - PATH_SWITCH_REQ_FAIL - HANDOVER_REQUIRED - HANDOVER_CMD - HANDOVER_PREP_FAIL - HANDOVER_REQ_ACK - HANDOVER_RES_ALLOC_FAIL - SECONDARY_RAT_USAGE - PDU_RES_MOD_IND_FAIL - UE_CONTEXT_RESUME_REQ - UE_CONTEXT_RESUME_RSP - UE_CONTEXT_SUSPEND_REQ ")
    @JsonProperty(JSON_PROPERTY_N2_SM_INFO_TYPE_EXT1)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getN2SmInfoTypeExt1()
    {
        return n2SmInfoTypeExt1;
    }

    @JsonProperty(JSON_PROPERTY_N2_SM_INFO_TYPE_EXT1)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setN2SmInfoTypeExt1(String n2SmInfoTypeExt1)
    {
        this.n2SmInfoTypeExt1 = n2SmInfoTypeExt1;
    }

    public SmContextUpdateData maReleaseInd(String maReleaseInd)
    {

        this.maReleaseInd = maReleaseInd;
        return this;
    }

    /**
     * Multi-Access PDU session release Indication. Possible values are -
     * REL_MAPDU_OVER_3GPP - REL_MAPDU_OVER_N3GPP
     * 
     * @return maReleaseInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Multi-Access PDU session release Indication. Possible values are   - REL_MAPDU_OVER_3GPP   - REL_MAPDU_OVER_N3GPP ")
    @JsonProperty(JSON_PROPERTY_MA_RELEASE_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMaReleaseInd()
    {
        return maReleaseInd;
    }

    @JsonProperty(JSON_PROPERTY_MA_RELEASE_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaReleaseInd(String maReleaseInd)
    {
        this.maReleaseInd = maReleaseInd;
    }

    public SmContextUpdateData maNwUpgradeInd(Boolean maNwUpgradeInd)
    {

        this.maNwUpgradeInd = maNwUpgradeInd;
        return this;
    }

    /**
     * Get maNwUpgradeInd
     * 
     * @return maNwUpgradeInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_MA_NW_UPGRADE_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getMaNwUpgradeInd()
    {
        return maNwUpgradeInd;
    }

    @JsonProperty(JSON_PROPERTY_MA_NW_UPGRADE_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaNwUpgradeInd(Boolean maNwUpgradeInd)
    {
        this.maNwUpgradeInd = maNwUpgradeInd;
    }

    public SmContextUpdateData maRequestInd(Boolean maRequestInd)
    {

        this.maRequestInd = maRequestInd;
        return this;
    }

    /**
     * Get maRequestInd
     * 
     * @return maRequestInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_MA_REQUEST_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getMaRequestInd()
    {
        return maRequestInd;
    }

    @JsonProperty(JSON_PROPERTY_MA_REQUEST_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaRequestInd(Boolean maRequestInd)
    {
        this.maRequestInd = maRequestInd;
    }

    public SmContextUpdateData exemptionInd(ExemptionInd exemptionInd)
    {

        this.exemptionInd = exemptionInd;
        return this;
    }

    /**
     * Get exemptionInd
     * 
     * @return exemptionInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_EXEMPTION_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ExemptionInd getExemptionInd()
    {
        return exemptionInd;
    }

    @JsonProperty(JSON_PROPERTY_EXEMPTION_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExemptionInd(ExemptionInd exemptionInd)
    {
        this.exemptionInd = exemptionInd;
    }

    public SmContextUpdateData supportedFeatures(String supportedFeatures)
    {

        this.supportedFeatures = supportedFeatures;
        return this;
    }

    /**
     * A string used to indicate the features supported by an API that is used as
     * defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask
     * indicating supported features in hexadecimal representation Each character in
     * the string shall take a value of \&quot;0\&quot; to \&quot;9\&quot;,
     * \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to \&quot;F\&quot; and
     * shall represent the support of 4 features as described in table 5.2.2-3. The
     * most significant character representing the highest-numbered features shall
     * appear first in the string, and the character representing features 1 to 4
     * shall appear last in the string. The list of features and their numbering
     * (starting with 1) are defined separately for each API. If the string contains
     * a lower number of characters than there are defined features for an API, all
     * features that would be represented by characters that are not present in the
     * string are not supported.
     * 
     * @return supportedFeatures
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. ")
    @JsonProperty(JSON_PROPERTY_SUPPORTED_FEATURES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSupportedFeatures()
    {
        return supportedFeatures;
    }

    @JsonProperty(JSON_PROPERTY_SUPPORTED_FEATURES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSupportedFeatures(String supportedFeatures)
    {
        this.supportedFeatures = supportedFeatures;
    }

    public SmContextUpdateData moExpDataCounter(MoExpDataCounter moExpDataCounter)
    {

        this.moExpDataCounter = moExpDataCounter;
        return this;
    }

    /**
     * Get moExpDataCounter
     * 
     * @return moExpDataCounter
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_MO_EXP_DATA_COUNTER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public MoExpDataCounter getMoExpDataCounter()
    {
        return moExpDataCounter;
    }

    @JsonProperty(JSON_PROPERTY_MO_EXP_DATA_COUNTER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMoExpDataCounter(MoExpDataCounter moExpDataCounter)
    {
        this.moExpDataCounter = moExpDataCounter;
    }

    public SmContextUpdateData extendedNasSmTimerInd(Boolean extendedNasSmTimerInd)
    {

        this.extendedNasSmTimerInd = extendedNasSmTimerInd;
        return this;
    }

    /**
     * Get extendedNasSmTimerInd
     * 
     * @return extendedNasSmTimerInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_EXTENDED_NAS_SM_TIMER_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getExtendedNasSmTimerInd()
    {
        return extendedNasSmTimerInd;
    }

    @JsonProperty(JSON_PROPERTY_EXTENDED_NAS_SM_TIMER_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExtendedNasSmTimerInd(Boolean extendedNasSmTimerInd)
    {
        this.extendedNasSmTimerInd = extendedNasSmTimerInd;
    }

    public SmContextUpdateData forwardingFTeid(byte[] forwardingFTeid)
    {

        this.forwardingFTeid = forwardingFTeid;
        return this;
    }

    /**
     * string with format &#39;bytes&#39; as defined in OpenAPI
     * 
     * @return forwardingFTeid
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "string with format 'bytes' as defined in OpenAPI")
    @JsonProperty(JSON_PROPERTY_FORWARDING_F_TEID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public byte[] getForwardingFTeid()
    {
        return forwardingFTeid;
    }

    @JsonProperty(JSON_PROPERTY_FORWARDING_F_TEID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setForwardingFTeid(byte[] forwardingFTeid)
    {
        this.forwardingFTeid = forwardingFTeid;
    }

    public SmContextUpdateData forwardingBearerContexts(List<String> forwardingBearerContexts)
    {

        this.forwardingBearerContexts = forwardingBearerContexts;
        return this;
    }

    public SmContextUpdateData addForwardingBearerContextsItem(String forwardingBearerContextsItem)
    {
        if (this.forwardingBearerContexts == null)
        {
            this.forwardingBearerContexts = new ArrayList<>();
        }
        this.forwardingBearerContexts.add(forwardingBearerContextsItem);
        return this;
    }

    /**
     * Get forwardingBearerContexts
     * 
     * @return forwardingBearerContexts
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_FORWARDING_BEARER_CONTEXTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getForwardingBearerContexts()
    {
        return forwardingBearerContexts;
    }

    @JsonProperty(JSON_PROPERTY_FORWARDING_BEARER_CONTEXTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setForwardingBearerContexts(List<String> forwardingBearerContexts)
    {
        this.forwardingBearerContexts = forwardingBearerContexts;
    }

    public SmContextUpdateData ddnFailureSubs(DdnFailureSubs ddnFailureSubs)
    {

        this.ddnFailureSubs = ddnFailureSubs;
        return this;
    }

    /**
     * Get ddnFailureSubs
     * 
     * @return ddnFailureSubs
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_DDN_FAILURE_SUBS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public DdnFailureSubs getDdnFailureSubs()
    {
        return ddnFailureSubs;
    }

    @JsonProperty(JSON_PROPERTY_DDN_FAILURE_SUBS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDdnFailureSubs(DdnFailureSubs ddnFailureSubs)
    {
        this.ddnFailureSubs = ddnFailureSubs;
    }

    public SmContextUpdateData skipN2PduSessionResRelInd(Boolean skipN2PduSessionResRelInd)
    {

        this.skipN2PduSessionResRelInd = skipN2PduSessionResRelInd;
        return this;
    }

    /**
     * Get skipN2PduSessionResRelInd
     * 
     * @return skipN2PduSessionResRelInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SKIP_N2_PDU_SESSION_RES_REL_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getSkipN2PduSessionResRelInd()
    {
        return skipN2PduSessionResRelInd;
    }

    @JsonProperty(JSON_PROPERTY_SKIP_N2_PDU_SESSION_RES_REL_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSkipN2PduSessionResRelInd(Boolean skipN2PduSessionResRelInd)
    {
        this.skipN2PduSessionResRelInd = skipN2PduSessionResRelInd;
    }

    public SmContextUpdateData secondaryRatUsageDataReportContainer(List<byte[]> secondaryRatUsageDataReportContainer)
    {

        this.secondaryRatUsageDataReportContainer = secondaryRatUsageDataReportContainer;
        return this;
    }

    public SmContextUpdateData addSecondaryRatUsageDataReportContainerItem(byte[] secondaryRatUsageDataReportContainerItem)
    {
        if (this.secondaryRatUsageDataReportContainer == null)
        {
            this.secondaryRatUsageDataReportContainer = new ArrayList<>();
        }
        this.secondaryRatUsageDataReportContainer.add(secondaryRatUsageDataReportContainerItem);
        return this;
    }

    /**
     * Get secondaryRatUsageDataReportContainer
     * 
     * @return secondaryRatUsageDataReportContainer
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SECONDARY_RAT_USAGE_DATA_REPORT_CONTAINER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<byte[]> getSecondaryRatUsageDataReportContainer()
    {
        return secondaryRatUsageDataReportContainer;
    }

    @JsonProperty(JSON_PROPERTY_SECONDARY_RAT_USAGE_DATA_REPORT_CONTAINER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSecondaryRatUsageDataReportContainer(List<byte[]> secondaryRatUsageDataReportContainer)
    {
        this.secondaryRatUsageDataReportContainer = secondaryRatUsageDataReportContainer;
    }

    public SmContextUpdateData smPolicyNotifyInd(SmPolicyNotifyIndEnum smPolicyNotifyInd)
    {

        this.smPolicyNotifyInd = smPolicyNotifyInd;
        return this;
    }

    /**
     * Get smPolicyNotifyInd
     * 
     * @return smPolicyNotifyInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SM_POLICY_NOTIFY_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public SmPolicyNotifyIndEnum getSmPolicyNotifyInd()
    {
        return smPolicyNotifyInd;
    }

    @JsonProperty(JSON_PROPERTY_SM_POLICY_NOTIFY_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSmPolicyNotifyInd(SmPolicyNotifyIndEnum smPolicyNotifyInd)
    {
        this.smPolicyNotifyInd = smPolicyNotifyInd;
    }

    public SmContextUpdateData pcfUeCallbackInfo(PcfUeCallbackInfo pcfUeCallbackInfo)
    {
        this.pcfUeCallbackInfo = JsonNullable.<PcfUeCallbackInfo>of(pcfUeCallbackInfo);

        return this;
    }

    /**
     * Get pcfUeCallbackInfo
     * 
     * @return pcfUeCallbackInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonIgnore

    public PcfUeCallbackInfo getPcfUeCallbackInfo()
    {
        return pcfUeCallbackInfo.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_PCF_UE_CALLBACK_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<PcfUeCallbackInfo> getPcfUeCallbackInfo_JsonNullable()
    {
        return pcfUeCallbackInfo;
    }

    @JsonProperty(JSON_PROPERTY_PCF_UE_CALLBACK_INFO)
    public void setPcfUeCallbackInfo_JsonNullable(JsonNullable<PcfUeCallbackInfo> pcfUeCallbackInfo)
    {
        this.pcfUeCallbackInfo = pcfUeCallbackInfo;
    }

    public void setPcfUeCallbackInfo(PcfUeCallbackInfo pcfUeCallbackInfo)
    {
        this.pcfUeCallbackInfo = JsonNullable.<PcfUeCallbackInfo>of(pcfUeCallbackInfo);
    }

    public SmContextUpdateData satelliteBackhaulCat(String satelliteBackhaulCat)
    {

        this.satelliteBackhaulCat = satelliteBackhaulCat;
        return this;
    }

    /**
     * Indicates the satellite backhaul used.
     * 
     * @return satelliteBackhaulCat
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates the satellite backhaul used.")
    @JsonProperty(JSON_PROPERTY_SATELLITE_BACKHAUL_CAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSatelliteBackhaulCat()
    {
        return satelliteBackhaulCat;
    }

    @JsonProperty(JSON_PROPERTY_SATELLITE_BACKHAUL_CAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSatelliteBackhaulCat(String satelliteBackhaulCat)
    {
        this.satelliteBackhaulCat = satelliteBackhaulCat;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        SmContextUpdateData smContextUpdateData = (SmContextUpdateData) o;
        return Objects.equals(this.pei, smContextUpdateData.pei) && Objects.equals(this.servingNfId, smContextUpdateData.servingNfId)
               && Objects.equals(this.guami, smContextUpdateData.guami) && Objects.equals(this.servingNetwork, smContextUpdateData.servingNetwork)
               && equalsNullable(this.backupAmfInfo, smContextUpdateData.backupAmfInfo) && Objects.equals(this.anType, smContextUpdateData.anType)
               && Objects.equals(this.additionalAnType, smContextUpdateData.additionalAnType)
               && Objects.equals(this.anTypeToReactivate, smContextUpdateData.anTypeToReactivate) && Objects.equals(this.ratType, smContextUpdateData.ratType)
               && Objects.equals(this.presenceInLadn, smContextUpdateData.presenceInLadn) && Objects.equals(this.ueLocation, smContextUpdateData.ueLocation)
               && Objects.equals(this.ueTimeZone, smContextUpdateData.ueTimeZone) && Objects.equals(this.addUeLocation, smContextUpdateData.addUeLocation)
               && Objects.equals(this.upCnxState, smContextUpdateData.upCnxState) && Objects.equals(this.hoState, smContextUpdateData.hoState)
               && Objects.equals(this.toBeSwitched, smContextUpdateData.toBeSwitched)
               && Objects.equals(this.failedToBeSwitched, smContextUpdateData.failedToBeSwitched) && Objects.equals(this.n1SmMsg, smContextUpdateData.n1SmMsg)
               && Objects.equals(this.n2SmInfo, smContextUpdateData.n2SmInfo) && Objects.equals(this.n2SmInfoType, smContextUpdateData.n2SmInfoType)
               && Objects.equals(this.targetId, smContextUpdateData.targetId) && Objects.equals(this.targetServingNfId, smContextUpdateData.targetServingNfId)
               && Objects.equals(this.smContextStatusUri, smContextUpdateData.smContextStatusUri)
               && Objects.equals(this.dataForwarding, smContextUpdateData.dataForwarding)
               && Objects.equals(this.n9ForwardingTunnel, smContextUpdateData.n9ForwardingTunnel)
               && Objects.equals(this.n9DlForwardingTnlList, smContextUpdateData.n9DlForwardingTnlList)
               && Objects.equals(this.n9UlForwardingTnlList, smContextUpdateData.n9UlForwardingTnlList)
               && Objects.equals(this.n9DlForwardingTunnel, smContextUpdateData.n9DlForwardingTunnel)
               && Objects.equals(this.n9InactivityTimer, smContextUpdateData.n9InactivityTimer)
               && Objects.equals(this.epsBearerSetup, smContextUpdateData.epsBearerSetup)
               && Objects.equals(this.revokeEbiList, smContextUpdateData.revokeEbiList) && Objects.equals(this.release, smContextUpdateData.release)
               && Objects.equals(this.cause, smContextUpdateData.cause) && Objects.equals(this.ngApCause, smContextUpdateData.ngApCause)
               && Objects.equals(this._5gMmCauseValue, smContextUpdateData._5gMmCauseValue) && Objects.equals(this.sNssai, smContextUpdateData.sNssai)
               && equalsNullable(this.traceData, smContextUpdateData.traceData)
               && Objects.equals(this.epsInterworkingInd, smContextUpdateData.epsInterworkingInd)
               && Objects.equals(this.anTypeCanBeChanged, smContextUpdateData.anTypeCanBeChanged)
               && Objects.equals(this.n2SmInfoExt1, smContextUpdateData.n2SmInfoExt1)
               && Objects.equals(this.n2SmInfoTypeExt1, smContextUpdateData.n2SmInfoTypeExt1)
               && Objects.equals(this.maReleaseInd, smContextUpdateData.maReleaseInd) && Objects.equals(this.maNwUpgradeInd, smContextUpdateData.maNwUpgradeInd)
               && Objects.equals(this.maRequestInd, smContextUpdateData.maRequestInd) && Objects.equals(this.exemptionInd, smContextUpdateData.exemptionInd)
               && Objects.equals(this.supportedFeatures, smContextUpdateData.supportedFeatures)
               && Objects.equals(this.moExpDataCounter, smContextUpdateData.moExpDataCounter)
               && Objects.equals(this.extendedNasSmTimerInd, smContextUpdateData.extendedNasSmTimerInd)
               && Arrays.equals(this.forwardingFTeid, smContextUpdateData.forwardingFTeid)
               && Objects.equals(this.forwardingBearerContexts, smContextUpdateData.forwardingBearerContexts)
               && Objects.equals(this.ddnFailureSubs, smContextUpdateData.ddnFailureSubs)
               && Objects.equals(this.skipN2PduSessionResRelInd, smContextUpdateData.skipN2PduSessionResRelInd)
               && Objects.equals(this.secondaryRatUsageDataReportContainer, smContextUpdateData.secondaryRatUsageDataReportContainer)
               && Objects.equals(this.smPolicyNotifyInd, smContextUpdateData.smPolicyNotifyInd)
               && equalsNullable(this.pcfUeCallbackInfo, smContextUpdateData.pcfUeCallbackInfo)
               && Objects.equals(this.satelliteBackhaulCat, smContextUpdateData.satelliteBackhaulCat);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a,
                                              JsonNullable<T> b)
    {
        return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(pei,
                            servingNfId,
                            guami,
                            servingNetwork,
                            hashCodeNullable(backupAmfInfo),
                            anType,
                            additionalAnType,
                            anTypeToReactivate,
                            ratType,
                            presenceInLadn,
                            ueLocation,
                            ueTimeZone,
                            addUeLocation,
                            upCnxState,
                            hoState,
                            toBeSwitched,
                            failedToBeSwitched,
                            n1SmMsg,
                            n2SmInfo,
                            n2SmInfoType,
                            targetId,
                            targetServingNfId,
                            smContextStatusUri,
                            dataForwarding,
                            n9ForwardingTunnel,
                            n9DlForwardingTnlList,
                            n9UlForwardingTnlList,
                            n9DlForwardingTunnel,
                            n9InactivityTimer,
                            epsBearerSetup,
                            revokeEbiList,
                            release,
                            cause,
                            ngApCause,
                            _5gMmCauseValue,
                            sNssai,
                            hashCodeNullable(traceData),
                            epsInterworkingInd,
                            anTypeCanBeChanged,
                            n2SmInfoExt1,
                            n2SmInfoTypeExt1,
                            maReleaseInd,
                            maNwUpgradeInd,
                            maRequestInd,
                            exemptionInd,
                            supportedFeatures,
                            moExpDataCounter,
                            extendedNasSmTimerInd,
                            Arrays.hashCode(forwardingFTeid),
                            forwardingBearerContexts,
                            ddnFailureSubs,
                            skipN2PduSessionResRelInd,
                            secondaryRatUsageDataReportContainer,
                            smPolicyNotifyInd,
                            hashCodeNullable(pcfUeCallbackInfo),
                            satelliteBackhaulCat);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a)
    {
        if (a == null)
        {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] { a.get() }) : 31;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class SmContextUpdateData {\n");
        sb.append("    pei: ").append(toIndentedString(pei)).append("\n");
        sb.append("    servingNfId: ").append(toIndentedString(servingNfId)).append("\n");
        sb.append("    guami: ").append(toIndentedString(guami)).append("\n");
        sb.append("    servingNetwork: ").append(toIndentedString(servingNetwork)).append("\n");
        sb.append("    backupAmfInfo: ").append(toIndentedString(backupAmfInfo)).append("\n");
        sb.append("    anType: ").append(toIndentedString(anType)).append("\n");
        sb.append("    additionalAnType: ").append(toIndentedString(additionalAnType)).append("\n");
        sb.append("    anTypeToReactivate: ").append(toIndentedString(anTypeToReactivate)).append("\n");
        sb.append("    ratType: ").append(toIndentedString(ratType)).append("\n");
        sb.append("    presenceInLadn: ").append(toIndentedString(presenceInLadn)).append("\n");
        sb.append("    ueLocation: ").append(toIndentedString(ueLocation)).append("\n");
        sb.append("    ueTimeZone: ").append(toIndentedString(ueTimeZone)).append("\n");
        sb.append("    addUeLocation: ").append(toIndentedString(addUeLocation)).append("\n");
        sb.append("    upCnxState: ").append(toIndentedString(upCnxState)).append("\n");
        sb.append("    hoState: ").append(toIndentedString(hoState)).append("\n");
        sb.append("    toBeSwitched: ").append(toIndentedString(toBeSwitched)).append("\n");
        sb.append("    failedToBeSwitched: ").append(toIndentedString(failedToBeSwitched)).append("\n");
        sb.append("    n1SmMsg: ").append(toIndentedString(n1SmMsg)).append("\n");
        sb.append("    n2SmInfo: ").append(toIndentedString(n2SmInfo)).append("\n");
        sb.append("    n2SmInfoType: ").append(toIndentedString(n2SmInfoType)).append("\n");
        sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
        sb.append("    targetServingNfId: ").append(toIndentedString(targetServingNfId)).append("\n");
        sb.append("    smContextStatusUri: ").append(toIndentedString(smContextStatusUri)).append("\n");
        sb.append("    dataForwarding: ").append(toIndentedString(dataForwarding)).append("\n");
        sb.append("    n9ForwardingTunnel: ").append(toIndentedString(n9ForwardingTunnel)).append("\n");
        sb.append("    n9DlForwardingTnlList: ").append(toIndentedString(n9DlForwardingTnlList)).append("\n");
        sb.append("    n9UlForwardingTnlList: ").append(toIndentedString(n9UlForwardingTnlList)).append("\n");
        sb.append("    n9DlForwardingTunnel: ").append(toIndentedString(n9DlForwardingTunnel)).append("\n");
        sb.append("    n9InactivityTimer: ").append(toIndentedString(n9InactivityTimer)).append("\n");
        sb.append("    epsBearerSetup: ").append(toIndentedString(epsBearerSetup)).append("\n");
        sb.append("    revokeEbiList: ").append(toIndentedString(revokeEbiList)).append("\n");
        sb.append("    release: ").append(toIndentedString(release)).append("\n");
        sb.append("    cause: ").append(toIndentedString(cause)).append("\n");
        sb.append("    ngApCause: ").append(toIndentedString(ngApCause)).append("\n");
        sb.append("    _5gMmCauseValue: ").append(toIndentedString(_5gMmCauseValue)).append("\n");
        sb.append("    sNssai: ").append(toIndentedString(sNssai)).append("\n");
        sb.append("    traceData: ").append(toIndentedString(traceData)).append("\n");
        sb.append("    epsInterworkingInd: ").append(toIndentedString(epsInterworkingInd)).append("\n");
        sb.append("    anTypeCanBeChanged: ").append(toIndentedString(anTypeCanBeChanged)).append("\n");
        sb.append("    n2SmInfoExt1: ").append(toIndentedString(n2SmInfoExt1)).append("\n");
        sb.append("    n2SmInfoTypeExt1: ").append(toIndentedString(n2SmInfoTypeExt1)).append("\n");
        sb.append("    maReleaseInd: ").append(toIndentedString(maReleaseInd)).append("\n");
        sb.append("    maNwUpgradeInd: ").append(toIndentedString(maNwUpgradeInd)).append("\n");
        sb.append("    maRequestInd: ").append(toIndentedString(maRequestInd)).append("\n");
        sb.append("    exemptionInd: ").append(toIndentedString(exemptionInd)).append("\n");
        sb.append("    supportedFeatures: ").append(toIndentedString(supportedFeatures)).append("\n");
        sb.append("    moExpDataCounter: ").append(toIndentedString(moExpDataCounter)).append("\n");
        sb.append("    extendedNasSmTimerInd: ").append(toIndentedString(extendedNasSmTimerInd)).append("\n");
        sb.append("    forwardingFTeid: ").append(toIndentedString(forwardingFTeid)).append("\n");
        sb.append("    forwardingBearerContexts: ").append(toIndentedString(forwardingBearerContexts)).append("\n");
        sb.append("    ddnFailureSubs: ").append(toIndentedString(ddnFailureSubs)).append("\n");
        sb.append("    skipN2PduSessionResRelInd: ").append(toIndentedString(skipN2PduSessionResRelInd)).append("\n");
        sb.append("    secondaryRatUsageDataReportContainer: ").append(toIndentedString(secondaryRatUsageDataReportContainer)).append("\n");
        sb.append("    smPolicyNotifyInd: ").append(toIndentedString(smPolicyNotifyInd)).append("\n");
        sb.append("    pcfUeCallbackInfo: ").append(toIndentedString(pcfUeCallbackInfo)).append("\n");
        sb.append("    satelliteBackhaulCat: ").append(toIndentedString(satelliteBackhaulCat)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
