# Copyright 2019 Evo Team
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.spec.port }}
  selector:
    app: {{ .Values.service.name }}
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-deployment
  labels:
    app: {{ .Values.service.name }}
    role: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      imagePullSecrets:
      - name: {{ template "eric-k6.pullSecrets" . }}
      containers:
      - name: {{ .Values.service.name }}
        image: {{ template "eric-k6.registryUrl" . }}/{{ template "eric-k6.repoPath" . }}/{{ template "eric-k6.image" . }}:{{ template "eric-k6.tag" . }}    
        imagePullPolicy: {{ template "eric-k6.imagePullPolicy" . }}  
        ports:
        - containerPort: 80
        {{ if .Values.spec.resources.requests.cpu }}
        resources:
          requests:
            cpu: {{ .Values.spec.resources.requests.cpu | quote }}
            memory: {{ .Values.spec.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.spec.resources.limits.cpu | quote }}
            memory: {{ .Values.spec.resources.limits.memory | quote }}
        {{ end }}
      {{ if .Values.usage }}
      nodeSelector:
        usage: {{ .Values.usage }}
      tolerations:
      - key: usage
        operator: Equal
        value: {{ .Values.usage }}
        effect: "NoSchedule"
      {{ end }}
