# Copyright 2022 Ericsson GmbH
{{- if and (eq (include "eric-sepp.n32c.init.tls" .) "true") }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-sepp.name" . }}-manager-worker-client-internal-certificate
  labels:
{{- include "eric-sepp.labels" . | indent 4 }}
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: sepp-manager-worker-client-if-certificate-secret
    certificateName: tls.crt
    privateKeyName: tls.key
  certificate:
    subject:
      cn: eric-sepp-manager
    issuer:
      reference: {{ template "eric-sepp.name" . }}-worker-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}
