{{- if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.service.manager.name }}-{{ .Release.Namespace }}
  labels:
{{- include "eric-sepp.labels" . | indent 4 }}
    app: {{ .Values.service.manager.name }}
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
#    - watch
#    - create
#    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - patch
    - watch
  - apiGroups:
    - "certm.sec.ericsson.com"
    resources:
    - externalcertificates
    verbs:
    - get
    - list
    - patch
    - watch
    - create
    - update
    - delete
  - apiGroups:
    - "apps"
    resources:
    - deployments
    verbs:
    - get
    - list
    - patch
    - watch
{{- end }}
