# Copyright 2022 Ericsson GmbH
{{- if eq (include "eric-sepp.n32c.resp.tls" .) "true" }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalUserCA
metadata:
  name: {{ template "eric-sepp.name" . }}-manager-ca
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
  labels:
    {{- include "eric-sepp.labels" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-sepp.name" . }}-manager-tls-client-ca-secret
    certificateName: cacertbundle.pem
  certificate:
    subject:
      cn: {{ template "eric-sepp.name" . }}-manager-ca
  {{- end }}
