{{- if eq (include "eric-sc-nlf.tls" .) "true" }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-sc-nlf.name" . }}-alarmhandler-client-certificate
  annotations:
{{- include "eric-sc-nlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-nlf.config-annotations" . | indent 4 }}
  labels:
{{- include "eric-sc-nlf.labels" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-sc-nlf.name" . }}-alarmhandler-client-certificate
  certificate:
    subject:
      cn: {{ template "eric-sc-nlf.name" . }}
    issuer:
      reference: {{ .Values.adp.fh.alarmHandler.hostname }}-fi-server-client-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}