apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-sc-nlf.name" . }}-loglevel-config
  labels:
{{- include "eric-sc-nlf.labels" . | indent 4 }}
    app: {{ template "eric-sc-nlf.name" . }}
  annotations:
{{- include "eric-sc-nlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-nlf.config-annotations" . | indent 4 }}
data:
  logcontrol.json: |-
    [
        {
          "container": "eric-sc-nlf",
          "severity": {{ .Values.log.nlf.level | quote }}
        }
    ]
