apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata:
  name: {{ template "eric-sc-nlf.name" . }}-nrf-ca-certificate
  annotations:
{{- include "eric-sc-nlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-nlf.config-annotations" . | indent 4 }}
  labels:
    {{- include "eric-sc-nlf.labels" . | indent 4 }}
spec:
  generated-secret-name: {{ template "eric-sc-nlf.name" . }}-nrf-ca-certificate
  generated-secret-type: opaque
  trusted-certificates-file-name: "cert1.pem"
  trusted-certificate-list-name: {{ .Values.certificates.nrf.caCertificate | quote }}
