{{- $key := index .Values "certificates" "nrf" "key" }}
{{- $certificate := index .Values "certificates" "nrf" "certificate" }}
apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata:
  name: {{ template "eric-sc-nlf.name" . }}-nrf-client-certificate
  annotations:
{{- include "eric-sc-nlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-nlf.config-annotations" . | indent 4 }}
  labels:
{{- include "eric-sc-nlf.labels" . | indent 4 }}
spec:
  generated-secret-name: {{ template "eric-sc-nlf.name" . }}-nrf-client-certificate
  generated-secret-type: tls
  asymmetric-key-certificate-name: {{ printf "%s/%s" $key $certificate | quote }}
