{{- if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-sepp.name" . }}-manager
  labels:
{{- include "eric-sepp.labels" . | indent 4 }}
    app: {{ template "eric-sepp.name" . }}-manager
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "eric-sepp.name" . }}-manager-cm-key
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "eric-sepp.name" . }}-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }} 
