apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-sepp.name" . }}-manager-certificates
  labels:
{{- include "eric-sepp.labels" . | indent 4 }}
    app: {{ template "eric-sepp.name" . }}-manager
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
data:
  ca: |-
    {{- range $ca := .Values.certificates.traf.trustedAuthority }}
    {{ $ca.caList }}
    {{- end }}
  asymmetricKeyCert: |-
    {{- range $asymmetric := .Values.certificates.traf.asymmetric }}
    {{ $asymmetric.key }}
    {{ $asymmetric.certificate }}
    {{- end }}