{{- if eq (include "eric-sepp.tls" .) "true" }}
{{- if (.Values.rlf).enabled }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-sepp.name" . }}-manager-rlf-client-certificate
  labels:
{{- include "eric-sepp.labels" . | indent 4 }}
    app: {{ template "eric-sepp.name" . }}-manager
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-sepp.name" . }}-manager-rlf-client-certificate
    certificateName: tls.crt
    privateKeyName: tls.key
  certificate:
    subject:
      cn: {{ template "eric-sepp.name" . }}-manager
    issuer:
      reference: {{ .Values.sc.common.rlf.hostname }}-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}
{{- end }}