apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-sepp.name" . }}-rr
  labels:
{{- include "eric-sepp.labels" . | indent 4 }}
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
data:
  {{ template "eric-sepp.name" . }}-rr.yml: |
{{- include "eric-sepp.recording-rules" . | indent 4 }}