{{- if and (eq (include "eric-sepp.tls" .) "true")  (eq (include "eric-sepp.n32c.init.tls" .) "true") }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalUserCA
metadata:
  name: {{ template "eric-sepp.name" . }}-worker-ca
  labels:
{{- include "eric-sepp.labels" . | indent 4 }}
    app: {{ template "eric-sepp.name" . }}-worker
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-sepp.name" . }}-worker-n32c-client-ca-certificate
    certificateName: cacertbundle.pem
  certificate:
    subject:
      cn: {{ template "eric-sepp.name" . }}-worker-ca
  {{- end }}