{{- range $.Values.certificates.traf.trustedAuthority }}
apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata:
  name: {{ include "eric-sepp.name" $ }}-worker-{{ printf "%s" .caList }}-ca-certificate
  labels:
{{- include "eric-sepp.labels" $ | indent 4 }}
    app: {{ include "eric-sepp.name" $ }}
  annotations:
{{- include "eric-sepp.helm-annotations" $ | indent 4 }}
{{- include "eric-sepp.config-annotations" $ | indent 4 }}
spec:
  generated-secret-name: {{ include "eric-sepp.name" $ }}-worker-{{ printf "%s" .caList }}-ca-certificate
  generated-secret-type: opaque
  trusted-certificates-file-name: "cert1.pem"
  trusted-certificate-list-name: {{ printf "%s" .caList }}
---
{{- end }}