{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-sepp.name" . }}-worker-allow
  labels:
{{- include "eric-sepp.labels" . | indent 4 }}
    app: {{ template "eric-sepp.name" . }}-worker
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "eric-sepp.name" . }}-worker
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.adp.pm.server.hostname }}
    ports:
    - port: {{ .Values.spec.worker.metricsPort }}
      protocol: TCP
    - port: {{ .Values.tapcollector.worker.pmClientPort }}
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.adp.cm.mediator.hostname }}
    ports:
    - port: {{ .Values.spec.sds.port }}
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.sc.common.manager.hostname }}
    ports:
    - port: {{ .Values.spec.certnotifier.port }}
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "eric-sepp.name" . }}-manager
    ports:
    - port: {{ .Values.service.worker.n32c.server.port}}
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}