{{ if (((.Values.service).worker).multiVpn).enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "eric-sepp.name" . }}-worker-2
  labels:
    ericsson.com/tapcollector-traffic-service: {{ template "eric-sepp.name" . }}-worker
{{- include "eric-sepp.labels" . | indent 4 }}
    app: {{ template "eric-sepp.name" . }}-worker
  annotations:
{{- include "eric-sepp.helm-annotations" . | indent 4 }}
{{- include "eric-sepp.config-annotations" . | indent 4 }}
{{- include "eric-sepp.workerLB-annotations" . | indent 4 }}
{{- include "eric-sepp.multiVpn.metallb-annotations" . | indent 4 }}
spec:
  type: {{ .Values.service.worker.type }}
  allocateLoadBalancerNodePorts: {{ .Values.service.worker.allocateLoadBalancerNodePorts }}
  {{- include "eric-sepp.multiVpn.ipfamilypolicy" . | indent 2 }}
  # Conditional ipFamilyPolicy != "RequireDualStack"
  {{- if ne ( .Values.service.worker.multiVpn.ipFamilyPolicy | toString ) "RequireDualStack" }}
  # ipFamily value for Service type LoadBalancer
  {{- $isIpV4Enabled := include "eric-sepp.multiVpn.enabled-IPv4" .}}
  {{- $isIpV6Enabled := include "eric-sepp.multiVpn.enabled-IPv6" .}}
  {{- if ne $isIpV4Enabled $isIpV6Enabled }}
    {{- if $isIpV4Enabled }}
  ipFamilies: ["IPv4"]
    {{- end }}
    {{- if $isIpV6Enabled }}
  ipFamilies: ["IPv6"]
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if not .Values.service.worker.multiVpn.annotations.loadBalancerIPs }}
  {{- if .Values.service.worker.multiVpn.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.worker.multiVpn.loadBalancerIP | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.service.worker.multiVpn.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.worker.multiVpn.externalTrafficPolicy | quote }}
  {{ end }}
  ports:
  - name: unencrypted-port
    protocol: TCP
    port: {{ .Values.service.worker.multiVpn.port }}
    targetPort: {{ .Values.service.worker.multiVpn.port2Name }}
  - name: encrypted-port
    protocol: TCP
    port: {{ .Values.service.worker.multiVpn.tlsport }}
    targetPort: {{ .Values.service.worker.multiVpn.tlsPort2Name }}
  selector:
    app: {{ template "eric-sepp.name" . }}-worker
{{- end }}
