{{ if index .Values "eric-sc" "rbac" "clusterMonitoring" "create" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eric-sc.cluster-monitoring" . }}
  labels:
{{- include "eric-sc.de-facto-labels" . | indent 4 }}
  annotations:
{{- include "eric-sc.product-annotations" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eric-sc.cluster-monitoring" . }}
subjects:
- kind: ServiceAccount
  name: {{ index .Values "eric-pm-server" "server" "serviceAccountName" | quote }}
  namespace: {{ .Release.Namespace }}
{{- end }}
