{{ if index .Values "eric-sc" "rbac" "clusterMonitoring" "create" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eric-sc.cluster-monitoring" . }}
  labels:
{{- include "eric-sc.de-facto-labels" . | indent 4 }}
  annotations:
{{- include "eric-sc.product-annotations" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get "/metrics"
    verbs:
      - get
{{- end }}
