{{ if index .Values "eric-sc" "rbac" "clusterMonitoring" "create" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ index .Values "eric-pm-server" "server" "serviceAccountName" }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "eric-sc.de-facto-labels" . | indent 4 }}
  annotations:
{{- include "eric-sc.product-annotations" . | indent 4 }}
{{- end }}
