{{- $key := index .Values "eric-sc" "certificates" "nbi" "key" }}
{{- $certificate := index .Values "eric-sc" "certificates" "nbi" "certificate" }}
apiVersion: certm.sec.ericsson.com/v1 
kind: ExternalCertificate
metadata: 
  name: nbi-certs-consumer-cr
spec: 
  generated-secret-name: {{ index .Values "eric-sc" "certificates" "nbi" "secret" | quote }}
  generated-secret-type: tls
  asymmetric-key-certificate-name:  {{ printf "%s/%s" $key $certificate | quote }}
