apiVersion:  certm.sec.ericsson.com/v1 
kind: ExternalCertificate
metadata:
  name: "eric-sc-trusted-ca-cr"
spec:
  generated-secret-name: "eric-sc-trusted-ca"
  generated-secret-type: opaque
  trusted-certificates-file-name: "ca.crt"
  trusted-certificate-list-name: {{ index .Values "eric-sc" "certificates" "trustedCAs" "certificateList" | quote }}
