apiVersion:  certm.sec.ericsson.com/v1 
kind: ExternalCertificate
metadata:
  name: trusted-certificate-authorities-cr
spec:
  generated-secret-name: {{ index .Values "eric-sc" "certificates" "trustedCAs" "secret" | quote }}
  generated-secret-type: opaque
  trusted-certificates-file-name: "cert1.pem"
  trusted-certificate-list-name: {{ index .Values "eric-sc" "certificates" "trustedCAs" "certificateList" | quote }}
