{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
# START. DND-37533: Network Policies file additions/changes.
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "eric-stm-diameter-proxy-grpc.name" . }}-allow
  labels:
    app: {{ template "eric-stm-diameter-proxy-grpc.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "eric-stm-diameter-proxy-grpc.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.adp.cm.mediator.hostname }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.adp.pm.server.hostname }}
    ports:
    - port: {{ .Values.service.diameter.server.oam.port }}
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.adp.pm.server.hostname }}
    ports:
    - port: {{ .Values.spec.cddjmxexporter.port }}
      protocol: TCP 
# STOP. DND-37533: Network Policies file additions/changes.
{{- end }}
{{- end }}
{{- end }}

