{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-stm-diameter-proxy-grpc.name" . }}-dsl-access
  labels:
{{- if (include "eric-stm-diameter-proxy-grpc.labels" .) }}
{{- include "eric-stm-diameter-proxy-grpc.labels" . | nindent 4 }}
{{- end }}
  annotations:
{{- if (include "eric-stm-diameter-proxy-grpc.annotations" .) }}
{{- include "eric-stm-diameter-proxy-grpc.annotations" . | nindent 4 }}
{{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-stm-diameter-proxy-grpc.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{ .Values.initialConfig.dsl.serviceName }}-access: "true"
{{- end }}
{{- end }}
{{- end }}
