{{- if eq (include "eric-stm-diameter-proxy-grpc.should.use.legacy.rb" .) "true" }}
{{- if .Values.global }}
{{- if .Values.global.security }}
{{- if .Values.global.security.policyBinding }}
{{- if .Values.global.security.policyBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-stm-diameter-proxy-grpc.name" . }}-role-binding
  labels:
{{- if (include "eric-stm-diameter-proxy-grpc.labels" .) }}
{{- include "eric-stm-diameter-proxy-grpc.labels" . | nindent 4 }}
{{- end }}
  annotations:
{{- if (include "eric-stm-diameter-proxy-grpc.annotations" .) }}
{{- include "eric-stm-diameter-proxy-grpc.annotations" . | nindent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "eric-stm-diameter-proxy-grpc.securityPolicy.reference.default-restricted-security-policy.0" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-stm-diameter-proxy-grpc.name" . }}-service-account
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
