/*
 * AUSF API
 * AUSF UE Authentication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29509.nausf.ueauthentication;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Successful authentication for CP-PRUK ID.
 */
@ApiModel(description = "Successful authentication for CP-PRUK ID.")
@JsonPropertyOrder({ ProSeAuthenticationResult.JSON_PROPERTY_KNR_PRO_SE,
                     ProSeAuthenticationResult.JSON_PROPERTY_NONCE2,
                     ProSeAuthenticationResult.JSON_PROPERTY_SUPPORTED_FEATURES })
public class ProSeAuthenticationResult
{
    public static final String JSON_PROPERTY_KNR_PRO_SE = "knrProSe";
    private String knrProSe;

    public static final String JSON_PROPERTY_NONCE2 = "nonce2";
    private JsonNullable<byte[]> nonce2 = JsonNullable.<byte[]>undefined();

    public static final String JSON_PROPERTY_SUPPORTED_FEATURES = "supportedFeatures";
    private String supportedFeatures;

    public ProSeAuthenticationResult()
    {
    }

    public ProSeAuthenticationResult knrProSe(String knrProSe)
    {

        this.knrProSe = knrProSe;
        return this;
    }

    /**
     * Contains the KNR_ProSe.
     * 
     * @return knrProSe
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Contains the KNR_ProSe.")
    @JsonProperty(JSON_PROPERTY_KNR_PRO_SE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKnrProSe()
    {
        return knrProSe;
    }

    @JsonProperty(JSON_PROPERTY_KNR_PRO_SE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKnrProSe(String knrProSe)
    {
        this.knrProSe = knrProSe;
    }

    public ProSeAuthenticationResult nonce2(byte[] nonce2)
    {
        this.nonce2 = JsonNullable.<byte[]>of(nonce2);

        return this;
    }

    /**
     * contains an Nonce2
     * 
     * @return nonce2
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "contains an Nonce2")
    @JsonIgnore

    public byte[] getNonce2()
    {
        return nonce2.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_NONCE2)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<byte[]> getNonce2_JsonNullable()
    {
        return nonce2;
    }

    @JsonProperty(JSON_PROPERTY_NONCE2)
    public void setNonce2_JsonNullable(JsonNullable<byte[]> nonce2)
    {
        this.nonce2 = nonce2;
    }

    public void setNonce2(byte[] nonce2)
    {
        this.nonce2 = JsonNullable.<byte[]>of(nonce2);
    }

    public ProSeAuthenticationResult supportedFeatures(String supportedFeatures)
    {

        this.supportedFeatures = supportedFeatures;
        return this;
    }

    /**
     * A string used to indicate the features supported by an API that is used as
     * defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask
     * indicating supported features in hexadecimal representation Each character in
     * the string shall take a value of \&quot;0\&quot; to \&quot;9\&quot;,
     * \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to \&quot;F\&quot; and
     * shall represent the support of 4 features as described in table 5.2.2-3. The
     * most significant character representing the highest-numbered features shall
     * appear first in the string, and the character representing features 1 to 4
     * shall appear last in the string. The list of features and their numbering
     * (starting with 1) are defined separately for each API. If the string contains
     * a lower number of characters than there are defined features for an API, all
     * features that would be represented by characters that are not present in the
     * string are not supported.
     * 
     * @return supportedFeatures
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. ")
    @JsonProperty(JSON_PROPERTY_SUPPORTED_FEATURES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSupportedFeatures()
    {
        return supportedFeatures;
    }

    @JsonProperty(JSON_PROPERTY_SUPPORTED_FEATURES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSupportedFeatures(String supportedFeatures)
    {
        this.supportedFeatures = supportedFeatures;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        ProSeAuthenticationResult proSeAuthenticationResult = (ProSeAuthenticationResult) o;
        return Objects.equals(this.knrProSe, proSeAuthenticationResult.knrProSe) && equalsNullable(this.nonce2, proSeAuthenticationResult.nonce2)
               && Objects.equals(this.supportedFeatures, proSeAuthenticationResult.supportedFeatures);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a,
                                              JsonNullable<T> b)
    {
        return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(knrProSe, hashCodeNullable(nonce2), supportedFeatures);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a)
    {
        if (a == null)
        {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] { a.get() }) : 31;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProSeAuthenticationResult {\n");
        sb.append("    knrProSe: ").append(toIndentedString(knrProSe)).append("\n");
        sb.append("    nonce2: ").append(toIndentedString(nonce2)).append("\n");
        sb.append("    supportedFeatures: ").append(toIndentedString(supportedFeatures)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
