apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
spec:
  selector:
    app: {{ .Values.service.name | quote }}
  ports:
    - protocol: UDP
      port: 162
      targetPort: 162
