Version: v2
Decription: FOSS list
LastUpdate: 2024-03-29 12:28
FOSS:
    # Available in Bazaar
    FOSSName: swagger-parser
    # Available in Bazaar
    FOSSVersion: 2.1.21
    # Available in Bazaar >>> used as kind of ID.
    FOSSURL: https://github.com/swagger-api/swagger-parser/archive/v{{FOSSVersion}}.tar.gz
    # Available in Bazaar
    PRIMNumber(CAX/CTX): 51/CAX1059391
    # Not Available in Bazaar
    Primary: Y
    # Available in Bazaar
    STAKOCode: General use
    # Available in Bazaar
    STAKOReason: NA
    # Not Available in Bazaar    
    FunctionalityUsedInTheEricssonProduct: Swagger Spec to Java POJOs
    # Available in Bazaar. Not used for specific report. >>> Includes _list_ of licenses taken from Bazaar
    AvailableLicenses: Apache License 2.0
    # Not available in Bazaar, >>> FAL should be factored out into separate mapping file
    ChoiceOfLicense: Apache License 2.0
    # Not Available in Bazaar >>> list of algorithms used (instead of bool)
    CryptographicAlgorithmsUsed: ()
    # Not Available in Bazaar
    CryptographicAlgorithmsUsedDescription: NA
    # Not Available in Bazaar >>> list
    SecureProtocolsUsed: ()
    # Not Available in Bazaar
    SecureProtocolsUsedDescription: NA
    # Select one of the following: Statically, Dynamically, Classpath, NotLinked. Not Available in Bazaar
    EricssonCodeLinkedWithTheFOSSCode: Dynamically
    # Not Available in Bazaar
    MavenDependency: 
    - 'io.swagger.parser.v3:swagger-parser-core:jar:{{FOSSVersion}}'
    - 'io.swagger.parser.v3:swagger-parser-safe-url-resolver:jar:{{FOSSVersion}}'
    - 'io.swagger.parser.v3:swagger-parser-v2-converter:jar:{{FOSSVersion}}'
    - 'io.swagger.parser.v3:swagger-parser-v3:jar:{{FOSSVersion}}'
    - 'io.swagger.parser.v3:swagger-parser:jar:{{FOSSVersion}}'
    - 'io.swagger:swagger-compat-spec-parser:jar:1.0.69'
    - 'io.swagger:swagger-parser:jar:1.0.69'
    - 'io.swagger:swagger-parser-safe-url-resolver:jar:1.0.69'
    # >>> New attribute:
    # If yes, the default values of /scripts/fossReport/templates/defaultTemplate.yaml are not taken into account.
    # In this case, the yaml attributes of the defaultTemplate.yaml should be copied in this file with the desired values.
    ManualSpecificFOSSEvaluation: NO
    ReportAuthor: XEIRPAP Eirini Papastefanaki


