Version: v2
Decription: FOSS list
LastUpdate: 2023-11-14 15:58
FOSS:
    # Available in Bazaar
    FOSSName: config, Typesafe
    # Available in Bazaar
    FOSSVersion: 1.4.1
    # Available in Bazaar >>> used as kind of ID.
    FOSSURL: https://github.com/lightbend/config/archive/v{{FOSSVersion}}.zip
    # Available in Bazaar
    PRIMNumber(CAX/CTX): 10/CAX1056770
    # Not Available in Bazaar
    Primary: N
    # Available in Bazaar
    STAKOCode: Restricted Use
    # Available in Bazaar
    STAKOReason: Product verison is older than 18 months
    # Not Available in Bazaar
    FunctionalityUsedInTheEricssonProduct: This is a configuration library for JVM languages.
    # Available in Bazaar. Not used for specific report. >>> Includes _list_ of licenses taken from Bazaar
    AvailableLicenses: Apache License 2.0
    # Not available in Bazaar, >>> FAL should be factored out into separate mapping file
    ChoiceOfLicense: Apache License 2.0
    # Not Available in Bazaar >>> list of algorithms used (instead of bool)
    CryptographicAlgorithmsUsed: ()
    # Not Available in Bazaar
    CryptographicAlgorithmsUsedDescription: NA
    # Not Available in Bazaar >>> list
    SecureProtocolsUsed: ()
    # Not Available in Bazaar
    SecureProtocolsUsedDescription: NA
    # Select one of the following: Statically, Dynamically, Classpath, NotLinked. Not Available in Bazaar
    EricssonCodeLinkedWithTheFOSSCode: Dynamically
    # Not Available in Bazaar
    MavenDependency:
    - 'com.typesafe:config:jar:{{FOSSVersion}}'
    # >>> New attribute:
    # If yes, the default values of /scripts/fossReport/templates/defaultTemplate.yaml are not taken into account.
    # In this case, the yaml attributes of the defaultTemplate.yaml should be copied in this file with the desired values.
    ManualSpecificFOSSEvaluation: NO
    ReportAuthor: ZARISAR Aristeidis Sarras
