/*
 * NSSF NSSAI Availability
 * 
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * 
 * This file has been auto-generated by the yaml2java script.
 */

package com.ericsson.cnal.openapi.r17.ts29531.nnssf.nssaiavailability;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * NssfEventType
 */
public class NssfEventType
{
    public static final String SNSSAI_STATUS_CHANGE_REPORT = "SNSSAI_STATUS_CHANGE_REPORT";

}
