/*
 * NSSF NSSAI Availability
 * NSSF NSSAI Availability Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29531.nnssf.nssaiavailability;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.PlmnId;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.ExtSnssai;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * This contains the restricted SNssai information per PLMN
 */
@ApiModel(description = "This contains the restricted SNssai information per PLMN")
@JsonPropertyOrder({ RestrictedSnssai.JSON_PROPERTY_HOME_PLMN_ID,
                     RestrictedSnssai.JSON_PROPERTY_S_NSSAI_LIST,
                     RestrictedSnssai.JSON_PROPERTY_HOME_PLMN_ID_LIST,
                     RestrictedSnssai.JSON_PROPERTY_ROAMING_RESTRICTION })
public class RestrictedSnssai
{
    public static final String JSON_PROPERTY_HOME_PLMN_ID = "homePlmnId";
    private PlmnId homePlmnId;

    public static final String JSON_PROPERTY_S_NSSAI_LIST = "sNssaiList";
    private List<ExtSnssai> sNssaiList = new ArrayList<>();

    public static final String JSON_PROPERTY_HOME_PLMN_ID_LIST = "homePlmnIdList";
    private List<PlmnId> homePlmnIdList = null;

    public static final String JSON_PROPERTY_ROAMING_RESTRICTION = "roamingRestriction";
    private Boolean roamingRestriction = false;

    public RestrictedSnssai()
    {
    }

    public RestrictedSnssai homePlmnId(PlmnId homePlmnId)
    {

        this.homePlmnId = homePlmnId;
        return this;
    }

    /**
     * Get homePlmnId
     * 
     * @return homePlmnId
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_HOME_PLMN_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public PlmnId getHomePlmnId()
    {
        return homePlmnId;
    }

    @JsonProperty(JSON_PROPERTY_HOME_PLMN_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHomePlmnId(PlmnId homePlmnId)
    {
        this.homePlmnId = homePlmnId;
    }

    public RestrictedSnssai sNssaiList(List<ExtSnssai> sNssaiList)
    {

        this.sNssaiList = sNssaiList;
        return this;
    }

    public RestrictedSnssai addSNssaiListItem(ExtSnssai sNssaiListItem)
    {
        this.sNssaiList.add(sNssaiListItem);
        return this;
    }

    /**
     * Get sNssaiList
     * 
     * @return sNssaiList
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_S_NSSAI_LIST)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<ExtSnssai> getsNssaiList()
    {
        return sNssaiList;
    }

    @JsonProperty(JSON_PROPERTY_S_NSSAI_LIST)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setsNssaiList(List<ExtSnssai> sNssaiList)
    {
        this.sNssaiList = sNssaiList;
    }

    public RestrictedSnssai homePlmnIdList(List<PlmnId> homePlmnIdList)
    {

        this.homePlmnIdList = homePlmnIdList;
        return this;
    }

    public RestrictedSnssai addHomePlmnIdListItem(PlmnId homePlmnIdListItem)
    {
        if (this.homePlmnIdList == null)
        {
            this.homePlmnIdList = new ArrayList<>();
        }
        this.homePlmnIdList.add(homePlmnIdListItem);
        return this;
    }

    /**
     * Get homePlmnIdList
     * 
     * @return homePlmnIdList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_HOME_PLMN_ID_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<PlmnId> getHomePlmnIdList()
    {
        return homePlmnIdList;
    }

    @JsonProperty(JSON_PROPERTY_HOME_PLMN_ID_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHomePlmnIdList(List<PlmnId> homePlmnIdList)
    {
        this.homePlmnIdList = homePlmnIdList;
    }

    public RestrictedSnssai roamingRestriction(Boolean roamingRestriction)
    {

        this.roamingRestriction = roamingRestriction;
        return this;
    }

    /**
     * Get roamingRestriction
     * 
     * @return roamingRestriction
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ROAMING_RESTRICTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRoamingRestriction()
    {
        return roamingRestriction;
    }

    @JsonProperty(JSON_PROPERTY_ROAMING_RESTRICTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRoamingRestriction(Boolean roamingRestriction)
    {
        this.roamingRestriction = roamingRestriction;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        RestrictedSnssai restrictedSnssai = (RestrictedSnssai) o;
        return Objects.equals(this.homePlmnId, restrictedSnssai.homePlmnId) && Objects.equals(this.sNssaiList, restrictedSnssai.sNssaiList)
               && Objects.equals(this.homePlmnIdList, restrictedSnssai.homePlmnIdList)
               && Objects.equals(this.roamingRestriction, restrictedSnssai.roamingRestriction);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(homePlmnId, sNssaiList, homePlmnIdList, roamingRestriction);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class RestrictedSnssai {\n");
        sb.append("    homePlmnId: ").append(toIndentedString(homePlmnId)).append("\n");
        sb.append("    sNssaiList: ").append(toIndentedString(sNssaiList)).append("\n");
        sb.append("    homePlmnIdList: ").append(toIndentedString(homePlmnIdList)).append("\n");
        sb.append("    roamingRestriction: ").append(toIndentedString(roamingRestriction)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
