{{- if eq (include "eric-stm-diameter-proxy-grpc.log-streaming-activated" .) "true" }}
{{- if  eq (default "" ((((.Values).global).logShipper).deployment).model) "static" }}
  {{- include "eric-stm-diameter-proxy-grpc.logshipper-tls-cert-lt-client" . }}
{{- else }}
  {{- include "eric-log-shipper-sidecar.logshipper-tls-cert-lt-client" . }}
{{- end }}
{{- end }}
