{{- define "eric-sc-nlf.de-facto-labels" }}
app.kubernetes.io/name: {{ template "eric-sc-nlf.name" . }}
app.kubernetes.io/version: {{ template "eric-sc-nlf.version" . }}
app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- end}}
