{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.service.nlf.name }}-default-access
  labels:
{{- include "eric-sc-nlf.labels" . | indent 4 }}
    app: {{ .Values.service.nlf.name | quote }}
  annotations:
{{- include "eric-sc-nlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-nlf.config-annotations" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.service.nlf.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{ .Values.service.nlf.name }}-access: "true"
    ports:
    - port: {{ .Values.service.nlf.restOam.targetPortName }}
      protocol: TCP
    - port: {{ .Values.service.nlf.rest.targetPortName }}
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}

