#!/bin/bash

# ===================================================================
# COPYRIGHT ERICSSON GMBH 2019
#
# The copyright to the computer program(s) herein is the property
# of Ericsson GmbH, Germany.
#
# The program(s) may be used and/or copied only with the written
# permission of Ericsson GmbH in accordance with
# the terms and conditions stipulated in the agreement/contract
# under which the program(s) have been supplied.
#
# Created on: Nov 25, 2019
#     Author: eedstl
# ===================================================================
#
# Wrapper around script log2human.jq
#
# ===================================================================

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
jq -r -R -f ${DIR}/log2human.jq

