Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1804.02"

  config.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.cpus = 2
      vb.memory = "5120"
      vb.disksize.size = '40GB'
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  config.vm.synced_folder "../../../5g_proto", "/hostdata/5g_proto"
end

