{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "eric-bsf.name" . }}-manager-allow
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ template "eric-bsf.name" . }}-manager
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "eric-bsf.name" . }}-manager
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.adp.cm.yangProvider.hostname }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.adp.cm.mediator.hostname }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.adp.pm.server.hostname }}
    ports:
    - port: {{ .Values.service.manager.server.oam.port }}
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.sc.common.monitor.hostname }}
    ports:
    - port: {{ .Values.probes.manager.port }}
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}