{{- if eq (include "eric-bsf.tls" .) "true" }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-bsf.name" . }}-manager-fhah-client-certificate
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ template "eric-bsf.name" . }}-manager
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-bsf.name" . }}-manager-fhah-client-certificate
  certificate:
    subject:
      cn: {{ template "eric-bsf.name" . }}-manager
    issuer:
      reference: {{ .Values.adp.fh.alarmHandler.hostname }}-fi-server-client-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}