# Copyright 2022 Ericsson GmbH
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-bsf.name" . }}-manager
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ template "eric-bsf.name" . }}-manager
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
{{- if .Values.metrics.manager.enabled }}
    prometheus.io/scrape: {{ .Values.metrics.manager.enabled | quote }}
{{- if eq (include "eric-bsf.tls" .) "true" }}
    prometheus.io/scheme: https
{{- else }}
    prometheus.io/scheme: http
{{- end }}
{{- end }}
spec:
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
{{- include "eric-bsf.ipfamilies" . | indent 2 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.manager.server.oam.port }}
    targetPort: {{ .Values.service.manager.server.oam.targetPort }}
    name: oam-server
  selector:
  {{- if .Values.manager.leaderElection.enabled }}
    leader: {{ template "eric-bsf.name" . }}-manager-leader
  {{- else }}
    app: {{ template "eric-bsf.name" . }}-manager
  {{- end }}