apiVersion:  certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata:
  name: {{ template "eric-bsf.name" . }}-worker-ca-certificate
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ template "eric-bsf.name" . }}-worker
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
spec:
  generated-secret-name: {{ template "eric-bsf.name" . }}-worker-ca-certificate
  generated-secret-type: opaque
  trusted-certificates-file-name: "cert1.pem"
  trusted-certificate-list-name: {{ .Values.certificates.traf.caCertificate | quote }}
