apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-bsf.name" . }}-worker-log-ctrl
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ template "eric-bsf.name" . }}-worker
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
data:
  logcontrol.json: |-
    [
        {
          "container": "eric-bsf-cert-notifier",
          "severity": {{ .Values.log.certnotifier.level | quote }}
        },
        {
          "container": "eric-bsf-worker",
          "severity": {{ .Values.log.worker.level | quote }}
        }{{- if eq (include "eric-bsf.tapcollector.worker.enabled" .) "true" }},
        {
          "container": "tapcollector",
          "severity": {{ .Values.log.tapcollector.level | quote }}
        }{{- end }}{{- if eq (include "eric-bsf.tapagent.worker.enabled" .) "true" }},
        {
          "container": "tlskeylogagent",
          "severity": {{ .Values.log.tlskeylogagent.level | quote}}
        }{{- end }}
    ]