/*
 * Naf_EventExposure
 * AF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29517.naf.eventexposure;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Contains Performance Data.
 */
@ApiModel(description = "Contains Performance Data.")
@JsonPropertyOrder({ PerformanceData.JSON_PROPERTY_PDB,
                     PerformanceData.JSON_PROPERTY_PLR,
                     PerformanceData.JSON_PROPERTY_THRPUT_UL,
                     PerformanceData.JSON_PROPERTY_THRPUT_DL })
public class PerformanceData
{
    public static final String JSON_PROPERTY_PDB = "pdb";
    private Integer pdb;

    public static final String JSON_PROPERTY_PLR = "plr";
    private Integer plr;

    public static final String JSON_PROPERTY_THRPUT_UL = "thrputUl";
    private String thrputUl;

    public static final String JSON_PROPERTY_THRPUT_DL = "thrputDl";
    private String thrputDl;

    public PerformanceData()
    {
    }

    public PerformanceData pdb(Integer pdb)
    {

        this.pdb = pdb;
        return this;
    }

    /**
     * Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and
     * 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. minimum: 1
     * 
     * @return pdb
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. ")
    @JsonProperty(JSON_PROPERTY_PDB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getPdb()
    {
        return pdb;
    }

    @JsonProperty(JSON_PROPERTY_PDB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPdb(Integer pdb)
    {
        this.pdb = pdb;
    }

    public PerformanceData plr(Integer plr)
    {

        this.plr = plr;
        return this;
    }

    /**
     * Unsigned integer indicating Packet Loss Rate (see clauses 5.7.2.8 and 5.7.4
     * of 3GPP TS 23.501), expressed in tenth of percent. minimum: 0 maximum: 1000
     * 
     * @return plr
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Unsigned integer indicating Packet Loss Rate (see clauses 5.7.2.8 and 5.7.4 of 3GPP TS 23.501), expressed in tenth of percent. ")
    @JsonProperty(JSON_PROPERTY_PLR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getPlr()
    {
        return plr;
    }

    @JsonProperty(JSON_PROPERTY_PLR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlr(Integer plr)
    {
        this.plr = plr;
    }

    public PerformanceData thrputUl(String thrputUl)
    {

        this.thrputUl = thrputUl;
        return this;
    }

    /**
     * String representing a bit rate; the prefixes follow the standard symbols from
     * The International System of Units, and represent x1000 multipliers, with the
     * exception that prefix \&quot;K\&quot; is used to represent the standard
     * symbol \&quot;k\&quot;.
     * 
     * @return thrputUl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ")
    @JsonProperty(JSON_PROPERTY_THRPUT_UL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getThrputUl()
    {
        return thrputUl;
    }

    @JsonProperty(JSON_PROPERTY_THRPUT_UL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setThrputUl(String thrputUl)
    {
        this.thrputUl = thrputUl;
    }

    public PerformanceData thrputDl(String thrputDl)
    {

        this.thrputDl = thrputDl;
        return this;
    }

    /**
     * String representing a bit rate; the prefixes follow the standard symbols from
     * The International System of Units, and represent x1000 multipliers, with the
     * exception that prefix \&quot;K\&quot; is used to represent the standard
     * symbol \&quot;k\&quot;.
     * 
     * @return thrputDl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ")
    @JsonProperty(JSON_PROPERTY_THRPUT_DL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getThrputDl()
    {
        return thrputDl;
    }

    @JsonProperty(JSON_PROPERTY_THRPUT_DL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setThrputDl(String thrputDl)
    {
        this.thrputDl = thrputDl;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        PerformanceData performanceData = (PerformanceData) o;
        return Objects.equals(this.pdb, performanceData.pdb) && Objects.equals(this.plr, performanceData.plr)
               && Objects.equals(this.thrputUl, performanceData.thrputUl) && Objects.equals(this.thrputDl, performanceData.thrputDl);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(pdb, plr, thrputUl, thrputDl);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class PerformanceData {\n");
        sb.append("    pdb: ").append(toIndentedString(pdb)).append("\n");
        sb.append("    plr: ").append(toIndentedString(plr)).append("\n");
        sb.append("    thrputUl: ").append(toIndentedString(thrputUl)).append("\n");
        sb.append("    thrputDl: ").append(toIndentedString(thrputDl)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
