{{- if .Values.rbac.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}
  labels:
{{- include "eric-loadgen.labels" . | indent 4 }}
    app: {{ .Values.service.name }} 
  annotations:
{{- include "eric-loadgen.helm-annotations" . | indent 4 }}
{{- include "eric-loadgen.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
