/*
 * Namf_Communication
 * AMF Communication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29518.namf.communication;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.NgApCause;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data within a Release UE Context request
 */
@ApiModel(description = "Data within a Release UE Context request")
@JsonPropertyOrder({ UEContextRelease.JSON_PROPERTY_SUPI, UEContextRelease.JSON_PROPERTY_UNAUTHENTICATED_SUPI, UEContextRelease.JSON_PROPERTY_NGAP_CAUSE })
public class UEContextRelease
{
    public static final String JSON_PROPERTY_SUPI = "supi";
    private String supi;

    public static final String JSON_PROPERTY_UNAUTHENTICATED_SUPI = "unauthenticatedSupi";
    private Boolean unauthenticatedSupi = false;

    public static final String JSON_PROPERTY_NGAP_CAUSE = "ngapCause";
    private NgApCause ngapCause;

    public UEContextRelease()
    {
    }

    public UEContextRelease supi(String supi)
    {

        this.supi = supi;
        return this;
    }

    /**
     * String identifying a Supi that shall contain either an IMSI, a network
     * specific identifier, a Global Cable Identifier (GCI) or a Global Line
     * Identifier (GLI) as specified in clause 2.2A of 3GPP TS 23.003. It shall be
     * formatted as follows - for an IMSI \&quot;imsi-&lt;imsi&gt;\&quot;, where
     * &lt;imsi&gt; shall be formatted according to clause 2.2 of 3GPP TS 23.003
     * that describes an IMSI. - for a network specific identifier
     * \&quot;nai-&lt;nai&gt;, where &lt;nai&gt; shall be formatted according to
     * clause 28.7.2 of 3GPP TS 23.003 that describes an NAI. - for a GCI
     * \&quot;gci-&lt;gci&gt;\&quot;, where &lt;gci&gt; shall be formatted according
     * to clause 28.15.2 of 3GPP TS 23.003. - for a GLI
     * \&quot;gli-&lt;gli&gt;\&quot;, where &lt;gli&gt; shall be formatted according
     * to clause 28.16.2 of 3GPP TS 23.003.To enable that the value is used as part
     * of an URI, the string shall only contain characters allowed according to the
     * \&quot;lower-with-hyphen\&quot; naming convention defined in 3GPP TS 29.501.
     * 
     * @return supi
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501. ")
    @JsonProperty(JSON_PROPERTY_SUPI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSupi()
    {
        return supi;
    }

    @JsonProperty(JSON_PROPERTY_SUPI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSupi(String supi)
    {
        this.supi = supi;
    }

    public UEContextRelease unauthenticatedSupi(Boolean unauthenticatedSupi)
    {

        this.unauthenticatedSupi = unauthenticatedSupi;
        return this;
    }

    /**
     * Get unauthenticatedSupi
     * 
     * @return unauthenticatedSupi
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_UNAUTHENTICATED_SUPI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getUnauthenticatedSupi()
    {
        return unauthenticatedSupi;
    }

    @JsonProperty(JSON_PROPERTY_UNAUTHENTICATED_SUPI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUnauthenticatedSupi(Boolean unauthenticatedSupi)
    {
        this.unauthenticatedSupi = unauthenticatedSupi;
    }

    public UEContextRelease ngapCause(NgApCause ngapCause)
    {

        this.ngapCause = ngapCause;
        return this;
    }

    /**
     * Get ngapCause
     * 
     * @return ngapCause
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_NGAP_CAUSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public NgApCause getNgapCause()
    {
        return ngapCause;
    }

    @JsonProperty(JSON_PROPERTY_NGAP_CAUSE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNgapCause(NgApCause ngapCause)
    {
        this.ngapCause = ngapCause;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        UEContextRelease ueContextRelease = (UEContextRelease) o;
        return Objects.equals(this.supi, ueContextRelease.supi) && Objects.equals(this.unauthenticatedSupi, ueContextRelease.unauthenticatedSupi)
               && Objects.equals(this.ngapCause, ueContextRelease.ngapCause);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(supi, unauthenticatedSupi, ngapCause);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class UEContextRelease {\n");
        sb.append("    supi: ").append(toIndentedString(supi)).append("\n");
        sb.append("    unauthenticatedSupi: ").append(toIndentedString(unauthenticatedSupi)).append("\n");
        sb.append("    ngapCause: ").append(toIndentedString(ngapCause)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
