/*
 * Namf_Communication
 * AMF Communication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29518.namf.communication;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data within a UE registration status update response to provide the status of
 * UE context transfer status update at a source AMF
 */
@ApiModel(description = "Data within a UE registration status update response to provide the status of UE context transfer status update at a source AMF")
@JsonPropertyOrder({ UeRegStatusUpdateRspData.JSON_PROPERTY_REG_STATUS_TRANSFER_COMPLETE })
public class UeRegStatusUpdateRspData
{
    public static final String JSON_PROPERTY_REG_STATUS_TRANSFER_COMPLETE = "regStatusTransferComplete";
    private Boolean regStatusTransferComplete;

    public UeRegStatusUpdateRspData()
    {
    }

    public UeRegStatusUpdateRspData regStatusTransferComplete(Boolean regStatusTransferComplete)
    {

        this.regStatusTransferComplete = regStatusTransferComplete;
        return this;
    }

    /**
     * Get regStatusTransferComplete
     * 
     * @return regStatusTransferComplete
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_REG_STATUS_TRANSFER_COMPLETE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Boolean getRegStatusTransferComplete()
    {
        return regStatusTransferComplete;
    }

    @JsonProperty(JSON_PROPERTY_REG_STATUS_TRANSFER_COMPLETE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setRegStatusTransferComplete(Boolean regStatusTransferComplete)
    {
        this.regStatusTransferComplete = regStatusTransferComplete;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        UeRegStatusUpdateRspData ueRegStatusUpdateRspData = (UeRegStatusUpdateRspData) o;
        return Objects.equals(this.regStatusTransferComplete, ueRegStatusUpdateRspData.regStatusTransferComplete);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(regStatusTransferComplete);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class UeRegStatusUpdateRspData {\n");
        sb.append("    regStatusTransferComplete: ").append(toIndentedString(regStatusTransferComplete)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
