{{- if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.service.worker.name }}
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ .Values.service.worker.name }}
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.service.worker.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ .Values.service.worker.name }}
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.service.worker.name }}-cm-key
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.service.worker.name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.worker.name }}-cm-key
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ .Values.service.worker.name }}
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
