{{- $key := index .Values "certificates" "traf" "key" }}
{{- $certificate := index .Values "certificates" "traf" "certificate" }}
apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata: 
  name: {{ template "eric-bsf.name" . }}-traf-certs-consumer-cr
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
spec: 
  generated-secret-name: {{ index .Values "certificates" "traf" "secret" | quote }}
  generated-secret-type: tls
  asymmetric-key-certificate-name:  {{ printf "%s/%s" $key $certificate | quote }}
