# Copyright 2019 Ericsson GmbH
{{- if eq (include "eric-bsf.tls" .) "true" }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-bsf.name" . }}-worker-oam-server
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-bsf.name" . }}-worker-oam-server-certificate
  certificate:
    subject:
      cn: {{ .Values.service.worker.name | quote }}
    subjectAlternativeName:
      dns:
        - certified-scrape-target
    extendedKeyUsage:
      tlsClientAuth: false
      tlsServerAuth: true
{{- end }}