# Copyright 2019 Ericsson GmbH
{{- if eq (include "eric-bsf.tls" .) "true" }}
{{- if or (eq (include "eric-bsf.manager.dcedsc.tls" .) "true")  (eq (include "eric-bsf.worker.dcedsc.tls" .) "true") }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: eric-bsf-dced-client-cert
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ .Values.service.manager.name | quote }}
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: eric-bsf-dced-client-cert
  certificate:
    subject:
      cn: root
    issuer:
      reference: eric-data-distributed-coordinator-ed-sc-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }} 
{{- end }}
