{{- if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.service.manager.name }}-{{ .Release.Namespace }}
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ .Values.service.manager.name }}
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.service.manager.name }}-cm-key
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.service.manager.name }}-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
