{{- if .Values.rbac.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.manager.name }}-cm-key
  labels:
{{- include "eric-bsf.labels" . | indent 4 }}
    app: {{ .Values.service.manager.name }} 
  annotations:
{{- include "eric-bsf.helm-annotations" . | indent 4 }}
{{- include "eric-bsf.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}