# Copyright 2019 Evo Team
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "eric-chfsim-6.name" .}}
  labels:
    a: {{ .Values.service.name }}
spec:
  {{- include "eric-chfsim.ipfamilies" . | indent 2 }}
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: rest-api
  - name: https
    protocol: TCP
    port: 443
    targetPort: rest-api-tls
  selector:
    app: {{ template "eric-chfsim-6.name" .}}
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "eric-chfsim-6.name" .}}
  labels:
    app: {{ template "eric-chfsim-6.name" .}}
    role: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ template "eric-chfsim-6.name" .}}
  template:
    metadata:
      labels:
        app: {{ template "eric-chfsim-6.name" .}}
        a: {{ .Values.service.name }}
        eric-sc-monitor-access: "true"
        eric-pm-server-access: "true"
    spec:
      {{- if include "eric-chfsim.pullSecrets" . }}
      imagePullSecrets:
      - name: {{ template "eric-chfsim.pullSecrets" . }}
      {{- end }}
      containers:
      - name: {{ .Values.service.name }}
        image: {{ template "eric-chfsim.registryUrl" . }}/{{ .Values.imageCredentials.repoPath }}/{{ .Values.spec.image }}:{{ .Values.spec.tag }}
        imagePullPolicy: {{ .Values.imageCredentials.pullPolicy | quote }}
        ports:
        - name: rest-api
          protocol: TCP
          containerPort: 80
        - name: rest-api-tls
          containerPort: 443
        {{   if  (eq .Values.certificates.enabled true) }}
        volumeMounts:
        - name: secrets
          mountPath: /root/certificates
          readOnly: true
          {{ end }}
        env:
        - name: JVM_PARAMS
          value: {{ .Values.jvm.parameters.chfsim | quote }}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        {{   if  (eq .Values.certificates.enabled true) }}
        - name: CHF_CERTIFICATES_PATH
          value: /root/certificates
        {{ end }}
        - name: START_IDS
          value: "10000000"
        - name: NUM_IDS
          value: "10000000"
        - name: CHF_DATA_REF_PREFIX
          value: "occ6-"
        - name: CHF_ROLE
          value: "frontend"
        - name: SERVICE_NAME
          value: {{ template "eric-chfsim-6.name" .}}
        - name: POD_IPS
          valueFrom:
           fieldRef:
             fieldPath: status.podIPs
        {{ if .Values.spec.resources.requests.cpu }}
        resources:
          requests:
            cpu: {{ .Values.spec.resources.requests.cpu | quote }}
            memory: {{ .Values.spec.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.spec.resources.limits.cpu | quote }}
            memory: {{ .Values.spec.resources.limits.memory | quote }}
        {{ end }}
      {{ if .Values.usage }}
      nodeSelector:
        usage: {{ .Values.usage }}
      tolerations:
      - key: usage
        operator: Equal
        value: {{ .Values.usage }}
        effect: "NoSchedule"
      {{ end }}
      {{   if  (eq .Values.certificates.enabled true) }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ template "eric-chfsim.secretName" .}}
            items:
              - key: {{ .Values.certificates.certificate }}
                path: certificate.pem
              - key: {{ .Values.certificates.key }}
                path: key.pem
              - key: {{ .Values.certificates.ca }}
                path: ca.pem
      {{  end }}
