/*
 * NRF NFManagement Service
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29510.nnrf.nfmanagement;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29503.nudm.uecm.NetworkNodeDiameterAddress;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Information of an HSS NF Instance
 */
@ApiModel(description = "Information of an HSS NF Instance")
@JsonPropertyOrder({ HssInfo.JSON_PROPERTY_GROUP_ID,
                     HssInfo.JSON_PROPERTY_IMSI_RANGES,
                     HssInfo.JSON_PROPERTY_IMS_PRIVATE_IDENTITY_RANGES,
                     HssInfo.JSON_PROPERTY_IMS_PUBLIC_IDENTITY_RANGES,
                     HssInfo.JSON_PROPERTY_MSISDN_RANGES,
                     HssInfo.JSON_PROPERTY_EXTERNAL_GROUP_IDENTIFIERS_RANGES,
                     HssInfo.JSON_PROPERTY_HSS_DIAMETER_ADDRESS })
public class HssInfo
{
    public static final String JSON_PROPERTY_GROUP_ID = "groupId";
    private String groupId;

    public static final String JSON_PROPERTY_IMSI_RANGES = "imsiRanges";
    private List<ImsiRange> imsiRanges = null;

    public static final String JSON_PROPERTY_IMS_PRIVATE_IDENTITY_RANGES = "imsPrivateIdentityRanges";
    private List<IdentityRange> imsPrivateIdentityRanges = null;

    public static final String JSON_PROPERTY_IMS_PUBLIC_IDENTITY_RANGES = "imsPublicIdentityRanges";
    private List<IdentityRange> imsPublicIdentityRanges = null;

    public static final String JSON_PROPERTY_MSISDN_RANGES = "msisdnRanges";
    private List<IdentityRange> msisdnRanges = null;

    public static final String JSON_PROPERTY_EXTERNAL_GROUP_IDENTIFIERS_RANGES = "externalGroupIdentifiersRanges";
    private List<IdentityRange> externalGroupIdentifiersRanges = null;

    public static final String JSON_PROPERTY_HSS_DIAMETER_ADDRESS = "hssDiameterAddress";
    private NetworkNodeDiameterAddress hssDiameterAddress;

    public HssInfo()
    {
    }

    public HssInfo groupId(String groupId)
    {

        this.groupId = groupId;
        return this;
    }

    /**
     * Identifier of a group of NFs.
     * 
     * @return groupId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Identifier of a group of NFs.")
    @JsonProperty(JSON_PROPERTY_GROUP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getGroupId()
    {
        return groupId;
    }

    @JsonProperty(JSON_PROPERTY_GROUP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGroupId(String groupId)
    {
        this.groupId = groupId;
    }

    public HssInfo imsiRanges(List<ImsiRange> imsiRanges)
    {

        this.imsiRanges = imsiRanges;
        return this;
    }

    public HssInfo addImsiRangesItem(ImsiRange imsiRangesItem)
    {
        if (this.imsiRanges == null)
        {
            this.imsiRanges = new ArrayList<>();
        }
        this.imsiRanges.add(imsiRangesItem);
        return this;
    }

    /**
     * Get imsiRanges
     * 
     * @return imsiRanges
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_IMSI_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ImsiRange> getImsiRanges()
    {
        return imsiRanges;
    }

    @JsonProperty(JSON_PROPERTY_IMSI_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setImsiRanges(List<ImsiRange> imsiRanges)
    {
        this.imsiRanges = imsiRanges;
    }

    public HssInfo imsPrivateIdentityRanges(List<IdentityRange> imsPrivateIdentityRanges)
    {

        this.imsPrivateIdentityRanges = imsPrivateIdentityRanges;
        return this;
    }

    public HssInfo addImsPrivateIdentityRangesItem(IdentityRange imsPrivateIdentityRangesItem)
    {
        if (this.imsPrivateIdentityRanges == null)
        {
            this.imsPrivateIdentityRanges = new ArrayList<>();
        }
        this.imsPrivateIdentityRanges.add(imsPrivateIdentityRangesItem);
        return this;
    }

    /**
     * Get imsPrivateIdentityRanges
     * 
     * @return imsPrivateIdentityRanges
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_IMS_PRIVATE_IDENTITY_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<IdentityRange> getImsPrivateIdentityRanges()
    {
        return imsPrivateIdentityRanges;
    }

    @JsonProperty(JSON_PROPERTY_IMS_PRIVATE_IDENTITY_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setImsPrivateIdentityRanges(List<IdentityRange> imsPrivateIdentityRanges)
    {
        this.imsPrivateIdentityRanges = imsPrivateIdentityRanges;
    }

    public HssInfo imsPublicIdentityRanges(List<IdentityRange> imsPublicIdentityRanges)
    {

        this.imsPublicIdentityRanges = imsPublicIdentityRanges;
        return this;
    }

    public HssInfo addImsPublicIdentityRangesItem(IdentityRange imsPublicIdentityRangesItem)
    {
        if (this.imsPublicIdentityRanges == null)
        {
            this.imsPublicIdentityRanges = new ArrayList<>();
        }
        this.imsPublicIdentityRanges.add(imsPublicIdentityRangesItem);
        return this;
    }

    /**
     * Get imsPublicIdentityRanges
     * 
     * @return imsPublicIdentityRanges
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_IMS_PUBLIC_IDENTITY_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<IdentityRange> getImsPublicIdentityRanges()
    {
        return imsPublicIdentityRanges;
    }

    @JsonProperty(JSON_PROPERTY_IMS_PUBLIC_IDENTITY_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setImsPublicIdentityRanges(List<IdentityRange> imsPublicIdentityRanges)
    {
        this.imsPublicIdentityRanges = imsPublicIdentityRanges;
    }

    public HssInfo msisdnRanges(List<IdentityRange> msisdnRanges)
    {

        this.msisdnRanges = msisdnRanges;
        return this;
    }

    public HssInfo addMsisdnRangesItem(IdentityRange msisdnRangesItem)
    {
        if (this.msisdnRanges == null)
        {
            this.msisdnRanges = new ArrayList<>();
        }
        this.msisdnRanges.add(msisdnRangesItem);
        return this;
    }

    /**
     * Get msisdnRanges
     * 
     * @return msisdnRanges
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_MSISDN_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<IdentityRange> getMsisdnRanges()
    {
        return msisdnRanges;
    }

    @JsonProperty(JSON_PROPERTY_MSISDN_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMsisdnRanges(List<IdentityRange> msisdnRanges)
    {
        this.msisdnRanges = msisdnRanges;
    }

    public HssInfo externalGroupIdentifiersRanges(List<IdentityRange> externalGroupIdentifiersRanges)
    {

        this.externalGroupIdentifiersRanges = externalGroupIdentifiersRanges;
        return this;
    }

    public HssInfo addExternalGroupIdentifiersRangesItem(IdentityRange externalGroupIdentifiersRangesItem)
    {
        if (this.externalGroupIdentifiersRanges == null)
        {
            this.externalGroupIdentifiersRanges = new ArrayList<>();
        }
        this.externalGroupIdentifiersRanges.add(externalGroupIdentifiersRangesItem);
        return this;
    }

    /**
     * Get externalGroupIdentifiersRanges
     * 
     * @return externalGroupIdentifiersRanges
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_EXTERNAL_GROUP_IDENTIFIERS_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<IdentityRange> getExternalGroupIdentifiersRanges()
    {
        return externalGroupIdentifiersRanges;
    }

    @JsonProperty(JSON_PROPERTY_EXTERNAL_GROUP_IDENTIFIERS_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExternalGroupIdentifiersRanges(List<IdentityRange> externalGroupIdentifiersRanges)
    {
        this.externalGroupIdentifiersRanges = externalGroupIdentifiersRanges;
    }

    public HssInfo hssDiameterAddress(NetworkNodeDiameterAddress hssDiameterAddress)
    {

        this.hssDiameterAddress = hssDiameterAddress;
        return this;
    }

    /**
     * Get hssDiameterAddress
     * 
     * @return hssDiameterAddress
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_HSS_DIAMETER_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public NetworkNodeDiameterAddress getHssDiameterAddress()
    {
        return hssDiameterAddress;
    }

    @JsonProperty(JSON_PROPERTY_HSS_DIAMETER_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHssDiameterAddress(NetworkNodeDiameterAddress hssDiameterAddress)
    {
        this.hssDiameterAddress = hssDiameterAddress;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        HssInfo hssInfo = (HssInfo) o;
        return Objects.equals(this.groupId, hssInfo.groupId) && Objects.equals(this.imsiRanges, hssInfo.imsiRanges)
               && Objects.equals(this.imsPrivateIdentityRanges, hssInfo.imsPrivateIdentityRanges)
               && Objects.equals(this.imsPublicIdentityRanges, hssInfo.imsPublicIdentityRanges) && Objects.equals(this.msisdnRanges, hssInfo.msisdnRanges)
               && Objects.equals(this.externalGroupIdentifiersRanges, hssInfo.externalGroupIdentifiersRanges)
               && Objects.equals(this.hssDiameterAddress, hssInfo.hssDiameterAddress);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(groupId,
                            imsiRanges,
                            imsPrivateIdentityRanges,
                            imsPublicIdentityRanges,
                            msisdnRanges,
                            externalGroupIdentifiersRanges,
                            hssDiameterAddress);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class HssInfo {\n");
        sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
        sb.append("    imsiRanges: ").append(toIndentedString(imsiRanges)).append("\n");
        sb.append("    imsPrivateIdentityRanges: ").append(toIndentedString(imsPrivateIdentityRanges)).append("\n");
        sb.append("    imsPublicIdentityRanges: ").append(toIndentedString(imsPublicIdentityRanges)).append("\n");
        sb.append("    msisdnRanges: ").append(toIndentedString(msisdnRanges)).append("\n");
        sb.append("    externalGroupIdentifiersRanges: ").append(toIndentedString(externalGroupIdentifiersRanges)).append("\n");
        sb.append("    hssDiameterAddress: ").append(toIndentedString(hssDiameterAddress)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
