/*
 * NRF NFManagement Service
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29510.nnrf.nfmanagement;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29510.nnrf.nfmanagement.IdentityRange;
import com.ericsson.cnal.openapi.r17.ts29510.nnrf.nfmanagement.SharedDataIdRange;
import com.ericsson.cnal.openapi.r17.ts29510.nnrf.nfmanagement.SupiRange;
import com.ericsson.cnal.openapi.r17.ts29510.nnrf.nfmanagement.UdrInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NrfInfoServedUdrInfoValue
 */
@JsonPropertyOrder({ NrfInfoServedUdrInfoValue.JSON_PROPERTY_GROUP_ID,
                     NrfInfoServedUdrInfoValue.JSON_PROPERTY_SUPI_RANGES,
                     NrfInfoServedUdrInfoValue.JSON_PROPERTY_GPSI_RANGES,
                     NrfInfoServedUdrInfoValue.JSON_PROPERTY_EXTERNAL_GROUP_IDENTIFIERS_RANGES,
                     NrfInfoServedUdrInfoValue.JSON_PROPERTY_SUPPORTED_DATA_SETS,
                     NrfInfoServedUdrInfoValue.JSON_PROPERTY_SHARED_DATA_ID_RANGES })
@JsonTypeName("NrfInfo_servedUdrInfo_value")
public class NrfInfoServedUdrInfoValue
{
    public static final String JSON_PROPERTY_GROUP_ID = "groupId";
    private String groupId;

    public static final String JSON_PROPERTY_SUPI_RANGES = "supiRanges";
    private List<SupiRange> supiRanges = null;

    public static final String JSON_PROPERTY_GPSI_RANGES = "gpsiRanges";
    private List<IdentityRange> gpsiRanges = null;

    public static final String JSON_PROPERTY_EXTERNAL_GROUP_IDENTIFIERS_RANGES = "externalGroupIdentifiersRanges";
    private List<IdentityRange> externalGroupIdentifiersRanges = null;

    public static final String JSON_PROPERTY_SUPPORTED_DATA_SETS = "supportedDataSets";
    private List<String> supportedDataSets = null;

    public static final String JSON_PROPERTY_SHARED_DATA_ID_RANGES = "sharedDataIdRanges";
    private List<SharedDataIdRange> sharedDataIdRanges = null;

    public NrfInfoServedUdrInfoValue()
    {
    }

    public NrfInfoServedUdrInfoValue groupId(String groupId)
    {

        this.groupId = groupId;
        return this;
    }

    /**
     * Identifier of a group of NFs.
     * 
     * @return groupId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Identifier of a group of NFs.")
    @JsonProperty(JSON_PROPERTY_GROUP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getGroupId()
    {
        return groupId;
    }

    @JsonProperty(JSON_PROPERTY_GROUP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGroupId(String groupId)
    {
        this.groupId = groupId;
    }

    public NrfInfoServedUdrInfoValue supiRanges(List<SupiRange> supiRanges)
    {

        this.supiRanges = supiRanges;
        return this;
    }

    public NrfInfoServedUdrInfoValue addSupiRangesItem(SupiRange supiRangesItem)
    {
        if (this.supiRanges == null)
        {
            this.supiRanges = new ArrayList<>();
        }
        this.supiRanges.add(supiRangesItem);
        return this;
    }

    /**
     * Get supiRanges
     * 
     * @return supiRanges
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SUPI_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<SupiRange> getSupiRanges()
    {
        return supiRanges;
    }

    @JsonProperty(JSON_PROPERTY_SUPI_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSupiRanges(List<SupiRange> supiRanges)
    {
        this.supiRanges = supiRanges;
    }

    public NrfInfoServedUdrInfoValue gpsiRanges(List<IdentityRange> gpsiRanges)
    {

        this.gpsiRanges = gpsiRanges;
        return this;
    }

    public NrfInfoServedUdrInfoValue addGpsiRangesItem(IdentityRange gpsiRangesItem)
    {
        if (this.gpsiRanges == null)
        {
            this.gpsiRanges = new ArrayList<>();
        }
        this.gpsiRanges.add(gpsiRangesItem);
        return this;
    }

    /**
     * Get gpsiRanges
     * 
     * @return gpsiRanges
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_GPSI_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<IdentityRange> getGpsiRanges()
    {
        return gpsiRanges;
    }

    @JsonProperty(JSON_PROPERTY_GPSI_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGpsiRanges(List<IdentityRange> gpsiRanges)
    {
        this.gpsiRanges = gpsiRanges;
    }

    public NrfInfoServedUdrInfoValue externalGroupIdentifiersRanges(List<IdentityRange> externalGroupIdentifiersRanges)
    {

        this.externalGroupIdentifiersRanges = externalGroupIdentifiersRanges;
        return this;
    }

    public NrfInfoServedUdrInfoValue addExternalGroupIdentifiersRangesItem(IdentityRange externalGroupIdentifiersRangesItem)
    {
        if (this.externalGroupIdentifiersRanges == null)
        {
            this.externalGroupIdentifiersRanges = new ArrayList<>();
        }
        this.externalGroupIdentifiersRanges.add(externalGroupIdentifiersRangesItem);
        return this;
    }

    /**
     * Get externalGroupIdentifiersRanges
     * 
     * @return externalGroupIdentifiersRanges
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_EXTERNAL_GROUP_IDENTIFIERS_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<IdentityRange> getExternalGroupIdentifiersRanges()
    {
        return externalGroupIdentifiersRanges;
    }

    @JsonProperty(JSON_PROPERTY_EXTERNAL_GROUP_IDENTIFIERS_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExternalGroupIdentifiersRanges(List<IdentityRange> externalGroupIdentifiersRanges)
    {
        this.externalGroupIdentifiersRanges = externalGroupIdentifiersRanges;
    }

    public NrfInfoServedUdrInfoValue supportedDataSets(List<String> supportedDataSets)
    {

        this.supportedDataSets = supportedDataSets;
        return this;
    }

    public NrfInfoServedUdrInfoValue addSupportedDataSetsItem(String supportedDataSetsItem)
    {
        if (this.supportedDataSets == null)
        {
            this.supportedDataSets = new ArrayList<>();
        }
        this.supportedDataSets.add(supportedDataSetsItem);
        return this;
    }

    /**
     * Get supportedDataSets
     * 
     * @return supportedDataSets
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SUPPORTED_DATA_SETS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getSupportedDataSets()
    {
        return supportedDataSets;
    }

    @JsonProperty(JSON_PROPERTY_SUPPORTED_DATA_SETS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSupportedDataSets(List<String> supportedDataSets)
    {
        this.supportedDataSets = supportedDataSets;
    }

    public NrfInfoServedUdrInfoValue sharedDataIdRanges(List<SharedDataIdRange> sharedDataIdRanges)
    {

        this.sharedDataIdRanges = sharedDataIdRanges;
        return this;
    }

    public NrfInfoServedUdrInfoValue addSharedDataIdRangesItem(SharedDataIdRange sharedDataIdRangesItem)
    {
        if (this.sharedDataIdRanges == null)
        {
            this.sharedDataIdRanges = new ArrayList<>();
        }
        this.sharedDataIdRanges.add(sharedDataIdRangesItem);
        return this;
    }

    /**
     * Get sharedDataIdRanges
     * 
     * @return sharedDataIdRanges
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SHARED_DATA_ID_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<SharedDataIdRange> getSharedDataIdRanges()
    {
        return sharedDataIdRanges;
    }

    @JsonProperty(JSON_PROPERTY_SHARED_DATA_ID_RANGES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSharedDataIdRanges(List<SharedDataIdRange> sharedDataIdRanges)
    {
        this.sharedDataIdRanges = sharedDataIdRanges;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        NrfInfoServedUdrInfoValue nrfInfoServedUdrInfoValue = (NrfInfoServedUdrInfoValue) o;
        return Objects.equals(this.groupId, nrfInfoServedUdrInfoValue.groupId) && Objects.equals(this.supiRanges, nrfInfoServedUdrInfoValue.supiRanges)
               && Objects.equals(this.gpsiRanges, nrfInfoServedUdrInfoValue.gpsiRanges)
               && Objects.equals(this.externalGroupIdentifiersRanges, nrfInfoServedUdrInfoValue.externalGroupIdentifiersRanges)
               && Objects.equals(this.supportedDataSets, nrfInfoServedUdrInfoValue.supportedDataSets)
               && Objects.equals(this.sharedDataIdRanges, nrfInfoServedUdrInfoValue.sharedDataIdRanges);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(groupId, supiRanges, gpsiRanges, externalGroupIdentifiersRanges, supportedDataSets, sharedDataIdRanges);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class NrfInfoServedUdrInfoValue {\n");
        sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
        sb.append("    supiRanges: ").append(toIndentedString(supiRanges)).append("\n");
        sb.append("    gpsiRanges: ").append(toIndentedString(gpsiRanges)).append("\n");
        sb.append("    externalGroupIdentifiersRanges: ").append(toIndentedString(externalGroupIdentifiersRanges)).append("\n");
        sb.append("    supportedDataSets: ").append(toIndentedString(supportedDataSets)).append("\n");
        sb.append("    sharedDataIdRanges: ").append(toIndentedString(sharedDataIdRanges)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
