#This Dockerfile creates the SLES-based base-image for the compiled envoy-binary
ARG DOCKER_BASE_IMG
FROM $DOCKER_BASE_IMG

ARG BINARY
COPY $BINARY /usr/local/bin/envoy
COPY $BINARY.version /usr/local/bin/VERSION_INFO
COPY stdout-redirect /
RUN chmod 555 /usr/local/bin/envoy &&\
    chmod 555 /usr/local/bin/VERSION_INFO &&\
    chmod 555 /stdout-redirect

