apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-env
data:
  LDAP_ORGANISATION: "Ericsson internal tool"
  LDAP_DOMAIN: {{ .Values.domainName }}
  LDAP_BASE_DN: {{ .Values.baseDN }}
  LDAP_BACKEND: "mdb"
  LDAP_TLS: "true"
  LDAP_TLS_ENFORCE: "false"
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
  LDAP_TLS_VERIFY_CLIENT: "try"
  {{ if .Values.tls.enabled }}
  LDAP_TLS_CRT_FILENAME: "certificate.pem"
  LDAP_TLS_KEY_FILENAME: "key.pem"
  LDAP_TLS_CA_CRT_FILENAME: "ca-certs-SC.pem"
  {{ end }}
