apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-creds
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote}}
  LDAP_CONFIG_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
