/*
 * LMF Location
 * LMF Location Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29572.nlmf.location;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Indicates the usage of a positioning method.
 */
@ApiModel(description = "Indicates the usage of a positioning method.")
@JsonPropertyOrder({ PositioningMethodAndUsage.JSON_PROPERTY_METHOD,
                     PositioningMethodAndUsage.JSON_PROPERTY_MODE,
                     PositioningMethodAndUsage.JSON_PROPERTY_USAGE,
                     PositioningMethodAndUsage.JSON_PROPERTY_METHOD_CODE })
public class PositioningMethodAndUsage
{
    public static final String JSON_PROPERTY_METHOD = "method";
    private String method;

    public static final String JSON_PROPERTY_MODE = "mode";
    private String mode;

    public static final String JSON_PROPERTY_USAGE = "usage";
    private String usage;

    public static final String JSON_PROPERTY_METHOD_CODE = "methodCode";
    private Integer methodCode;

    public PositioningMethodAndUsage()
    {
    }

    public PositioningMethodAndUsage method(String method)
    {

        this.method = method;
        return this;
    }

    /**
     * Indicates supported positioning methods.
     * 
     * @return method
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "Indicates supported positioning methods.")
    @JsonProperty(JSON_PROPERTY_METHOD)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getMethod()
    {
        return method;
    }

    @JsonProperty(JSON_PROPERTY_METHOD)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setMethod(String method)
    {
        this.method = method;
    }

    public PositioningMethodAndUsage mode(String mode)
    {

        this.mode = mode;
        return this;
    }

    /**
     * Indicates supported modes used for positioning method.
     * 
     * @return mode
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "Indicates supported modes used for positioning method.")
    @JsonProperty(JSON_PROPERTY_MODE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getMode()
    {
        return mode;
    }

    @JsonProperty(JSON_PROPERTY_MODE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setMode(String mode)
    {
        this.mode = mode;
    }

    public PositioningMethodAndUsage usage(String usage)
    {

        this.usage = usage;
        return this;
    }

    /**
     * Indicates usage made of the location measurement.
     * 
     * @return usage
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "Indicates usage made of the location measurement.")
    @JsonProperty(JSON_PROPERTY_USAGE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getUsage()
    {
        return usage;
    }

    @JsonProperty(JSON_PROPERTY_USAGE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUsage(String usage)
    {
        this.usage = usage;
    }

    public PositioningMethodAndUsage methodCode(Integer methodCode)
    {

        this.methodCode = methodCode;
        return this;
    }

    /**
     * Get methodCode minimum: 16 maximum: 31
     * 
     * @return methodCode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_METHOD_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getMethodCode()
    {
        return methodCode;
    }

    @JsonProperty(JSON_PROPERTY_METHOD_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMethodCode(Integer methodCode)
    {
        this.methodCode = methodCode;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        PositioningMethodAndUsage positioningMethodAndUsage = (PositioningMethodAndUsage) o;
        return Objects.equals(this.method, positioningMethodAndUsage.method) && Objects.equals(this.mode, positioningMethodAndUsage.mode)
               && Objects.equals(this.usage, positioningMethodAndUsage.usage) && Objects.equals(this.methodCode, positioningMethodAndUsage.methodCode);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(method, mode, usage, methodCode);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class PositioningMethodAndUsage {\n");
        sb.append("    method: ").append(toIndentedString(method)).append("\n");
        sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
        sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
        sb.append("    methodCode: ").append(toIndentedString(methodCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
