{
 "title": "BSF [Prometheus]",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cassandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage usage of WCDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "job:file_system_storage_usage" }
   ]
  },
  {
   "title": "Max WCDB storage utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "job:max_database_storage_utilization"
    }
   ]
  },
  {
   "title": "Pool open connections for CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "job:bsf_worker_pool_open_connections"
    },
    {
     "expr": "job:bsf_diameter_pool_open_connections"
    }
   ]
  },
  {
   "title": "Max throttling queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "job:throttling_queue_max" },
    {
     "expr": "job:bsf_worker_throttling_queue_max"
    },
    {
     "expr": "job:bsf_diameter_throttling_queue_max"
    }
   ]
  },
  {
   "title": "Pool in flight for CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "job:bsf_worker_pool_in_flight" },
    {
     "expr": "job:bsf_diameter_pool_in_flight"
    }
   ]
  },
  {
   "title": "Number of total throttling errors in CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "job:bsf_worker_throttling_errors"
    },
    {
     "expr": "job:bsf_diameter_throttling_errors"
    }
   ]
  },
  {
   "title": "Number of total timeout errors in CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "job:bsf_worker_timeout_errors" },
    {
     "expr": "job:bsf_diameter_timeout_errors"
    }
   ]
  },
  {
   "title": "Mean throttling delay of CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "job:bsf_worker_throttling_delay_mean_latency"
    },
    {
     "expr": "job:bsf_diameter_throttling_delay_mean_latency"
    }
   ]
  },
  {
   "title": "Number of total other errors in CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "job:bsf_diameter_requests_other_error"
    }
   ]
  },
  {
   "title": "Number of total unsent CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "job:bsf_worker_requests_unsent" },
    {
     "expr": "job:bsf_diameter_requests_unsent"
    }
   ]
  },
  {
   "title": "Number of total unavailable CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "job:bsf_worker_requests_unavailable"
    },
    {
     "expr": "job:bsf_diameter_requests_unavailable"
    }
   ]
  },
  {
   "title": "Number of total aborted CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "job:bsf_worker_requests_aborted"
    },
    {
     "expr": "job:bsf_diameter_requests_aborted"
    }
   ]
  },
  {
   "title": "Number of total write timeout errors of CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "job:bsf_worker_write_timeout_errors"
    },
    {
     "expr": "job:bsf_diameter_write_timeout_errors"
    }
   ]
  },
  {
   "title": "Number of total connection init errors of CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "job:bsf_worker_connection_init_errors"
    },
    {
     "expr": "job:bsf_diameter_connection_init_errors"
    }
   ]
  },
  {
   "title": "Number of total read timeout errors of CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "job:bsf_worker_read_timeout_errors"
    },
    {
     "expr": "job:bsf_diameter_read_timeout_errors"
    }
   ]
  },
  {
   "title": "Number of total throttling errors of CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "job:bsf_worker_total_request_throttling_per_instance"
    },
    {
     "expr": "job:bsf_diameter_total_request_throttling_per_instance"
    }
   ]
  },
  {
   "title": "Number of total connection auth errors of CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "job:bsf_worker_connection_auth_errors"
    },
    {
     "expr": "job:bsf_diameter_connection_auth_errors"
    }
   ]
  },
  {
   "title": "Number of mean latency of CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "job:bsf_worker_mean_latency_per_instance"
    },
    {
     "expr": "job:bsf_diameter_mean_latency_per_instance"
    }
   ]
  },
  {
   "title": "Number of total timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "job:bsf_worker_total_request_timeouts_per_instance"
    },
    {
     "expr": "job:bsf_diameter_total_request_timeouts_per_instance"
    }
   ]
  },
  {
   "title": "Number of total CQL requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    { "expr": "job:bsf_worker_cql_rate" },
    { "expr": "job:bsf_diameter_cql_rate" }
   ]
  },
  {
   "title": "Storage_utilization [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "job:cassandra_storage_utilization_total"
    }
   ]
  },
  {
   "title": "Unsuccessful transactions per cassandra total messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "job:cassandra_unsuccessful_transactions_per_cassandra_total_messages:ratio_rate45s_100"
    }
   ]
  },
  {
   "title": "Total number of all cql requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "job:cassandra_driver_cql_requests_counter_sum:rate45s"
    }
   ]
  },
  {
   "title": "Total number of all cql messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "job:cassandra_driver_cql_messages_counter_sum:rate45s"
    }
   ]
  },
  {
   "title": "Number of cql request for each cassandra client-server combination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "job:cassandra_driver_cql_requests_counter:rate45s"
    }
   ]
  },
  {
   "title": "Number of unsuccessful transactions per cassandra client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "job:cassandra_unsuccessful_transactions:rate45s"
    }
   ]
  },
  {
   "title": "Number of cql messages for each cassandra client-server combination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "job:cassandra_driver_cql_messages_counter:rate45s"
    }
   ]
  },
  {
   "title": "Number of throttling errors per cassandra client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "expr": "job:cassandra_driver_throttling_errors_counter:rate45s"
    }
   ]
  },
  {
   "title": "Total number of unsuccessful transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "job:cassandra_unsuccessful_transactions_sum:rate45s"
    }
   ]
  },
  {
   "title": "Number of connection auth errors for each cassandra client-server combination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "job:cassandra_driver_nodes_errors_connection_auth_counter:rate45s"
    }
   ]
  },
  {
   "title": "Total sum of all connection init/auth attempts per cassandra instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "job:cassandra_driver_nodes_errors_connection_counter_sum:rate45s"
    }
   ]
  },
  {
   "title": "Number of request aborted errors for each cassandra client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "job:cassandra_driver_nodes_errors_request_aborted_counter:rate45s"
    }
   ]
  },
  {
   "title": "Number of connection init errors for each cassandra client-server combination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "job:cassandra_driver_nodes_errors_connection_init_counter:rate45s"
    }
   ]
  },
  {
   "title": "Number of request read timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "targets": [
    {
     "expr": "job:cassandra_driver_nodes_errors_request_read_timeouts_counter:rate45s"
    }
   ]
  },
  {
   "title": "Number of request send unsent errors for each cassandra client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "job:cassandra_driver_nodes_errors_request_unsent_counter:rate45s"
    }
   ]
  },
  {
   "title": "Number of request unavailable errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "targets": [
    {
     "expr": "job:cassandra_driver_nodes_errors_request_unavailables_counter:rate45s"
    }
   ]
  },
  {
   "title": "Number of request other errors for each cassandra client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "job:cassandra_driver_nodes_errors_request_others_counter:rate45s"
    }
   ]
  },
  {
   "title": "Number of request write timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "job:cassandra_driver_nodes_errors_request_write_timeouts_counter:rate45s"
    }
   ]
  },
  {
   "title": "Number of cql client timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "targets": [
    {
     "expr": "job:cassandra_driver_cql_client_timeouts_counter:rate45s"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Memory Usage [Mb]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "job:bsf_manager_avg_memory_mb" },
      { "expr": "job:bsf_worker_avg_memory_mb" },
      { "expr": "job:bsf_diameter_avg_memory_mb" },
      { "expr": "job:stm_diameter_avg_memory_mb" },
      {
       "expr": "job:bsf_diameter_grpc_avg_memory_mb"
      },
      { "expr": "job:wcdb_avg_memory_mb" }
     ]
    },
    {
     "title": "Average CPU Usage [%]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "job:avg_bsf_load_percentage" },
      {
       "expr": "job:avg_bsf_worker_load_percentage"
      },
      {
       "expr": "job:avg_bsf_cassandra_load_percentage"
      },
      {
       "expr": "job:avg_bsf_dsl_load_percentage"
      },
      {
       "expr": "job:avg_bsf_fe_diameter_load_percentage"
      },
      {
       "expr": "job:avg_bsf_diameter_load_percentage"
      },
      {
       "expr": "job:avg_bsf_diameter_grpc_load_percentage"
      }
     ]
    },
    {
     "title": "Average CPU Usage [millicores]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "job:bsf_manager_avg_cpu_load_millicores"
      },
      {
       "expr": "job:bsf_worker_avg_cpu_load_millicores"
      },
      {
       "expr": "job:bsf_diameter_avg_cpu_load_millicores"
      },
      {
       "expr": "job:stm_diameter_avg_cpu_load_millicores"
      },
      {
       "expr": "job:bsf_diameter_grpc_avg_cpu_load_millicores"
      },
      {
       "expr": "job:wcdb_avg_cpu_load_millicores"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Traffic [TPS]",
     "type": "timeseries",
     "description": "Number of transactions per second (TPS) for HTTP/Diameter traffic",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      { "expr": "job:bsf_http_tps" },
      { "expr": "job:bsf_diameter_tps" }
     ]
    },
    {
     "title": "Success Rate [%]",
     "type": "timeseries",
     "description": "Number of transactions per second (TPS) for HTTP/Diameter traffic",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      { "expr": "job:bsf_http_success_rate" },
      { "expr": "job:bsf_diameter_success_rate" }
     ]
    }
   ]
  },
  {
   "title": "Vertx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vertx HTTP server response [sec]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "bsf_http_server_response_time_seconds"
      },
      {
       "expr": "bsf_http_server_response_time_seconds_max"
      }
     ]
    },
    {
     "title": "Vertx HTTP server active connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "bsf_http_server_active_connections"
      }
     ]
    }
   ]
  }
 ]
}