{
 "title": "RLF-Redis [InfluxDB2]",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RLF Cpu",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"rlf_cpu\"\n  )"
    }
   ]
  },
  {
   "title": "Redis Cpu",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sc_redis_cpu\"\n  )"
    }
   ]
  },
  {
   "title": "RLF Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"rlf_memory\"\n  )"
    }
   ]
  },
  {
   "title": "Redis Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sc_redis_memory\"\n  )"
    }
   ]
  }
 ]
}