{
 "title": "RLF-Redis [Prometheus]",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Redis Memory Usage [Mb]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rlf_redis_memory_usage" }
   ]
  },
  {
   "title": "Redis Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rlf_redis_memory_usage_percent" }
   ]
  },
  {
   "title": "Redis CPU Load [Millicores]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rlf_redis_cpu_load" }
   ]
  },
  {
   "title": "Redis CPU Load [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rlf_redis_cpu_load_percent" }
   ]
  },
  {
   "title": "Memory Usage [Mb]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rlf_memory_usage" }
   ]
  },
  {
   "title": "Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "rlf_memory_usage_percent" }
   ]
  },
  {
   "title": "CPU Load [Millicores]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rlf_cpu_load" }
   ]
  },
  {
   "title": "CPU Load [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "rlf_cpu_load_percent" }
   ]
  }
 ]
}