{
 "title": "SC Memory Metrics [Prometheus]",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "POD Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "job:pod_memory_usage_100" }
   ]
  },
  {
   "title": "Container MAX Memory Usage per POD [%]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "job:pod_container_memory_usage_100{aggregation=\"max\"}"
    }
   ]
  },
  {
   "title": "Container AVG Memory Usage per POD [%]",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "job:pod_container_memory_usage_100{aggregation=\"avg\"}"
    }
   ]
  },
  {
   "title": "Container MIN Memory Usage per POD [%]",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "job:pod_container_memory_usage_100{aggregation=\"min\"}"
    }
   ]
  },
  {
   "title": "Container Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 63 },
   "targets": [
    { "expr": "job:container_memory_usage_100" }
   ]
  }
 ]
}