{
 "title": "SC Memory Metrics [InfluxDB2]",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "POD Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "  from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r[\"_field\"] == \"job:pod_memory_usage_100\")"
    }
   ]
  },
  {
   "title": "Container MAX Memory Usage per POD [%]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r[\"_field\"] == \"job:pod_container_memory_usage_100\")\n  |> filter(fn: (r) => r[\"aggregation\"] == \"max\")"
    }
   ]
  },
  {
   "title": "Container AVG Memory Usage per POD [%]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r[\"_field\"] == \"job:pod_container_memory_usage_100\")\n  |> filter(fn: (r) => r[\"aggregation\"] == \"avg\")"
    }
   ]
  },
  {
   "title": "Container MIN Memory Usage per POD [%]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r[\"_field\"] == \"job:pod_container_memory_usage_100\")\n  |> filter(fn: (r) => r[\"aggregation\"] == \"min\")"
    }
   ]
  },
  {
   "title": "Container Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "query": "  from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r[\"_field\"] == \"job:container_memory_usage_100\")"
    }
   ]
  }
 ]
}