{
 "title": "SCP [Prometheus]",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "scp_load_avg" }
   ]
  },
  {
   "title": "Worker Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "scp_worker_pods" }
   ]
  },
  {
   "title": "CPU Usage [Millicores]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "scp_manager_cpu" },
    { "expr": "scp_worker_cpu_avg" },
    { "expr": "scp_worker_cpu_max" },
    { "expr": "scp_worker_cpu_min" }
   ]
  },
  {
   "title": "Memory Usage [Mb]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "scp_manager_memory" },
    { "expr": "scp_worker_memory_avg" },
    { "expr": "scp_worker_memory_max" },
    { "expr": "scp_worker_memory_min" }
   ]
  },
  {
   "title": "Egress Pool [MPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "scp_egress_pool_mps" }
   ]
  },
  {
   "title": "Egress Pool c4/5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "scp_egress_pool_class4" },
    { "expr": "scp_egress_pool_class5" }
   ]
  },
  {
   "title": "Messages per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "scp_ingress_mps" },
    { "expr": "scp_egress_mps" },
    { "expr": "scp_nrf_discovery_mps" }
   ]
  },
  {
   "title": "Success Rate [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "scp_ingress_success" },
    { "expr": "scp_egress_success" },
    { "expr": "scp_nrf_discovery_success" }
   ]
  }
 ]
}