{
 "title": "SEPP [InfluxDB2]",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Manager Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_manager_memory\"\n  )"
    }
   ]
  },
  {
   "title": "Worker Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_worker_memory_avg\"\n  )"
    },
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_worker_memory_max\"\n  )"
    },
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_worker_memory_min\"\n  )"
    }
   ]
  },
  {
   "title": "Manager CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_manager_cpu\"\n  )"
    }
   ]
  },
  {
   "title": "Worker CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_worker_cpu_avg\"\n  )"
    },
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_worker_cpu_max\"\n  )"
    },
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_worker_cpu_min\"\n  )"
    }
   ]
  },
  {
   "title": "Ingress [MPS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_ingress_mps\"\n  )"
    }
   ]
  },
  {
   "title": "Ingress Success [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_ingress_success\"\n  )"
    }
   ]
  },
  {
   "title": "Egress [MPS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -30m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_egress_mps\"\n  )"
    }
   ]
  },
  {
   "title": "Egress Success [%]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r._field == \"sepp_egress_success\"\n  )"
    }
   ]
  },
  {
   "title": "NRF Discovery [MPS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r.field == \"sepp_nrf_discovery_mps\"\n  )"
    }
   ]
  },
  {
   "title": "NRF Discovery Success [%]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"prometheus_remote_write\" and\n    r.field == \"sepp_nrf_discovery_success\"\n  )"
    }
   ]
  }
 ]
}