{
 "title": "SLF [Prometheus]",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage [Millicores]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "slf_cpu" }
   ]
  },
  {
   "title": "Memory Usage [Mb]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "slf_memory" }
   ]
  },
  {
   "title": "SCP NRF Discovery [MPS]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "slf_scp_nrf_discovery_mps" }
   ]
  },
  {
   "title": "NRF Discovery Success Rate [%]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "slf_nrf_discovery_success" }
   ]
  }
 ]
}