{{- if  .Values.env.secure }}
{{- if  .Values.env.certCustomResources.enabled }}
apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata:
  name: {{ .Values.service.name }}-asymmetric-key-cert
  labels:
    app.kubernetes.io/name: {{ .Values.service.name  }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  generated-secret-name: {{ .Values.service.name }}-asymmetric-key-cert-secret
  generated-secret-type: tls
  asymmetric-key-certificate-name: {{ .Values.env.certCustomResources.key }}/{{ .Values.env.certCustomResources.cert }}
{{- end -}}
{{- end -}}