apiVersion: v2
appVersion: 1.1.0-4
dependencies:
- condition: eric-sepp.enabled
  name: eric-sepp
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-sc-all-internal-helm
  version: 1.13.0-h6fa1d31
- alias: eric-sc-sepp-license-consumer
  condition: eric-sc-sepp-license-consumer.enabled
  import-values:
  - child: licenseconsumer.config
    parent: global.licenseconsumer.config
  name: eric-sc-license-consumer
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-sc-license-consumer-released-helm/
  version: 1.1.0+9
- alias: eric-sc-sepp-log-shipper
  condition: eric-sc-sepp-log-shipper.enabled
  import-values:
  - child: logShipper.config
    parent: global.logShipper.config
  name: eric-log-shipper
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 19.1.0+16
description: sepp app. (c) Ericsson AB 2023.
name: eric-sc-sepp
type: application
version: 1.1.0-4
