/*
 * Nchf_ConvergedCharging
 * ConvergedCharging Service    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 3.1.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts32291.nchf.convergedcharging;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ISUPCause
 */
@JsonPropertyOrder({ ISUPCause.JSON_PROPERTY_I_S_U_P_CAUSE_LOCATION,
                     ISUPCause.JSON_PROPERTY_I_S_U_P_CAUSE_VALUE,
                     ISUPCause.JSON_PROPERTY_I_S_U_P_CAUSE_DIAGNOSTICS })
public class ISUPCause
{
    public static final String JSON_PROPERTY_I_S_U_P_CAUSE_LOCATION = "iSUPCauseLocation";
    private Integer iSUPCauseLocation;

    public static final String JSON_PROPERTY_I_S_U_P_CAUSE_VALUE = "iSUPCauseValue";
    private Integer iSUPCauseValue;

    public static final String JSON_PROPERTY_I_S_U_P_CAUSE_DIAGNOSTICS = "iSUPCauseDiagnostics";
    private String iSUPCauseDiagnostics;

    public ISUPCause()
    {
    }

    public ISUPCause iSUPCauseLocation(Integer iSUPCauseLocation)
    {

        this.iSUPCauseLocation = iSUPCauseLocation;
        return this;
    }

    /**
     * Integer where the allowed values correspond to the value range of an unsigned
     * 32-bit integer. minimum: 0 maximum: 4294967295
     * 
     * @return iSUPCauseLocation
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. ")
    @JsonProperty(JSON_PROPERTY_I_S_U_P_CAUSE_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getiSUPCauseLocation()
    {
        return iSUPCauseLocation;
    }

    @JsonProperty(JSON_PROPERTY_I_S_U_P_CAUSE_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setiSUPCauseLocation(Integer iSUPCauseLocation)
    {
        this.iSUPCauseLocation = iSUPCauseLocation;
    }

    public ISUPCause iSUPCauseValue(Integer iSUPCauseValue)
    {

        this.iSUPCauseValue = iSUPCauseValue;
        return this;
    }

    /**
     * Integer where the allowed values correspond to the value range of an unsigned
     * 32-bit integer. minimum: 0 maximum: 4294967295
     * 
     * @return iSUPCauseValue
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. ")
    @JsonProperty(JSON_PROPERTY_I_S_U_P_CAUSE_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getiSUPCauseValue()
    {
        return iSUPCauseValue;
    }

    @JsonProperty(JSON_PROPERTY_I_S_U_P_CAUSE_VALUE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setiSUPCauseValue(Integer iSUPCauseValue)
    {
        this.iSUPCauseValue = iSUPCauseValue;
    }

    public ISUPCause iSUPCauseDiagnostics(String iSUPCauseDiagnostics)
    {

        this.iSUPCauseDiagnostics = iSUPCauseDiagnostics;
        return this;
    }

    /**
     * Get iSUPCauseDiagnostics
     * 
     * @return iSUPCauseDiagnostics
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_I_S_U_P_CAUSE_DIAGNOSTICS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getiSUPCauseDiagnostics()
    {
        return iSUPCauseDiagnostics;
    }

    @JsonProperty(JSON_PROPERTY_I_S_U_P_CAUSE_DIAGNOSTICS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setiSUPCauseDiagnostics(String iSUPCauseDiagnostics)
    {
        this.iSUPCauseDiagnostics = iSUPCauseDiagnostics;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        ISUPCause isUPCause = (ISUPCause) o;
        return Objects.equals(this.iSUPCauseLocation, isUPCause.iSUPCauseLocation) && Objects.equals(this.iSUPCauseValue, isUPCause.iSUPCauseValue)
               && Objects.equals(this.iSUPCauseDiagnostics, isUPCause.iSUPCauseDiagnostics);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(iSUPCauseLocation, iSUPCauseValue, iSUPCauseDiagnostics);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class ISUPCause {\n");
        sb.append("    iSUPCauseLocation: ").append(toIndentedString(iSUPCauseLocation)).append("\n");
        sb.append("    iSUPCauseValue: ").append(toIndentedString(iSUPCauseValue)).append("\n");
        sb.append("    iSUPCauseDiagnostics: ").append(toIndentedString(iSUPCauseDiagnostics)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
