/*
 * Nchf_ConvergedCharging
 * 
 *
 * OpenAPI spec version: 3.1.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * 
 * This file has been auto-generated by the yaml2java script.
 */

package com.ericsson.cnal.openapi.r17.ts32291.nchf.convergedcharging;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ParticipantActionType
 */
public class ParticipantActionType
{
    public static final String CREATE = "CREATE";
    public static final String JOIN = "JOIN";
    public static final String INVITE_INTO = "INVITE_INTO";
    public static final String QUIT = "QUIT";

}
