{{- define "eric-dsc-load.de-facto-labels" }}
app.kubernetes.io/name: {{ .Chart.Name | quote }}
app.kubernetes.io/version: {{ template "eric-dsc-load.version" . }}
app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- end -}}
