apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.container.image.repo }}/{{ .Values.container.image.dbreference }}:{{ .Values.container.image.dbtag }}"
        ports:
        - containerPort: {{ .Values.dbservice.port }}
          name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ejbca-database-credentials
              key: password-root
        - name: MYSQL_DATABASE
          value: "ejbca"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: ejbca-database-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ejbca-database-credentials
              key: password
        volumeMounts:
        - name: config-mariadb-volume
          mountPath: /etc/mysql/config.d/
      volumes:
        - name: config-mariadb-volume
          configMap:
            name: config-mariadb-configmap
