apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ejbca-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "1800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "1800"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.path | quote }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: ejbca-backend-service
            port:
              number: {{ .Values.ejbcaservice.port }}
