apiVersion: v1
kind: Service
metadata:
  name: ejbca-backend-service
  labels:
    app: ejbca
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: https
    port: 8082
    targetPort: 8082
  selector:
    app: ejbca
---
apiVersion: v1
kind: Service
metadata:
  name: ejbca-database-service
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
  - name: dbport
    port: {{ .Values.dbservice.port }}
    targetPort: {{ .Values.dbservice.port }}
  selector:
    app: database
