# Hello-Go

service:
  name: "###CHART_NAME###"

spec:
  replicas: "1"
  image: "###IMAGE_NAME###"
  tag: "###IMAGE_TAG###"
  port: "80"

vm:
  hello-slogan: "This is a HELM packaged Kubernetes POD saying hello to the world!"

