apiVersion: siptls.sec.ericsson.com/v1
kind: InternalUserCA
metadata:
  name: {{ template "eric-scp.name" . }}-manager-ca
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-scp.name" . }}-manager-tls-client-ca-secret
    certificateName: cacertbundle.pem
  certificate:
    subject:
      cn: {{ template "eric-scp.name" . }}-manager-ca
