# Copyright 2022 Ericsson GmbH

apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-scp.name" . }}-worker-slf-client-internal-certificate
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: eric-scp-worker-slf-client-certificate
    certificateName: tls.crt
    privateKeyName: tls.key
  certificate:
    subject:
      cn: eric-scp-worker
    issuer:
      reference: eric-sc-slf-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
      
