{{- if eq (include "eric-scp.tls" .) "true" }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-scp.name" . }}-manager-fhah-client-certificate
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: scp-manager-fhah-client-if-certificate-secret
  certificate:
    subject:
      cn: eric-scp-manager
    issuer:
      reference: eric-fh-alarm-handler-fi-server-client-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}