{{- if .Values.rbac.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.manager.name }}
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
    app: {{ .Values.service.manager.name }} 
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
