/*
 * NSSF NS Selection
 * NSSF Network Slice Selection Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29531.nnssf.nsselection;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Tai;
import com.ericsson.cnal.openapi.r17.ts29510.nnrf.nfmanagement.TaiRange;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Snssai;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Contains the association of NSAGs and S-NSSAI(s) along with the TA(s) within
 * which the association is valid.
 */
@ApiModel(description = "Contains the association of NSAGs and S-NSSAI(s) along with the TA(s) within which the association is valid.")
@JsonPropertyOrder({ NsagInfo.JSON_PROPERTY_NSAG_IDS,
                     NsagInfo.JSON_PROPERTY_SNSSAI_LIST,
                     NsagInfo.JSON_PROPERTY_TAI_LIST,
                     NsagInfo.JSON_PROPERTY_TAI_RANGE_LIST })
public class NsagInfo
{
    public static final String JSON_PROPERTY_NSAG_IDS = "nsagIds";
    private List<Integer> nsagIds = new ArrayList<>();

    public static final String JSON_PROPERTY_SNSSAI_LIST = "snssaiList";
    private List<Snssai> snssaiList = new ArrayList<>();

    public static final String JSON_PROPERTY_TAI_LIST = "taiList";
    private List<Tai> taiList = null;

    public static final String JSON_PROPERTY_TAI_RANGE_LIST = "taiRangeList";
    private List<TaiRange> taiRangeList = null;

    public NsagInfo()
    {
    }

    public NsagInfo nsagIds(List<Integer> nsagIds)
    {

        this.nsagIds = nsagIds;
        return this;
    }

    public NsagInfo addNsagIdsItem(Integer nsagIdsItem)
    {
        this.nsagIds.add(nsagIdsItem);
        return this;
    }

    /**
     * Get nsagIds
     * 
     * @return nsagIds
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_NSAG_IDS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<Integer> getNsagIds()
    {
        return nsagIds;
    }

    @JsonProperty(JSON_PROPERTY_NSAG_IDS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNsagIds(List<Integer> nsagIds)
    {
        this.nsagIds = nsagIds;
    }

    public NsagInfo snssaiList(List<Snssai> snssaiList)
    {

        this.snssaiList = snssaiList;
        return this;
    }

    public NsagInfo addSnssaiListItem(Snssai snssaiListItem)
    {
        this.snssaiList.add(snssaiListItem);
        return this;
    }

    /**
     * Get snssaiList
     * 
     * @return snssaiList
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_SNSSAI_LIST)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<Snssai> getSnssaiList()
    {
        return snssaiList;
    }

    @JsonProperty(JSON_PROPERTY_SNSSAI_LIST)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSnssaiList(List<Snssai> snssaiList)
    {
        this.snssaiList = snssaiList;
    }

    public NsagInfo taiList(List<Tai> taiList)
    {

        this.taiList = taiList;
        return this;
    }

    public NsagInfo addTaiListItem(Tai taiListItem)
    {
        if (this.taiList == null)
        {
            this.taiList = new ArrayList<>();
        }
        this.taiList.add(taiListItem);
        return this;
    }

    /**
     * Get taiList
     * 
     * @return taiList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TAI_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Tai> getTaiList()
    {
        return taiList;
    }

    @JsonProperty(JSON_PROPERTY_TAI_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTaiList(List<Tai> taiList)
    {
        this.taiList = taiList;
    }

    public NsagInfo taiRangeList(List<TaiRange> taiRangeList)
    {

        this.taiRangeList = taiRangeList;
        return this;
    }

    public NsagInfo addTaiRangeListItem(TaiRange taiRangeListItem)
    {
        if (this.taiRangeList == null)
        {
            this.taiRangeList = new ArrayList<>();
        }
        this.taiRangeList.add(taiRangeListItem);
        return this;
    }

    /**
     * Get taiRangeList
     * 
     * @return taiRangeList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TAI_RANGE_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<TaiRange> getTaiRangeList()
    {
        return taiRangeList;
    }

    @JsonProperty(JSON_PROPERTY_TAI_RANGE_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTaiRangeList(List<TaiRange> taiRangeList)
    {
        this.taiRangeList = taiRangeList;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        NsagInfo nsagInfo = (NsagInfo) o;
        return Objects.equals(this.nsagIds, nsagInfo.nsagIds) && Objects.equals(this.snssaiList, nsagInfo.snssaiList)
               && Objects.equals(this.taiList, nsagInfo.taiList) && Objects.equals(this.taiRangeList, nsagInfo.taiRangeList);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(nsagIds, snssaiList, taiList, taiRangeList);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class NsagInfo {\n");
        sb.append("    nsagIds: ").append(toIndentedString(nsagIds)).append("\n");
        sb.append("    snssaiList: ").append(toIndentedString(snssaiList)).append("\n");
        sb.append("    taiList: ").append(toIndentedString(taiList)).append("\n");
        sb.append("    taiRangeList: ").append(toIndentedString(taiRangeList)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
