# vTaprecorder Simulator

service:
  name: "eric-vtaprecorder"

imageCredentials:
  registry:
    url: "armdocker.rnd.ericsson.se"
    pullSecret: "regcred"
  repoPath: "proj-5g-bsf"
  pullPolicy: Always

persistence:
  persistentVolumeClaim:
    size: "1Gi"
    storageClassName: "network-block"

spec:
  replicas: "1"
  image:
  tag: latest
  sinkPort: "4754"
  dtlsPort: "4755"
  ipVersion: "4"
  controlPort: "9999"
  resources:
    requests:
      cpu: 0.4
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
jvm:
  parameters: "-server -XX:+CrashOnOutOfMemoryError -XX:+ErrorFileToStderr -XX:+UseG1GC -XX:MaxRAMPercentage=80 -Dcom.sun.management.jmxremote.port=8100 -Dcom.sun.management.jmxremote.rmi.port=8100 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.host=127.0.0.1"      
