/*
 * Common Data Types
 * 
 *
 * OpenAPI spec version: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * 
 * This file has been auto-generated by the yaml2java script.
 */

package com.ericsson.cnal.openapi.r17.ts29571.commondata;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * JobType
 */
public class JobType
{
    public static final String IMMEDIATE_MDT_ONLY = "IMMEDIATE_MDT_ONLY";
    public static final String LOGGED_MDT_ONLY = "LOGGED_MDT_ONLY";
    public static final String TRACE_ONLY = "TRACE_ONLY";
    public static final String IMMEDIATE_MDT_AND_TRACE = "IMMEDIATE_MDT_AND_TRACE";
    public static final String RLF_REPORTS_ONLY = "RLF_REPORTS_ONLY";
    public static final String RCEF_REPORTS_ONLY = "RCEF_REPORTS_ONLY";
    public static final String LOGGED_MBSFN_MDT = "LOGGED_MBSFN_MDT";

}
