/*
 * Common Data Types
 * 
 *
 * OpenAPI spec version: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * 
 * This file has been auto-generated by the yaml2java script.
 */

package com.ericsson.cnal.openapi.r17.ts29571.commondata;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MatchingOperator
 */
public class MatchingOperator
{
    public static final String FULL_MATCH = "FULL_MATCH";
    public static final String MATCH_ALL = "MATCH_ALL";
    public static final String STARTS_WITH = "STARTS_WITH";
    public static final String NOT_START_WITH = "NOT_START_WITH";
    public static final String ENDS_WITH = "ENDS_WITH";
    public static final String NOT_END_WITH = "NOT_END_WITH";
    public static final String CONTAINS = "CONTAINS";
    public static final String NOT_CONTAIN = "NOT_CONTAIN";

}
