/*
 * Common Data Types
 * Common Data Types for Service Based Interfaces.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.   
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29571.commondata;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Represent MBS Media Information.
 */
@ApiModel(description = "Represent MBS Media Information.")
@JsonPropertyOrder({ MbsMediaInfo.JSON_PROPERTY_MBS_MED_TYPE,
                     MbsMediaInfo.JSON_PROPERTY_MAX_REQ_MBS_BW_DL,
                     MbsMediaInfo.JSON_PROPERTY_MIN_REQ_MBS_BW_DL,
                     MbsMediaInfo.JSON_PROPERTY_CODECS })
public class MbsMediaInfo
{
    public static final String JSON_PROPERTY_MBS_MED_TYPE = "mbsMedType";
    private String mbsMedType;

    public static final String JSON_PROPERTY_MAX_REQ_MBS_BW_DL = "maxReqMbsBwDl";
    private String maxReqMbsBwDl;

    public static final String JSON_PROPERTY_MIN_REQ_MBS_BW_DL = "minReqMbsBwDl";
    private String minReqMbsBwDl;

    public static final String JSON_PROPERTY_CODECS = "codecs";
    private List<String> codecs = null;

    public MbsMediaInfo()
    {
    }

    public MbsMediaInfo mbsMedType(String mbsMedType)
    {

        this.mbsMedType = mbsMedType;
        return this;
    }

    /**
     * Indicates the media type of a media component.
     * 
     * @return mbsMedType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates the media type of a media component.")
    @JsonProperty(JSON_PROPERTY_MBS_MED_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMbsMedType()
    {
        return mbsMedType;
    }

    @JsonProperty(JSON_PROPERTY_MBS_MED_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMbsMedType(String mbsMedType)
    {
        this.mbsMedType = mbsMedType;
    }

    public MbsMediaInfo maxReqMbsBwDl(String maxReqMbsBwDl)
    {

        this.maxReqMbsBwDl = maxReqMbsBwDl;
        return this;
    }

    /**
     * String representing a bit rate; the prefixes follow the standard symbols from
     * The International System of Units, and represent x1000 multipliers, with the
     * exception that prefix \&quot;K\&quot; is used to represent the standard
     * symbol \&quot;k\&quot;.
     * 
     * @return maxReqMbsBwDl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ")
    @JsonProperty(JSON_PROPERTY_MAX_REQ_MBS_BW_DL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMaxReqMbsBwDl()
    {
        return maxReqMbsBwDl;
    }

    @JsonProperty(JSON_PROPERTY_MAX_REQ_MBS_BW_DL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxReqMbsBwDl(String maxReqMbsBwDl)
    {
        this.maxReqMbsBwDl = maxReqMbsBwDl;
    }

    public MbsMediaInfo minReqMbsBwDl(String minReqMbsBwDl)
    {

        this.minReqMbsBwDl = minReqMbsBwDl;
        return this;
    }

    /**
     * String representing a bit rate; the prefixes follow the standard symbols from
     * The International System of Units, and represent x1000 multipliers, with the
     * exception that prefix \&quot;K\&quot; is used to represent the standard
     * symbol \&quot;k\&quot;.
     * 
     * @return minReqMbsBwDl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ")
    @JsonProperty(JSON_PROPERTY_MIN_REQ_MBS_BW_DL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMinReqMbsBwDl()
    {
        return minReqMbsBwDl;
    }

    @JsonProperty(JSON_PROPERTY_MIN_REQ_MBS_BW_DL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMinReqMbsBwDl(String minReqMbsBwDl)
    {
        this.minReqMbsBwDl = minReqMbsBwDl;
    }

    public MbsMediaInfo codecs(List<String> codecs)
    {

        this.codecs = codecs;
        return this;
    }

    public MbsMediaInfo addCodecsItem(String codecsItem)
    {
        if (this.codecs == null)
        {
            this.codecs = new ArrayList<>();
        }
        this.codecs.add(codecsItem);
        return this;
    }

    /**
     * Get codecs
     * 
     * @return codecs
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_CODECS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getCodecs()
    {
        return codecs;
    }

    @JsonProperty(JSON_PROPERTY_CODECS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCodecs(List<String> codecs)
    {
        this.codecs = codecs;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        MbsMediaInfo mbsMediaInfo = (MbsMediaInfo) o;
        return Objects.equals(this.mbsMedType, mbsMediaInfo.mbsMedType) && Objects.equals(this.maxReqMbsBwDl, mbsMediaInfo.maxReqMbsBwDl)
               && Objects.equals(this.minReqMbsBwDl, mbsMediaInfo.minReqMbsBwDl) && Objects.equals(this.codecs, mbsMediaInfo.codecs);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(mbsMedType, maxReqMbsBwDl, minReqMbsBwDl, codecs);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class MbsMediaInfo {\n");
        sb.append("    mbsMedType: ").append(toIndentedString(mbsMedType)).append("\n");
        sb.append("    maxReqMbsBwDl: ").append(toIndentedString(maxReqMbsBwDl)).append("\n");
        sb.append("    minReqMbsBwDl: ").append(toIndentedString(minReqMbsBwDl)).append("\n");
        sb.append("    codecs: ").append(toIndentedString(codecs)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
