/*
 * Nudm_MT
 * UDM MT Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29503.nudm.mt;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Tai;
import com.ericsson.cnal.openapi.r17.ts29572.nlmf.location.GeographicArea;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Ecgi;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Ncgi;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.PlmnId;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Represents the requested location information.
 */
@ApiModel(description = "Represents the requested location information.")
@JsonPropertyOrder({ LocationInfoResult.JSON_PROPERTY_V_PLMN_ID,
                     LocationInfoResult.JSON_PROPERTY_AMF_INSTANCE_ID,
                     LocationInfoResult.JSON_PROPERTY_SMSF_INSTANCE_ID,
                     LocationInfoResult.JSON_PROPERTY_NCGI,
                     LocationInfoResult.JSON_PROPERTY_ECGI,
                     LocationInfoResult.JSON_PROPERTY_TAI,
                     LocationInfoResult.JSON_PROPERTY_CURRENT_LOC,
                     LocationInfoResult.JSON_PROPERTY_GEO_INFO,
                     LocationInfoResult.JSON_PROPERTY_LOCATION_AGE,
                     LocationInfoResult.JSON_PROPERTY_RAT_TYPE,
                     LocationInfoResult.JSON_PROPERTY_TIMEZONE,
                     LocationInfoResult.JSON_PROPERTY_SUPPORTED_FEATURES })
public class LocationInfoResult
{
    public static final String JSON_PROPERTY_V_PLMN_ID = "vPlmnId";
    private PlmnId vPlmnId;

    public static final String JSON_PROPERTY_AMF_INSTANCE_ID = "amfInstanceId";
    private UUID amfInstanceId;

    public static final String JSON_PROPERTY_SMSF_INSTANCE_ID = "smsfInstanceId";
    private UUID smsfInstanceId;

    public static final String JSON_PROPERTY_NCGI = "ncgi";
    private Ncgi ncgi;

    public static final String JSON_PROPERTY_ECGI = "ecgi";
    private Ecgi ecgi;

    public static final String JSON_PROPERTY_TAI = "tai";
    private Tai tai;

    public static final String JSON_PROPERTY_CURRENT_LOC = "currentLoc";
    private Boolean currentLoc;

    public static final String JSON_PROPERTY_GEO_INFO = "geoInfo";
    private GeographicArea geoInfo;

    public static final String JSON_PROPERTY_LOCATION_AGE = "locationAge";
    private Integer locationAge;

    public static final String JSON_PROPERTY_RAT_TYPE = "ratType";
    private String ratType;

    public static final String JSON_PROPERTY_TIMEZONE = "timezone";
    private String timezone;

    public static final String JSON_PROPERTY_SUPPORTED_FEATURES = "supportedFeatures";
    private String supportedFeatures;

    public LocationInfoResult()
    {
    }

    public LocationInfoResult vPlmnId(PlmnId vPlmnId)
    {

        this.vPlmnId = vPlmnId;
        return this;
    }

    /**
     * Get vPlmnId
     * 
     * @return vPlmnId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_V_PLMN_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PlmnId getvPlmnId()
    {
        return vPlmnId;
    }

    @JsonProperty(JSON_PROPERTY_V_PLMN_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setvPlmnId(PlmnId vPlmnId)
    {
        this.vPlmnId = vPlmnId;
    }

    public LocationInfoResult amfInstanceId(UUID amfInstanceId)
    {

        this.amfInstanceId = amfInstanceId;
        return this;
    }

    /**
     * String uniquely identifying a NF instance. The format of the NF Instance ID
     * shall be a Universally Unique Identifier (UUID) version 4, as described in
     * IETF RFC 4122.
     * 
     * @return amfInstanceId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  ")
    @JsonProperty(JSON_PROPERTY_AMF_INSTANCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getAmfInstanceId()
    {
        return amfInstanceId;
    }

    @JsonProperty(JSON_PROPERTY_AMF_INSTANCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAmfInstanceId(UUID amfInstanceId)
    {
        this.amfInstanceId = amfInstanceId;
    }

    public LocationInfoResult smsfInstanceId(UUID smsfInstanceId)
    {

        this.smsfInstanceId = smsfInstanceId;
        return this;
    }

    /**
     * String uniquely identifying a NF instance. The format of the NF Instance ID
     * shall be a Universally Unique Identifier (UUID) version 4, as described in
     * IETF RFC 4122.
     * 
     * @return smsfInstanceId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  ")
    @JsonProperty(JSON_PROPERTY_SMSF_INSTANCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getSmsfInstanceId()
    {
        return smsfInstanceId;
    }

    @JsonProperty(JSON_PROPERTY_SMSF_INSTANCE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSmsfInstanceId(UUID smsfInstanceId)
    {
        this.smsfInstanceId = smsfInstanceId;
    }

    public LocationInfoResult ncgi(Ncgi ncgi)
    {

        this.ncgi = ncgi;
        return this;
    }

    /**
     * Get ncgi
     * 
     * @return ncgi
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_NCGI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Ncgi getNcgi()
    {
        return ncgi;
    }

    @JsonProperty(JSON_PROPERTY_NCGI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNcgi(Ncgi ncgi)
    {
        this.ncgi = ncgi;
    }

    public LocationInfoResult ecgi(Ecgi ecgi)
    {

        this.ecgi = ecgi;
        return this;
    }

    /**
     * Get ecgi
     * 
     * @return ecgi
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ECGI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Ecgi getEcgi()
    {
        return ecgi;
    }

    @JsonProperty(JSON_PROPERTY_ECGI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEcgi(Ecgi ecgi)
    {
        this.ecgi = ecgi;
    }

    public LocationInfoResult tai(Tai tai)
    {

        this.tai = tai;
        return this;
    }

    /**
     * Get tai
     * 
     * @return tai
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TAI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Tai getTai()
    {
        return tai;
    }

    @JsonProperty(JSON_PROPERTY_TAI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTai(Tai tai)
    {
        this.tai = tai;
    }

    public LocationInfoResult currentLoc(Boolean currentLoc)
    {

        this.currentLoc = currentLoc;
        return this;
    }

    /**
     * Get currentLoc
     * 
     * @return currentLoc
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_CURRENT_LOC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getCurrentLoc()
    {
        return currentLoc;
    }

    @JsonProperty(JSON_PROPERTY_CURRENT_LOC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCurrentLoc(Boolean currentLoc)
    {
        this.currentLoc = currentLoc;
    }

    public LocationInfoResult geoInfo(GeographicArea geoInfo)
    {

        this.geoInfo = geoInfo;
        return this;
    }

    /**
     * Get geoInfo
     * 
     * @return geoInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_GEO_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public GeographicArea getGeoInfo()
    {
        return geoInfo;
    }

    @JsonProperty(JSON_PROPERTY_GEO_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGeoInfo(GeographicArea geoInfo)
    {
        this.geoInfo = geoInfo;
    }

    public LocationInfoResult locationAge(Integer locationAge)
    {

        this.locationAge = locationAge;
        return this;
    }

    /**
     * Indicates value of the age of the location estimate. minimum: 0 maximum:
     * 32767
     * 
     * @return locationAge
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates value of the age of the location estimate.")
    @JsonProperty(JSON_PROPERTY_LOCATION_AGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getLocationAge()
    {
        return locationAge;
    }

    @JsonProperty(JSON_PROPERTY_LOCATION_AGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLocationAge(Integer locationAge)
    {
        this.locationAge = locationAge;
    }

    public LocationInfoResult ratType(String ratType)
    {

        this.ratType = ratType;
        return this;
    }

    /**
     * Indicates the radio access used.
     * 
     * @return ratType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates the radio access used.")
    @JsonProperty(JSON_PROPERTY_RAT_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getRatType()
    {
        return ratType;
    }

    @JsonProperty(JSON_PROPERTY_RAT_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRatType(String ratType)
    {
        this.ratType = ratType;
    }

    public LocationInfoResult timezone(String timezone)
    {

        this.timezone = timezone;
        return this;
    }

    /**
     * String with format \&quot;time-numoffset\&quot; optionally appended by
     * \&quot;daylightSavingTime\&quot;, where - \&quot;time-numoffset\&quot; shall
     * represent the time zone adjusted for daylight saving time and be encoded as
     * time-numoffset as defined in clause 5.6 of IETF RFC 3339; -
     * \&quot;daylightSavingTime\&quot; shall represent the adjustment that has been
     * made and shall be encoded as \&quot;+1\&quot; or \&quot;+2\&quot; for a +1 or
     * +2 hours adjustment. The example is for 8 hours behind UTC, +1 hour
     * adjustment for Daylight Saving Time.
     * 
     * @return timezone
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "-08:00+1",
                      value = "String with format \"time-numoffset\" optionally appended by \"daylightSavingTime\", where  - \"time-numoffset\" shall represent the time zone adjusted for daylight saving time and be    encoded as time-numoffset as defined in clause 5.6 of IETF RFC 3339;  - \"daylightSavingTime\" shall represent the adjustment that has been made and shall be    encoded as \"+1\" or \"+2\" for a +1 or +2 hours adjustment.  The example is for 8 hours behind UTC, +1 hour adjustment for Daylight Saving Time. ")
    @JsonProperty(JSON_PROPERTY_TIMEZONE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTimezone()
    {
        return timezone;
    }

    @JsonProperty(JSON_PROPERTY_TIMEZONE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTimezone(String timezone)
    {
        this.timezone = timezone;
    }

    public LocationInfoResult supportedFeatures(String supportedFeatures)
    {

        this.supportedFeatures = supportedFeatures;
        return this;
    }

    /**
     * A string used to indicate the features supported by an API that is used as
     * defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask
     * indicating supported features in hexadecimal representation Each character in
     * the string shall take a value of \&quot;0\&quot; to \&quot;9\&quot;,
     * \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to \&quot;F\&quot; and
     * shall represent the support of 4 features as described in table 5.2.2-3. The
     * most significant character representing the highest-numbered features shall
     * appear first in the string, and the character representing features 1 to 4
     * shall appear last in the string. The list of features and their numbering
     * (starting with 1) are defined separately for each API. If the string contains
     * a lower number of characters than there are defined features for an API, all
     * features that would be represented by characters that are not present in the
     * string are not supported.
     * 
     * @return supportedFeatures
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. ")
    @JsonProperty(JSON_PROPERTY_SUPPORTED_FEATURES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSupportedFeatures()
    {
        return supportedFeatures;
    }

    @JsonProperty(JSON_PROPERTY_SUPPORTED_FEATURES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSupportedFeatures(String supportedFeatures)
    {
        this.supportedFeatures = supportedFeatures;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        LocationInfoResult locationInfoResult = (LocationInfoResult) o;
        return Objects.equals(this.vPlmnId, locationInfoResult.vPlmnId) && Objects.equals(this.amfInstanceId, locationInfoResult.amfInstanceId)
               && Objects.equals(this.smsfInstanceId, locationInfoResult.smsfInstanceId) && Objects.equals(this.ncgi, locationInfoResult.ncgi)
               && Objects.equals(this.ecgi, locationInfoResult.ecgi) && Objects.equals(this.tai, locationInfoResult.tai)
               && Objects.equals(this.currentLoc, locationInfoResult.currentLoc) && Objects.equals(this.geoInfo, locationInfoResult.geoInfo)
               && Objects.equals(this.locationAge, locationInfoResult.locationAge) && Objects.equals(this.ratType, locationInfoResult.ratType)
               && Objects.equals(this.timezone, locationInfoResult.timezone) && Objects.equals(this.supportedFeatures, locationInfoResult.supportedFeatures);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(vPlmnId, amfInstanceId, smsfInstanceId, ncgi, ecgi, tai, currentLoc, geoInfo, locationAge, ratType, timezone, supportedFeatures);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class LocationInfoResult {\n");
        sb.append("    vPlmnId: ").append(toIndentedString(vPlmnId)).append("\n");
        sb.append("    amfInstanceId: ").append(toIndentedString(amfInstanceId)).append("\n");
        sb.append("    smsfInstanceId: ").append(toIndentedString(smsfInstanceId)).append("\n");
        sb.append("    ncgi: ").append(toIndentedString(ncgi)).append("\n");
        sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
        sb.append("    tai: ").append(toIndentedString(tai)).append("\n");
        sb.append("    currentLoc: ").append(toIndentedString(currentLoc)).append("\n");
        sb.append("    geoInfo: ").append(toIndentedString(geoInfo)).append("\n");
        sb.append("    locationAge: ").append(toIndentedString(locationAge)).append("\n");
        sb.append("    ratType: ").append(toIndentedString(ratType)).append("\n");
        sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
        sb.append("    supportedFeatures: ").append(toIndentedString(supportedFeatures)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
