apiVersion: siptls.sec.ericsson.com/v1
kind: InternalUserCA
metadata:
  name: {{ template "eric-sc-slf.name" . }}-ca
  annotations:
{{- include "eric-sc-slf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-slf.config-annotations" . | indent 4 }}
  labels:
    {{- include "eric-sc-slf.labels" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-sc-slf.name" . }}-tls-client-ca-secret
    certificateName: cacertbundle.pem
  certificate:
    subject:
      cn: {{ template "eric-sc-slf.name" . }}-ca