{{- if .Values.rbac.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.slf.name }}
  labels:
{{- include "eric-sc-slf.labels" . | indent 4 }}
    app: {{ .Values.service.slf.name }} 
  annotations:
{{- include "eric-sc-slf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-slf.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
