# Copyright 2019 Ericsson GmbH
{{- if eq (include "eric-sc-slf.tls" .) "true" }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-sc-slf.name" . }}-mediator-client-internal-certificate
  annotations:
{{- include "eric-sc-slf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-slf.config-annotations" . | indent 4 }}
  labels:
{{- include "eric-sc-slf.labels" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: slf-mediator-client-if-certificate-secret
    certificateName: tls.crt
    privateKeyName: tls.key
  certificate:
    subject:
      cn: eric-sc-slf
    issuer:
      reference: eric-cm-mediator-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}