{{- if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.service.slf.name }}-{{ .Release.Namespace }}
  labels:
{{- include "eric-sc-slf.labels" . | indent 4 }}
    app: {{ .Values.service.slf.name }}
  annotations:
{{- include "eric-sc-slf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-slf.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - ""
    resources:
#    - services
#    - endpoints
    - pods
    verbs:
#    - get
#    - list
#    - watch
#    - create
#    - update
    - patch
{{- end }}
