/*
 * Npcf_SMPolicyControl API
 * 
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * 
 * This file has been auto-generated by the yaml2java script.
 */

package com.ericsson.cnal.openapi.r17.ts29512.npcf.smpolicycontrol;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MulticastAccessControl
 */
public class MulticastAccessControl
{
    public static final String ALLOWED = "ALLOWED";
    public static final String NOT_ALLOWED = "NOT_ALLOWED";

}
