/*
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29512.npcf.smpolicycontrol;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.PlmnIdNid;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.ServerAddressingInfo;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.SubscribedDefaultQos;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.AccessType;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.TraceData;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.PcfUeCallbackInfo;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Snssai;
import com.ericsson.cnal.openapi.r17.ts29502.nsmf.pdusession.VplmnQos;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Ambr;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.UserLocation;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Contains the parameters used to create an Individual SM policy resource.
 */
@ApiModel(description = "Contains the parameters used to create an Individual SM policy resource.")
@JsonPropertyOrder({ SmPolicyContextData.JSON_PROPERTY_ACC_NET_CH_ID,
                     SmPolicyContextData.JSON_PROPERTY_CHARG_ENTITY_ADDR,
                     SmPolicyContextData.JSON_PROPERTY_GPSI,
                     SmPolicyContextData.JSON_PROPERTY_SUPI,
                     SmPolicyContextData.JSON_PROPERTY_INVALID_SUPI,
                     SmPolicyContextData.JSON_PROPERTY_INTER_GRP_IDS,
                     SmPolicyContextData.JSON_PROPERTY_PDU_SESSION_ID,
                     SmPolicyContextData.JSON_PROPERTY_PDU_SESSION_TYPE,
                     SmPolicyContextData.JSON_PROPERTY_CHARGINGCHARACTERISTICS,
                     SmPolicyContextData.JSON_PROPERTY_DNN,
                     SmPolicyContextData.JSON_PROPERTY_DNN_SEL_MODE,
                     SmPolicyContextData.JSON_PROPERTY_NOTIFICATION_URI,
                     SmPolicyContextData.JSON_PROPERTY_ACCESS_TYPE,
                     SmPolicyContextData.JSON_PROPERTY_RAT_TYPE,
                     SmPolicyContextData.JSON_PROPERTY_ADD_ACCESS_INFO,
                     SmPolicyContextData.JSON_PROPERTY_SERVING_NETWORK,
                     SmPolicyContextData.JSON_PROPERTY_USER_LOCATION_INFO,
                     SmPolicyContextData.JSON_PROPERTY_UE_TIME_ZONE,
                     SmPolicyContextData.JSON_PROPERTY_PEI,
                     SmPolicyContextData.JSON_PROPERTY_IPV4_ADDRESS,
                     SmPolicyContextData.JSON_PROPERTY_IPV6_ADDRESS_PREFIX,
                     SmPolicyContextData.JSON_PROPERTY_IP_DOMAIN,
                     SmPolicyContextData.JSON_PROPERTY_SUBS_SESS_AMBR,
                     SmPolicyContextData.JSON_PROPERTY_AUTH_PROF_INDEX,
                     SmPolicyContextData.JSON_PROPERTY_SUBS_DEF_QOS,
                     SmPolicyContextData.JSON_PROPERTY_VPLMN_QOS,
                     SmPolicyContextData.JSON_PROPERTY_NUM_OF_PACK_FILTER,
                     SmPolicyContextData.JSON_PROPERTY_ONLINE,
                     SmPolicyContextData.JSON_PROPERTY_OFFLINE,
                     SmPolicyContextData.JSON_PROPERTY_3GPP_PS_DATA_OFF_STATUS,
                     SmPolicyContextData.JSON_PROPERTY_REF_QOS_INDICATION,
                     SmPolicyContextData.JSON_PROPERTY_TRACE_REQ,
                     SmPolicyContextData.JSON_PROPERTY_SLICE_INFO,
                     SmPolicyContextData.JSON_PROPERTY_QOS_FLOW_USAGE,
                     SmPolicyContextData.JSON_PROPERTY_SERV_NF_ID,
                     SmPolicyContextData.JSON_PROPERTY_SUPP_FEAT,
                     SmPolicyContextData.JSON_PROPERTY_SMF_ID,
                     SmPolicyContextData.JSON_PROPERTY_RECOVERY_TIME,
                     SmPolicyContextData.JSON_PROPERTY_MA_PDU_IND,
                     SmPolicyContextData.JSON_PROPERTY_ATSSS_CAPAB,
                     SmPolicyContextData.JSON_PROPERTY_IPV4_FRAME_ROUTE_LIST,
                     SmPolicyContextData.JSON_PROPERTY_IPV6_FRAME_ROUTE_LIST,
                     SmPolicyContextData.JSON_PROPERTY_SAT_BACKHAUL_CATEGORY,
                     SmPolicyContextData.JSON_PROPERTY_PCF_UE_INFO,
                     SmPolicyContextData.JSON_PROPERTY_PVS_INFO,
                     SmPolicyContextData.JSON_PROPERTY_ONBOARD_IND,
                     SmPolicyContextData.JSON_PROPERTY_NWDAF_DATAS })
public class SmPolicyContextData
{
    public static final String JSON_PROPERTY_ACC_NET_CH_ID = "accNetChId";
    private AccNetChId accNetChId;

    public static final String JSON_PROPERTY_CHARG_ENTITY_ADDR = "chargEntityAddr";
    private AccNetChargingAddress chargEntityAddr;

    public static final String JSON_PROPERTY_GPSI = "gpsi";
    private String gpsi;

    public static final String JSON_PROPERTY_SUPI = "supi";
    private String supi;

    public static final String JSON_PROPERTY_INVALID_SUPI = "invalidSupi";
    private Boolean invalidSupi;

    public static final String JSON_PROPERTY_INTER_GRP_IDS = "interGrpIds";
    private List<String> interGrpIds = null;

    public static final String JSON_PROPERTY_PDU_SESSION_ID = "pduSessionId";
    private Integer pduSessionId;

    public static final String JSON_PROPERTY_PDU_SESSION_TYPE = "pduSessionType";
    private String pduSessionType;

    public static final String JSON_PROPERTY_CHARGINGCHARACTERISTICS = "chargingcharacteristics";
    private String chargingcharacteristics;

    public static final String JSON_PROPERTY_DNN = "dnn";
    private String dnn;

    public static final String JSON_PROPERTY_DNN_SEL_MODE = "dnnSelMode";
    private String dnnSelMode;

    public static final String JSON_PROPERTY_NOTIFICATION_URI = "notificationUri";
    private String notificationUri;

    public static final String JSON_PROPERTY_ACCESS_TYPE = "accessType";
    private AccessType accessType;

    public static final String JSON_PROPERTY_RAT_TYPE = "ratType";
    private String ratType;

    public static final String JSON_PROPERTY_ADD_ACCESS_INFO = "addAccessInfo";
    private AdditionalAccessInfo addAccessInfo;

    public static final String JSON_PROPERTY_SERVING_NETWORK = "servingNetwork";
    private PlmnIdNid servingNetwork;

    public static final String JSON_PROPERTY_USER_LOCATION_INFO = "userLocationInfo";
    private UserLocation userLocationInfo;

    public static final String JSON_PROPERTY_UE_TIME_ZONE = "ueTimeZone";
    private String ueTimeZone;

    public static final String JSON_PROPERTY_PEI = "pei";
    private String pei;

    public static final String JSON_PROPERTY_IPV4_ADDRESS = "ipv4Address";
    private String ipv4Address;

    public static final String JSON_PROPERTY_IPV6_ADDRESS_PREFIX = "ipv6AddressPrefix";
    private String ipv6AddressPrefix;

    public static final String JSON_PROPERTY_IP_DOMAIN = "ipDomain";
    private String ipDomain;

    public static final String JSON_PROPERTY_SUBS_SESS_AMBR = "subsSessAmbr";
    private Ambr subsSessAmbr;

    public static final String JSON_PROPERTY_AUTH_PROF_INDEX = "authProfIndex";
    private String authProfIndex;

    public static final String JSON_PROPERTY_SUBS_DEF_QOS = "subsDefQos";
    private SubscribedDefaultQos subsDefQos;

    public static final String JSON_PROPERTY_VPLMN_QOS = "vplmnQos";
    private VplmnQos vplmnQos;

    public static final String JSON_PROPERTY_NUM_OF_PACK_FILTER = "numOfPackFilter";
    private Integer numOfPackFilter;

    public static final String JSON_PROPERTY_ONLINE = "online";
    private Boolean online;

    public static final String JSON_PROPERTY_OFFLINE = "offline";
    private Boolean offline;

    public static final String JSON_PROPERTY_3GPP_PS_DATA_OFF_STATUS = "3gppPsDataOffStatus";
    private Boolean _3gppPsDataOffStatus;

    public static final String JSON_PROPERTY_REF_QOS_INDICATION = "refQosIndication";
    private Boolean refQosIndication;

    public static final String JSON_PROPERTY_TRACE_REQ = "traceReq";
    private JsonNullable<TraceData> traceReq = JsonNullable.<TraceData>undefined();

    public static final String JSON_PROPERTY_SLICE_INFO = "sliceInfo";
    private Snssai sliceInfo;

    public static final String JSON_PROPERTY_QOS_FLOW_USAGE = "qosFlowUsage";
    private String qosFlowUsage;

    public static final String JSON_PROPERTY_SERV_NF_ID = "servNfId";
    private ServingNfIdentity servNfId;

    public static final String JSON_PROPERTY_SUPP_FEAT = "suppFeat";
    private String suppFeat;

    public static final String JSON_PROPERTY_SMF_ID = "smfId";
    private UUID smfId;

    public static final String JSON_PROPERTY_RECOVERY_TIME = "recoveryTime";
    private OffsetDateTime recoveryTime;

    public static final String JSON_PROPERTY_MA_PDU_IND = "maPduInd";
    private String maPduInd;

    public static final String JSON_PROPERTY_ATSSS_CAPAB = "atsssCapab";
    private String atsssCapab;

    public static final String JSON_PROPERTY_IPV4_FRAME_ROUTE_LIST = "ipv4FrameRouteList";
    private List<String> ipv4FrameRouteList = null;

    public static final String JSON_PROPERTY_IPV6_FRAME_ROUTE_LIST = "ipv6FrameRouteList";
    private List<String> ipv6FrameRouteList = null;

    public static final String JSON_PROPERTY_SAT_BACKHAUL_CATEGORY = "satBackhaulCategory";
    private String satBackhaulCategory;

    public static final String JSON_PROPERTY_PCF_UE_INFO = "pcfUeInfo";
    private JsonNullable<PcfUeCallbackInfo> pcfUeInfo = JsonNullable.<PcfUeCallbackInfo>undefined();

    public static final String JSON_PROPERTY_PVS_INFO = "pvsInfo";
    private List<ServerAddressingInfo> pvsInfo = null;

    public static final String JSON_PROPERTY_ONBOARD_IND = "onboardInd";
    private Boolean onboardInd;

    public static final String JSON_PROPERTY_NWDAF_DATAS = "nwdafDatas";
    private List<NwdafData> nwdafDatas = null;

    public SmPolicyContextData()
    {
    }

    public SmPolicyContextData accNetChId(AccNetChId accNetChId)
    {

        this.accNetChId = accNetChId;
        return this;
    }

    /**
     * Get accNetChId
     * 
     * @return accNetChId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ACC_NET_CH_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AccNetChId getAccNetChId()
    {
        return accNetChId;
    }

    @JsonProperty(JSON_PROPERTY_ACC_NET_CH_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAccNetChId(AccNetChId accNetChId)
    {
        this.accNetChId = accNetChId;
    }

    public SmPolicyContextData chargEntityAddr(AccNetChargingAddress chargEntityAddr)
    {

        this.chargEntityAddr = chargEntityAddr;
        return this;
    }

    /**
     * Get chargEntityAddr
     * 
     * @return chargEntityAddr
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_CHARG_ENTITY_ADDR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AccNetChargingAddress getChargEntityAddr()
    {
        return chargEntityAddr;
    }

    @JsonProperty(JSON_PROPERTY_CHARG_ENTITY_ADDR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setChargEntityAddr(AccNetChargingAddress chargEntityAddr)
    {
        this.chargEntityAddr = chargEntityAddr;
    }

    public SmPolicyContextData gpsi(String gpsi)
    {

        this.gpsi = gpsi;
        return this;
    }

    /**
     * String identifying a Gpsi shall contain either an External Id or an MSISDN.
     * It shall be formatted as follows -External Identifier&#x3D;
     * \&quot;extid-&#39;extid&#39;, where &#39;extid&#39; shall be formatted
     * according to clause 19.7.2 of 3GPP TS 23.003 that describes an External
     * Identifier.
     * 
     * @return gpsi
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  ")
    @JsonProperty(JSON_PROPERTY_GPSI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getGpsi()
    {
        return gpsi;
    }

    @JsonProperty(JSON_PROPERTY_GPSI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGpsi(String gpsi)
    {
        this.gpsi = gpsi;
    }

    public SmPolicyContextData supi(String supi)
    {

        this.supi = supi;
        return this;
    }

    /**
     * String identifying a Supi that shall contain either an IMSI, a network
     * specific identifier, a Global Cable Identifier (GCI) or a Global Line
     * Identifier (GLI) as specified in clause 2.2A of 3GPP TS 23.003. It shall be
     * formatted as follows - for an IMSI \&quot;imsi-&lt;imsi&gt;\&quot;, where
     * &lt;imsi&gt; shall be formatted according to clause 2.2 of 3GPP TS 23.003
     * that describes an IMSI. - for a network specific identifier
     * \&quot;nai-&lt;nai&gt;, where &lt;nai&gt; shall be formatted according to
     * clause 28.7.2 of 3GPP TS 23.003 that describes an NAI. - for a GCI
     * \&quot;gci-&lt;gci&gt;\&quot;, where &lt;gci&gt; shall be formatted according
     * to clause 28.15.2 of 3GPP TS 23.003. - for a GLI
     * \&quot;gli-&lt;gli&gt;\&quot;, where &lt;gli&gt; shall be formatted according
     * to clause 28.16.2 of 3GPP TS 23.003.To enable that the value is used as part
     * of an URI, the string shall only contain characters allowed according to the
     * \&quot;lower-with-hyphen\&quot; naming convention defined in 3GPP TS 29.501.
     * 
     * @return supi
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true,
                      value = "String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501. ")
    @JsonProperty(JSON_PROPERTY_SUPI)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getSupi()
    {
        return supi;
    }

    @JsonProperty(JSON_PROPERTY_SUPI)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSupi(String supi)
    {
        this.supi = supi;
    }

    public SmPolicyContextData invalidSupi(Boolean invalidSupi)
    {

        this.invalidSupi = invalidSupi;
        return this;
    }

    /**
     * When this attribute is included and set to true, it indicates that the supi
     * attribute contains an invalid value.This attribute shall be present if the
     * SUPI is not available in the SMF or the SUPI is unauthenticated. When present
     * it shall be set to true for an invalid SUPI and false (default) for a valid
     * SUPI.
     * 
     * @return invalidSupi
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "When this attribute is included and set to true, it indicates that the supi attribute contains an invalid value.This attribute shall be present if the SUPI is not available in the SMF or the SUPI is unauthenticated. When present it shall be set to true for an invalid SUPI and false (default) for a valid SUPI. ")
    @JsonProperty(JSON_PROPERTY_INVALID_SUPI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getInvalidSupi()
    {
        return invalidSupi;
    }

    @JsonProperty(JSON_PROPERTY_INVALID_SUPI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setInvalidSupi(Boolean invalidSupi)
    {
        this.invalidSupi = invalidSupi;
    }

    public SmPolicyContextData interGrpIds(List<String> interGrpIds)
    {

        this.interGrpIds = interGrpIds;
        return this;
    }

    public SmPolicyContextData addInterGrpIdsItem(String interGrpIdsItem)
    {
        if (this.interGrpIds == null)
        {
            this.interGrpIds = new ArrayList<>();
        }
        this.interGrpIds.add(interGrpIdsItem);
        return this;
    }

    /**
     * Get interGrpIds
     * 
     * @return interGrpIds
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_INTER_GRP_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getInterGrpIds()
    {
        return interGrpIds;
    }

    @JsonProperty(JSON_PROPERTY_INTER_GRP_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setInterGrpIds(List<String> interGrpIds)
    {
        this.interGrpIds = interGrpIds;
    }

    public SmPolicyContextData pduSessionId(Integer pduSessionId)
    {

        this.pduSessionId = pduSessionId;
        return this;
    }

    /**
     * Unsigned integer identifying a PDU session, within the range 0 to 255, as
     * specified in clause 11.2.3.1b, bits 1 to 8, of 3GPP TS 24.007. If the PDU
     * Session ID is allocated by the Core Network for UEs not supporting N1 mode,
     * reserved range 64 to 95 is used. PDU Session ID within the reserved range is
     * only visible in the Core Network. minimum: 0 maximum: 255
     * 
     * @return pduSessionId
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true,
                      value = "Unsigned integer identifying a PDU session, within the range 0 to 255, as specified in  clause 11.2.3.1b, bits 1 to 8, of 3GPP TS 24.007. If the PDU Session ID is allocated by the  Core Network for UEs not supporting N1 mode, reserved range 64 to 95 is used. PDU Session ID  within the reserved range is only visible in the Core Network.  ")
    @JsonProperty(JSON_PROPERTY_PDU_SESSION_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Integer getPduSessionId()
    {
        return pduSessionId;
    }

    @JsonProperty(JSON_PROPERTY_PDU_SESSION_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPduSessionId(Integer pduSessionId)
    {
        this.pduSessionId = pduSessionId;
    }

    public SmPolicyContextData pduSessionType(String pduSessionType)
    {

        this.pduSessionType = pduSessionType;
        return this;
    }

    /**
     * PduSessionType indicates the type of a PDU session. It shall comply with the
     * provisions defined in table 5.4.3.3-1.
     * 
     * @return pduSessionType
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true,
                      value = "PduSessionType indicates the type of a PDU session. It shall comply with the provisions defined in table 5.4.3.3-1.  ")
    @JsonProperty(JSON_PROPERTY_PDU_SESSION_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getPduSessionType()
    {
        return pduSessionType;
    }

    @JsonProperty(JSON_PROPERTY_PDU_SESSION_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPduSessionType(String pduSessionType)
    {
        this.pduSessionType = pduSessionType;
    }

    public SmPolicyContextData chargingcharacteristics(String chargingcharacteristics)
    {

        this.chargingcharacteristics = chargingcharacteristics;
        return this;
    }

    /**
     * Get chargingcharacteristics
     * 
     * @return chargingcharacteristics
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_CHARGINGCHARACTERISTICS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getChargingcharacteristics()
    {
        return chargingcharacteristics;
    }

    @JsonProperty(JSON_PROPERTY_CHARGINGCHARACTERISTICS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setChargingcharacteristics(String chargingcharacteristics)
    {
        this.chargingcharacteristics = chargingcharacteristics;
    }

    public SmPolicyContextData dnn(String dnn)
    {

        this.dnn = dnn;
        return this;
    }

    /**
     * String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;
     * it shall contain either a DNN Network Identifier, or a full DNN with both the
     * Network Identifier and Operator Identifier, as specified in 3GPP TS 23.003
     * clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are
     * separated by dots (e.g. \&quot;Label1.Label2.Label3\&quot;).
     * 
     * @return dnn
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true,
                      value = "String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\"). ")
    @JsonProperty(JSON_PROPERTY_DNN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getDnn()
    {
        return dnn;
    }

    @JsonProperty(JSON_PROPERTY_DNN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDnn(String dnn)
    {
        this.dnn = dnn;
    }

    public SmPolicyContextData dnnSelMode(String dnnSelMode)
    {

        this.dnnSelMode = dnnSelMode;
        return this;
    }

    /**
     * DNN Selection Mode. Possible values are - VERIFIED - UE_DNN_NOT_VERIFIED -
     * NW_DNN_NOT_VERIFIED
     * 
     * @return dnnSelMode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "DNN Selection Mode. Possible values are - VERIFIED - UE_DNN_NOT_VERIFIED - NW_DNN_NOT_VERIFIED ")
    @JsonProperty(JSON_PROPERTY_DNN_SEL_MODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDnnSelMode()
    {
        return dnnSelMode;
    }

    @JsonProperty(JSON_PROPERTY_DNN_SEL_MODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDnnSelMode(String dnnSelMode)
    {
        this.dnnSelMode = dnnSelMode;
    }

    public SmPolicyContextData notificationUri(String notificationUri)
    {

        this.notificationUri = notificationUri;
        return this;
    }

    /**
     * String providing an URI formatted according to RFC 3986.
     * 
     * @return notificationUri
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "String providing an URI formatted according to RFC 3986.")
    @JsonProperty(JSON_PROPERTY_NOTIFICATION_URI)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getNotificationUri()
    {
        return notificationUri;
    }

    @JsonProperty(JSON_PROPERTY_NOTIFICATION_URI)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNotificationUri(String notificationUri)
    {
        this.notificationUri = notificationUri;
    }

    public SmPolicyContextData accessType(AccessType accessType)
    {

        this.accessType = accessType;
        return this;
    }

    /**
     * Get accessType
     * 
     * @return accessType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ACCESS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AccessType getAccessType()
    {
        return accessType;
    }

    @JsonProperty(JSON_PROPERTY_ACCESS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAccessType(AccessType accessType)
    {
        this.accessType = accessType;
    }

    public SmPolicyContextData ratType(String ratType)
    {

        this.ratType = ratType;
        return this;
    }

    /**
     * Indicates the radio access used.
     * 
     * @return ratType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates the radio access used.")
    @JsonProperty(JSON_PROPERTY_RAT_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getRatType()
    {
        return ratType;
    }

    @JsonProperty(JSON_PROPERTY_RAT_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRatType(String ratType)
    {
        this.ratType = ratType;
    }

    public SmPolicyContextData addAccessInfo(AdditionalAccessInfo addAccessInfo)
    {

        this.addAccessInfo = addAccessInfo;
        return this;
    }

    /**
     * Get addAccessInfo
     * 
     * @return addAccessInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ADD_ACCESS_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AdditionalAccessInfo getAddAccessInfo()
    {
        return addAccessInfo;
    }

    @JsonProperty(JSON_PROPERTY_ADD_ACCESS_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAddAccessInfo(AdditionalAccessInfo addAccessInfo)
    {
        this.addAccessInfo = addAccessInfo;
    }

    public SmPolicyContextData servingNetwork(PlmnIdNid servingNetwork)
    {

        this.servingNetwork = servingNetwork;
        return this;
    }

    /**
     * Get servingNetwork
     * 
     * @return servingNetwork
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SERVING_NETWORK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PlmnIdNid getServingNetwork()
    {
        return servingNetwork;
    }

    @JsonProperty(JSON_PROPERTY_SERVING_NETWORK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setServingNetwork(PlmnIdNid servingNetwork)
    {
        this.servingNetwork = servingNetwork;
    }

    public SmPolicyContextData userLocationInfo(UserLocation userLocationInfo)
    {

        this.userLocationInfo = userLocationInfo;
        return this;
    }

    /**
     * Get userLocationInfo
     * 
     * @return userLocationInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_USER_LOCATION_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UserLocation getUserLocationInfo()
    {
        return userLocationInfo;
    }

    @JsonProperty(JSON_PROPERTY_USER_LOCATION_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserLocationInfo(UserLocation userLocationInfo)
    {
        this.userLocationInfo = userLocationInfo;
    }

    public SmPolicyContextData ueTimeZone(String ueTimeZone)
    {

        this.ueTimeZone = ueTimeZone;
        return this;
    }

    /**
     * String with format \&quot;time-numoffset\&quot; optionally appended by
     * \&quot;daylightSavingTime\&quot;, where - \&quot;time-numoffset\&quot; shall
     * represent the time zone adjusted for daylight saving time and be encoded as
     * time-numoffset as defined in clause 5.6 of IETF RFC 3339; -
     * \&quot;daylightSavingTime\&quot; shall represent the adjustment that has been
     * made and shall be encoded as \&quot;+1\&quot; or \&quot;+2\&quot; for a +1 or
     * +2 hours adjustment. The example is for 8 hours behind UTC, +1 hour
     * adjustment for Daylight Saving Time.
     * 
     * @return ueTimeZone
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "-08:00+1",
                      value = "String with format \"time-numoffset\" optionally appended by \"daylightSavingTime\", where  - \"time-numoffset\" shall represent the time zone adjusted for daylight saving time and be    encoded as time-numoffset as defined in clause 5.6 of IETF RFC 3339;  - \"daylightSavingTime\" shall represent the adjustment that has been made and shall be    encoded as \"+1\" or \"+2\" for a +1 or +2 hours adjustment.  The example is for 8 hours behind UTC, +1 hour adjustment for Daylight Saving Time. ")
    @JsonProperty(JSON_PROPERTY_UE_TIME_ZONE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUeTimeZone()
    {
        return ueTimeZone;
    }

    @JsonProperty(JSON_PROPERTY_UE_TIME_ZONE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUeTimeZone(String ueTimeZone)
    {
        this.ueTimeZone = ueTimeZone;
    }

    public SmPolicyContextData pei(String pei)
    {

        this.pei = pei;
        return this;
    }

    /**
     * String representing a Permanent Equipment Identifier that may contain - an
     * IMEI or IMEISV, as specified in clause 6.2 of 3GPP TS 23.003; a MAC address
     * for a 5G-RG or FN-RG via wireline access, with an indication that this
     * address cannot be trusted for regulatory purpose if this address cannot be
     * used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7 of
     * 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345.
     * 
     * @return pei
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String representing a Permanent Equipment Identifier that may contain - an IMEI or IMEISV, as  specified in clause 6.2 of 3GPP TS 23.003; a MAC address for a 5G-RG or FN-RG via  wireline  access, with an indication that this address cannot be trusted for regulatory purpose if this  address cannot be used as an Equipment Identifier of the FN-RG, as specified in clause 4.7.7  of 3GPP TS23.316. Examples are imei-012345678901234 or imeisv-0123456789012345.  ")
    @JsonProperty(JSON_PROPERTY_PEI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPei()
    {
        return pei;
    }

    @JsonProperty(JSON_PROPERTY_PEI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPei(String pei)
    {
        this.pei = pei;
    }

    public SmPolicyContextData ipv4Address(String ipv4Address)
    {

        this.ipv4Address = ipv4Address;
        return this;
    }

    /**
     * String identifying a IPv4 address formatted in the &#39;dotted decimal&#39;
     * notation as defined in RFC 1166.
     * 
     * @return ipv4Address
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "198.51.100.1", value = "String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166. ")
    @JsonProperty(JSON_PROPERTY_IPV4_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getIpv4Address()
    {
        return ipv4Address;
    }

    @JsonProperty(JSON_PROPERTY_IPV4_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIpv4Address(String ipv4Address)
    {
        this.ipv4Address = ipv4Address;
    }

    public SmPolicyContextData ipv6AddressPrefix(String ipv6AddressPrefix)
    {

        this.ipv6AddressPrefix = ipv6AddressPrefix;
        return this;
    }

    /**
     * Get ipv6AddressPrefix
     * 
     * @return ipv6AddressPrefix
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_IPV6_ADDRESS_PREFIX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getIpv6AddressPrefix()
    {
        return ipv6AddressPrefix;
    }

    @JsonProperty(JSON_PROPERTY_IPV6_ADDRESS_PREFIX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIpv6AddressPrefix(String ipv6AddressPrefix)
    {
        this.ipv6AddressPrefix = ipv6AddressPrefix;
    }

    public SmPolicyContextData ipDomain(String ipDomain)
    {

        this.ipDomain = ipDomain;
        return this;
    }

    /**
     * Indicates the IPv4 address domain
     * 
     * @return ipDomain
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates the IPv4 address domain")
    @JsonProperty(JSON_PROPERTY_IP_DOMAIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getIpDomain()
    {
        return ipDomain;
    }

    @JsonProperty(JSON_PROPERTY_IP_DOMAIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIpDomain(String ipDomain)
    {
        this.ipDomain = ipDomain;
    }

    public SmPolicyContextData subsSessAmbr(Ambr subsSessAmbr)
    {

        this.subsSessAmbr = subsSessAmbr;
        return this;
    }

    /**
     * Get subsSessAmbr
     * 
     * @return subsSessAmbr
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SUBS_SESS_AMBR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Ambr getSubsSessAmbr()
    {
        return subsSessAmbr;
    }

    @JsonProperty(JSON_PROPERTY_SUBS_SESS_AMBR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubsSessAmbr(Ambr subsSessAmbr)
    {
        this.subsSessAmbr = subsSessAmbr;
    }

    public SmPolicyContextData authProfIndex(String authProfIndex)
    {

        this.authProfIndex = authProfIndex;
        return this;
    }

    /**
     * Indicates the DN-AAA authorization profile index
     * 
     * @return authProfIndex
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates the DN-AAA authorization profile index")
    @JsonProperty(JSON_PROPERTY_AUTH_PROF_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAuthProfIndex()
    {
        return authProfIndex;
    }

    @JsonProperty(JSON_PROPERTY_AUTH_PROF_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAuthProfIndex(String authProfIndex)
    {
        this.authProfIndex = authProfIndex;
    }

    public SmPolicyContextData subsDefQos(SubscribedDefaultQos subsDefQos)
    {

        this.subsDefQos = subsDefQos;
        return this;
    }

    /**
     * Get subsDefQos
     * 
     * @return subsDefQos
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SUBS_DEF_QOS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public SubscribedDefaultQos getSubsDefQos()
    {
        return subsDefQos;
    }

    @JsonProperty(JSON_PROPERTY_SUBS_DEF_QOS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubsDefQos(SubscribedDefaultQos subsDefQos)
    {
        this.subsDefQos = subsDefQos;
    }

    public SmPolicyContextData vplmnQos(VplmnQos vplmnQos)
    {

        this.vplmnQos = vplmnQos;
        return this;
    }

    /**
     * Get vplmnQos
     * 
     * @return vplmnQos
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_VPLMN_QOS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public VplmnQos getVplmnQos()
    {
        return vplmnQos;
    }

    @JsonProperty(JSON_PROPERTY_VPLMN_QOS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVplmnQos(VplmnQos vplmnQos)
    {
        this.vplmnQos = vplmnQos;
    }

    public SmPolicyContextData numOfPackFilter(Integer numOfPackFilter)
    {

        this.numOfPackFilter = numOfPackFilter;
        return this;
    }

    /**
     * Contains the number of supported packet filter for signalled QoS rules.
     * 
     * @return numOfPackFilter
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Contains the number of supported packet filter for signalled QoS rules.")
    @JsonProperty(JSON_PROPERTY_NUM_OF_PACK_FILTER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getNumOfPackFilter()
    {
        return numOfPackFilter;
    }

    @JsonProperty(JSON_PROPERTY_NUM_OF_PACK_FILTER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNumOfPackFilter(Integer numOfPackFilter)
    {
        this.numOfPackFilter = numOfPackFilter;
    }

    public SmPolicyContextData online(Boolean online)
    {

        this.online = online;
        return this;
    }

    /**
     * If it is included and set to true, the online charging is applied to the PDU
     * session.
     * 
     * @return online
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "If it is included and set to true, the online charging is applied to the PDU session.")
    @JsonProperty(JSON_PROPERTY_ONLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getOnline()
    {
        return online;
    }

    @JsonProperty(JSON_PROPERTY_ONLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOnline(Boolean online)
    {
        this.online = online;
    }

    public SmPolicyContextData offline(Boolean offline)
    {

        this.offline = offline;
        return this;
    }

    /**
     * If it is included and set to true, the offline charging is applied to the PDU
     * session.
     * 
     * @return offline
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "If it is included and set to true, the offline charging is applied to the PDU session.")
    @JsonProperty(JSON_PROPERTY_OFFLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getOffline()
    {
        return offline;
    }

    @JsonProperty(JSON_PROPERTY_OFFLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOffline(Boolean offline)
    {
        this.offline = offline;
    }

    public SmPolicyContextData _3gppPsDataOffStatus(Boolean _3gppPsDataOffStatus)
    {

        this._3gppPsDataOffStatus = _3gppPsDataOffStatus;
        return this;
    }

    /**
     * If it is included and set to true, the 3GPP PS Data Off is activated by the
     * UE.
     * 
     * @return _3gppPsDataOffStatus
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "If it is included and set to true, the 3GPP PS Data Off is activated by the UE.")
    @JsonProperty(JSON_PROPERTY_3GPP_PS_DATA_OFF_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean get3gppPsDataOffStatus()
    {
        return _3gppPsDataOffStatus;
    }

    @JsonProperty(JSON_PROPERTY_3GPP_PS_DATA_OFF_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void set3gppPsDataOffStatus(Boolean _3gppPsDataOffStatus)
    {
        this._3gppPsDataOffStatus = _3gppPsDataOffStatus;
    }

    public SmPolicyContextData refQosIndication(Boolean refQosIndication)
    {

        this.refQosIndication = refQosIndication;
        return this;
    }

    /**
     * If it is included and set to true, the reflective QoS is supported by the UE.
     * 
     * @return refQosIndication
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "If it is included and set to true, the reflective QoS is supported by the UE.")
    @JsonProperty(JSON_PROPERTY_REF_QOS_INDICATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRefQosIndication()
    {
        return refQosIndication;
    }

    @JsonProperty(JSON_PROPERTY_REF_QOS_INDICATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRefQosIndication(Boolean refQosIndication)
    {
        this.refQosIndication = refQosIndication;
    }

    public SmPolicyContextData traceReq(TraceData traceReq)
    {
        this.traceReq = JsonNullable.<TraceData>of(traceReq);

        return this;
    }

    /**
     * Get traceReq
     * 
     * @return traceReq
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonIgnore

    public TraceData getTraceReq()
    {
        return traceReq.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_TRACE_REQ)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<TraceData> getTraceReq_JsonNullable()
    {
        return traceReq;
    }

    @JsonProperty(JSON_PROPERTY_TRACE_REQ)
    public void setTraceReq_JsonNullable(JsonNullable<TraceData> traceReq)
    {
        this.traceReq = traceReq;
    }

    public void setTraceReq(TraceData traceReq)
    {
        this.traceReq = JsonNullable.<TraceData>of(traceReq);
    }

    public SmPolicyContextData sliceInfo(Snssai sliceInfo)
    {

        this.sliceInfo = sliceInfo;
        return this;
    }

    /**
     * Get sliceInfo
     * 
     * @return sliceInfo
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_SLICE_INFO)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Snssai getSliceInfo()
    {
        return sliceInfo;
    }

    @JsonProperty(JSON_PROPERTY_SLICE_INFO)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSliceInfo(Snssai sliceInfo)
    {
        this.sliceInfo = sliceInfo;
    }

    public SmPolicyContextData qosFlowUsage(String qosFlowUsage)
    {

        this.qosFlowUsage = qosFlowUsage;
        return this;
    }

    /**
     * Possible values are - GENERAL: Indicate no specific QoS flow usage
     * information is available. - IMS_SIG: Indicate that the QoS flow is used for
     * IMS signalling only.
     * 
     * @return qosFlowUsage
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Possible values are - GENERAL: Indicate no specific QoS flow usage information is available.  - IMS_SIG: Indicate that the QoS flow is used for IMS signalling only. ")
    @JsonProperty(JSON_PROPERTY_QOS_FLOW_USAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getQosFlowUsage()
    {
        return qosFlowUsage;
    }

    @JsonProperty(JSON_PROPERTY_QOS_FLOW_USAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setQosFlowUsage(String qosFlowUsage)
    {
        this.qosFlowUsage = qosFlowUsage;
    }

    public SmPolicyContextData servNfId(ServingNfIdentity servNfId)
    {

        this.servNfId = servNfId;
        return this;
    }

    /**
     * Get servNfId
     * 
     * @return servNfId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SERV_NF_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ServingNfIdentity getServNfId()
    {
        return servNfId;
    }

    @JsonProperty(JSON_PROPERTY_SERV_NF_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setServNfId(ServingNfIdentity servNfId)
    {
        this.servNfId = servNfId;
    }

    public SmPolicyContextData suppFeat(String suppFeat)
    {

        this.suppFeat = suppFeat;
        return this;
    }

    /**
     * A string used to indicate the features supported by an API that is used as
     * defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask
     * indicating supported features in hexadecimal representation Each character in
     * the string shall take a value of \&quot;0\&quot; to \&quot;9\&quot;,
     * \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to \&quot;F\&quot; and
     * shall represent the support of 4 features as described in table 5.2.2-3. The
     * most significant character representing the highest-numbered features shall
     * appear first in the string, and the character representing features 1 to 4
     * shall appear last in the string. The list of features and their numbering
     * (starting with 1) are defined separately for each API. If the string contains
     * a lower number of characters than there are defined features for an API, all
     * features that would be represented by characters that are not present in the
     * string are not supported.
     * 
     * @return suppFeat
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. ")
    @JsonProperty(JSON_PROPERTY_SUPP_FEAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSuppFeat()
    {
        return suppFeat;
    }

    @JsonProperty(JSON_PROPERTY_SUPP_FEAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSuppFeat(String suppFeat)
    {
        this.suppFeat = suppFeat;
    }

    public SmPolicyContextData smfId(UUID smfId)
    {

        this.smfId = smfId;
        return this;
    }

    /**
     * String uniquely identifying a NF instance. The format of the NF Instance ID
     * shall be a Universally Unique Identifier (UUID) version 4, as described in
     * IETF RFC 4122.
     * 
     * @return smfId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  ")
    @JsonProperty(JSON_PROPERTY_SMF_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getSmfId()
    {
        return smfId;
    }

    @JsonProperty(JSON_PROPERTY_SMF_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSmfId(UUID smfId)
    {
        this.smfId = smfId;
    }

    public SmPolicyContextData recoveryTime(OffsetDateTime recoveryTime)
    {

        this.recoveryTime = recoveryTime;
        return this;
    }

    /**
     * string with format &#39;date-time&#39; as defined in OpenAPI.
     * 
     * @return recoveryTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "string with format 'date-time' as defined in OpenAPI.")
    @JsonProperty(JSON_PROPERTY_RECOVERY_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING)

    public OffsetDateTime getRecoveryTime()
    {
        return recoveryTime;
    }

    @JsonProperty(JSON_PROPERTY_RECOVERY_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRecoveryTime(OffsetDateTime recoveryTime)
    {
        this.recoveryTime = recoveryTime;
    }

    public SmPolicyContextData maPduInd(String maPduInd)
    {

        this.maPduInd = maPduInd;
        return this;
    }

    /**
     * Contains the MA PDU session indication, i.e., MA PDU Request or MA PDU
     * Network-Upgrade Allowed.
     * 
     * @return maPduInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Contains the MA PDU session indication, i.e., MA PDU Request or MA PDU Network-Upgrade Allowed.")
    @JsonProperty(JSON_PROPERTY_MA_PDU_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMaPduInd()
    {
        return maPduInd;
    }

    @JsonProperty(JSON_PROPERTY_MA_PDU_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaPduInd(String maPduInd)
    {
        this.maPduInd = maPduInd;
    }

    public SmPolicyContextData atsssCapab(String atsssCapab)
    {

        this.atsssCapab = atsssCapab;
        return this;
    }

    /**
     * Contains the ATSSS capability supported for the MA PDU Session.
     * 
     * @return atsssCapab
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Contains the ATSSS capability supported for the MA PDU Session.")
    @JsonProperty(JSON_PROPERTY_ATSSS_CAPAB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAtsssCapab()
    {
        return atsssCapab;
    }

    @JsonProperty(JSON_PROPERTY_ATSSS_CAPAB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAtsssCapab(String atsssCapab)
    {
        this.atsssCapab = atsssCapab;
    }

    public SmPolicyContextData ipv4FrameRouteList(List<String> ipv4FrameRouteList)
    {

        this.ipv4FrameRouteList = ipv4FrameRouteList;
        return this;
    }

    public SmPolicyContextData addIpv4FrameRouteListItem(String ipv4FrameRouteListItem)
    {
        if (this.ipv4FrameRouteList == null)
        {
            this.ipv4FrameRouteList = new ArrayList<>();
        }
        this.ipv4FrameRouteList.add(ipv4FrameRouteListItem);
        return this;
    }

    /**
     * Get ipv4FrameRouteList
     * 
     * @return ipv4FrameRouteList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_IPV4_FRAME_ROUTE_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getIpv4FrameRouteList()
    {
        return ipv4FrameRouteList;
    }

    @JsonProperty(JSON_PROPERTY_IPV4_FRAME_ROUTE_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIpv4FrameRouteList(List<String> ipv4FrameRouteList)
    {
        this.ipv4FrameRouteList = ipv4FrameRouteList;
    }

    public SmPolicyContextData ipv6FrameRouteList(List<String> ipv6FrameRouteList)
    {

        this.ipv6FrameRouteList = ipv6FrameRouteList;
        return this;
    }

    public SmPolicyContextData addIpv6FrameRouteListItem(String ipv6FrameRouteListItem)
    {
        if (this.ipv6FrameRouteList == null)
        {
            this.ipv6FrameRouteList = new ArrayList<>();
        }
        this.ipv6FrameRouteList.add(ipv6FrameRouteListItem);
        return this;
    }

    /**
     * Get ipv6FrameRouteList
     * 
     * @return ipv6FrameRouteList
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_IPV6_FRAME_ROUTE_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getIpv6FrameRouteList()
    {
        return ipv6FrameRouteList;
    }

    @JsonProperty(JSON_PROPERTY_IPV6_FRAME_ROUTE_LIST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIpv6FrameRouteList(List<String> ipv6FrameRouteList)
    {
        this.ipv6FrameRouteList = ipv6FrameRouteList;
    }

    public SmPolicyContextData satBackhaulCategory(String satBackhaulCategory)
    {

        this.satBackhaulCategory = satBackhaulCategory;
        return this;
    }

    /**
     * Indicates the satellite backhaul used.
     * 
     * @return satBackhaulCategory
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates the satellite backhaul used.")
    @JsonProperty(JSON_PROPERTY_SAT_BACKHAUL_CATEGORY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSatBackhaulCategory()
    {
        return satBackhaulCategory;
    }

    @JsonProperty(JSON_PROPERTY_SAT_BACKHAUL_CATEGORY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSatBackhaulCategory(String satBackhaulCategory)
    {
        this.satBackhaulCategory = satBackhaulCategory;
    }

    public SmPolicyContextData pcfUeInfo(PcfUeCallbackInfo pcfUeInfo)
    {
        this.pcfUeInfo = JsonNullable.<PcfUeCallbackInfo>of(pcfUeInfo);

        return this;
    }

    /**
     * Get pcfUeInfo
     * 
     * @return pcfUeInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonIgnore

    public PcfUeCallbackInfo getPcfUeInfo()
    {
        return pcfUeInfo.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_PCF_UE_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<PcfUeCallbackInfo> getPcfUeInfo_JsonNullable()
    {
        return pcfUeInfo;
    }

    @JsonProperty(JSON_PROPERTY_PCF_UE_INFO)
    public void setPcfUeInfo_JsonNullable(JsonNullable<PcfUeCallbackInfo> pcfUeInfo)
    {
        this.pcfUeInfo = pcfUeInfo;
    }

    public void setPcfUeInfo(PcfUeCallbackInfo pcfUeInfo)
    {
        this.pcfUeInfo = JsonNullable.<PcfUeCallbackInfo>of(pcfUeInfo);
    }

    public SmPolicyContextData pvsInfo(List<ServerAddressingInfo> pvsInfo)
    {

        this.pvsInfo = pvsInfo;
        return this;
    }

    public SmPolicyContextData addPvsInfoItem(ServerAddressingInfo pvsInfoItem)
    {
        if (this.pvsInfo == null)
        {
            this.pvsInfo = new ArrayList<>();
        }
        this.pvsInfo.add(pvsInfoItem);
        return this;
    }

    /**
     * Get pvsInfo
     * 
     * @return pvsInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_PVS_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ServerAddressingInfo> getPvsInfo()
    {
        return pvsInfo;
    }

    @JsonProperty(JSON_PROPERTY_PVS_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPvsInfo(List<ServerAddressingInfo> pvsInfo)
    {
        this.pvsInfo = pvsInfo;
    }

    public SmPolicyContextData onboardInd(Boolean onboardInd)
    {

        this.onboardInd = onboardInd;
        return this;
    }

    /**
     * If it is included and set to true, it indicates that the PDU session is used
     * for UE Onboarding.
     * 
     * @return onboardInd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "If it is included and set to true, it indicates that the PDU session is used for UE Onboarding.")
    @JsonProperty(JSON_PROPERTY_ONBOARD_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getOnboardInd()
    {
        return onboardInd;
    }

    @JsonProperty(JSON_PROPERTY_ONBOARD_IND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOnboardInd(Boolean onboardInd)
    {
        this.onboardInd = onboardInd;
    }

    public SmPolicyContextData nwdafDatas(List<NwdafData> nwdafDatas)
    {

        this.nwdafDatas = nwdafDatas;
        return this;
    }

    public SmPolicyContextData addNwdafDatasItem(NwdafData nwdafDatasItem)
    {
        if (this.nwdafDatas == null)
        {
            this.nwdafDatas = new ArrayList<>();
        }
        this.nwdafDatas.add(nwdafDatasItem);
        return this;
    }

    /**
     * Get nwdafDatas
     * 
     * @return nwdafDatas
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_NWDAF_DATAS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<NwdafData> getNwdafDatas()
    {
        return nwdafDatas;
    }

    @JsonProperty(JSON_PROPERTY_NWDAF_DATAS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNwdafDatas(List<NwdafData> nwdafDatas)
    {
        this.nwdafDatas = nwdafDatas;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        SmPolicyContextData smPolicyContextData = (SmPolicyContextData) o;
        return Objects.equals(this.accNetChId, smPolicyContextData.accNetChId) && Objects.equals(this.chargEntityAddr, smPolicyContextData.chargEntityAddr)
               && Objects.equals(this.gpsi, smPolicyContextData.gpsi) && Objects.equals(this.supi, smPolicyContextData.supi)
               && Objects.equals(this.invalidSupi, smPolicyContextData.invalidSupi) && Objects.equals(this.interGrpIds, smPolicyContextData.interGrpIds)
               && Objects.equals(this.pduSessionId, smPolicyContextData.pduSessionId) && Objects.equals(this.pduSessionType, smPolicyContextData.pduSessionType)
               && Objects.equals(this.chargingcharacteristics, smPolicyContextData.chargingcharacteristics) && Objects.equals(this.dnn, smPolicyContextData.dnn)
               && Objects.equals(this.dnnSelMode, smPolicyContextData.dnnSelMode) && Objects.equals(this.notificationUri, smPolicyContextData.notificationUri)
               && Objects.equals(this.accessType, smPolicyContextData.accessType) && Objects.equals(this.ratType, smPolicyContextData.ratType)
               && Objects.equals(this.addAccessInfo, smPolicyContextData.addAccessInfo)
               && Objects.equals(this.servingNetwork, smPolicyContextData.servingNetwork)
               && Objects.equals(this.userLocationInfo, smPolicyContextData.userLocationInfo) && Objects.equals(this.ueTimeZone, smPolicyContextData.ueTimeZone)
               && Objects.equals(this.pei, smPolicyContextData.pei) && Objects.equals(this.ipv4Address, smPolicyContextData.ipv4Address)
               && Objects.equals(this.ipv6AddressPrefix, smPolicyContextData.ipv6AddressPrefix) && Objects.equals(this.ipDomain, smPolicyContextData.ipDomain)
               && Objects.equals(this.subsSessAmbr, smPolicyContextData.subsSessAmbr) && Objects.equals(this.authProfIndex, smPolicyContextData.authProfIndex)
               && Objects.equals(this.subsDefQos, smPolicyContextData.subsDefQos) && Objects.equals(this.vplmnQos, smPolicyContextData.vplmnQos)
               && Objects.equals(this.numOfPackFilter, smPolicyContextData.numOfPackFilter) && Objects.equals(this.online, smPolicyContextData.online)
               && Objects.equals(this.offline, smPolicyContextData.offline)
               && Objects.equals(this._3gppPsDataOffStatus, smPolicyContextData._3gppPsDataOffStatus)
               && Objects.equals(this.refQosIndication, smPolicyContextData.refQosIndication) && equalsNullable(this.traceReq, smPolicyContextData.traceReq)
               && Objects.equals(this.sliceInfo, smPolicyContextData.sliceInfo) && Objects.equals(this.qosFlowUsage, smPolicyContextData.qosFlowUsage)
               && Objects.equals(this.servNfId, smPolicyContextData.servNfId) && Objects.equals(this.suppFeat, smPolicyContextData.suppFeat)
               && Objects.equals(this.smfId, smPolicyContextData.smfId) && Objects.equals(this.recoveryTime, smPolicyContextData.recoveryTime)
               && Objects.equals(this.maPduInd, smPolicyContextData.maPduInd) && Objects.equals(this.atsssCapab, smPolicyContextData.atsssCapab)
               && Objects.equals(this.ipv4FrameRouteList, smPolicyContextData.ipv4FrameRouteList)
               && Objects.equals(this.ipv6FrameRouteList, smPolicyContextData.ipv6FrameRouteList)
               && Objects.equals(this.satBackhaulCategory, smPolicyContextData.satBackhaulCategory)
               && equalsNullable(this.pcfUeInfo, smPolicyContextData.pcfUeInfo) && Objects.equals(this.pvsInfo, smPolicyContextData.pvsInfo)
               && Objects.equals(this.onboardInd, smPolicyContextData.onboardInd) && Objects.equals(this.nwdafDatas, smPolicyContextData.nwdafDatas);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a,
                                              JsonNullable<T> b)
    {
        return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(accNetChId,
                            chargEntityAddr,
                            gpsi,
                            supi,
                            invalidSupi,
                            interGrpIds,
                            pduSessionId,
                            pduSessionType,
                            chargingcharacteristics,
                            dnn,
                            dnnSelMode,
                            notificationUri,
                            accessType,
                            ratType,
                            addAccessInfo,
                            servingNetwork,
                            userLocationInfo,
                            ueTimeZone,
                            pei,
                            ipv4Address,
                            ipv6AddressPrefix,
                            ipDomain,
                            subsSessAmbr,
                            authProfIndex,
                            subsDefQos,
                            vplmnQos,
                            numOfPackFilter,
                            online,
                            offline,
                            _3gppPsDataOffStatus,
                            refQosIndication,
                            hashCodeNullable(traceReq),
                            sliceInfo,
                            qosFlowUsage,
                            servNfId,
                            suppFeat,
                            smfId,
                            recoveryTime,
                            maPduInd,
                            atsssCapab,
                            ipv4FrameRouteList,
                            ipv6FrameRouteList,
                            satBackhaulCategory,
                            hashCodeNullable(pcfUeInfo),
                            pvsInfo,
                            onboardInd,
                            nwdafDatas);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a)
    {
        if (a == null)
        {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] { a.get() }) : 31;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class SmPolicyContextData {\n");
        sb.append("    accNetChId: ").append(toIndentedString(accNetChId)).append("\n");
        sb.append("    chargEntityAddr: ").append(toIndentedString(chargEntityAddr)).append("\n");
        sb.append("    gpsi: ").append(toIndentedString(gpsi)).append("\n");
        sb.append("    supi: ").append(toIndentedString(supi)).append("\n");
        sb.append("    invalidSupi: ").append(toIndentedString(invalidSupi)).append("\n");
        sb.append("    interGrpIds: ").append(toIndentedString(interGrpIds)).append("\n");
        sb.append("    pduSessionId: ").append(toIndentedString(pduSessionId)).append("\n");
        sb.append("    pduSessionType: ").append(toIndentedString(pduSessionType)).append("\n");
        sb.append("    chargingcharacteristics: ").append(toIndentedString(chargingcharacteristics)).append("\n");
        sb.append("    dnn: ").append(toIndentedString(dnn)).append("\n");
        sb.append("    dnnSelMode: ").append(toIndentedString(dnnSelMode)).append("\n");
        sb.append("    notificationUri: ").append(toIndentedString(notificationUri)).append("\n");
        sb.append("    accessType: ").append(toIndentedString(accessType)).append("\n");
        sb.append("    ratType: ").append(toIndentedString(ratType)).append("\n");
        sb.append("    addAccessInfo: ").append(toIndentedString(addAccessInfo)).append("\n");
        sb.append("    servingNetwork: ").append(toIndentedString(servingNetwork)).append("\n");
        sb.append("    userLocationInfo: ").append(toIndentedString(userLocationInfo)).append("\n");
        sb.append("    ueTimeZone: ").append(toIndentedString(ueTimeZone)).append("\n");
        sb.append("    pei: ").append(toIndentedString(pei)).append("\n");
        sb.append("    ipv4Address: ").append(toIndentedString(ipv4Address)).append("\n");
        sb.append("    ipv6AddressPrefix: ").append(toIndentedString(ipv6AddressPrefix)).append("\n");
        sb.append("    ipDomain: ").append(toIndentedString(ipDomain)).append("\n");
        sb.append("    subsSessAmbr: ").append(toIndentedString(subsSessAmbr)).append("\n");
        sb.append("    authProfIndex: ").append(toIndentedString(authProfIndex)).append("\n");
        sb.append("    subsDefQos: ").append(toIndentedString(subsDefQos)).append("\n");
        sb.append("    vplmnQos: ").append(toIndentedString(vplmnQos)).append("\n");
        sb.append("    numOfPackFilter: ").append(toIndentedString(numOfPackFilter)).append("\n");
        sb.append("    online: ").append(toIndentedString(online)).append("\n");
        sb.append("    offline: ").append(toIndentedString(offline)).append("\n");
        sb.append("    _3gppPsDataOffStatus: ").append(toIndentedString(_3gppPsDataOffStatus)).append("\n");
        sb.append("    refQosIndication: ").append(toIndentedString(refQosIndication)).append("\n");
        sb.append("    traceReq: ").append(toIndentedString(traceReq)).append("\n");
        sb.append("    sliceInfo: ").append(toIndentedString(sliceInfo)).append("\n");
        sb.append("    qosFlowUsage: ").append(toIndentedString(qosFlowUsage)).append("\n");
        sb.append("    servNfId: ").append(toIndentedString(servNfId)).append("\n");
        sb.append("    suppFeat: ").append(toIndentedString(suppFeat)).append("\n");
        sb.append("    smfId: ").append(toIndentedString(smfId)).append("\n");
        sb.append("    recoveryTime: ").append(toIndentedString(recoveryTime)).append("\n");
        sb.append("    maPduInd: ").append(toIndentedString(maPduInd)).append("\n");
        sb.append("    atsssCapab: ").append(toIndentedString(atsssCapab)).append("\n");
        sb.append("    ipv4FrameRouteList: ").append(toIndentedString(ipv4FrameRouteList)).append("\n");
        sb.append("    ipv6FrameRouteList: ").append(toIndentedString(ipv6FrameRouteList)).append("\n");
        sb.append("    satBackhaulCategory: ").append(toIndentedString(satBackhaulCategory)).append("\n");
        sb.append("    pcfUeInfo: ").append(toIndentedString(pcfUeInfo)).append("\n");
        sb.append("    pvsInfo: ").append(toIndentedString(pvsInfo)).append("\n");
        sb.append("    onboardInd: ").append(toIndentedString(onboardInd)).append("\n");
        sb.append("    nwdafDatas: ").append(toIndentedString(nwdafDatas)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
