/*
 * Nnwdaf_EventsSubscription
 * 
 *
 * OpenAPI spec version: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 * 
 * This file has been auto-generated by the yaml2java script.
 */

package com.ericsson.cnal.openapi.r17.ts29520.nnwdaf.eventssubscription;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AnalyticsMetadata
 */
public class AnalyticsMetadata
{
    public static final String NUM_OF_SAMPLES = "NUM_OF_SAMPLES";
    public static final String DATA_WINDOW = "DATA_WINDOW";
    public static final String DATA_STAT_PROPS = "DATA_STAT_PROPS";
    public static final String STRATEGY = "STRATEGY";
    public static final String ACCURACY = "ACCURACY";

}
