/*
 * Nnwdaf_EventsSubscription
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29520.nnwdaf.eventssubscription;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Represents DN performance data.
 */
@ApiModel(description = "Represents DN performance data.")
@JsonPropertyOrder({ PerfData.JSON_PROPERTY_AVG_TRAFFIC_RATE,
                     PerfData.JSON_PROPERTY_MAX_TRAFFIC_RATE,
                     PerfData.JSON_PROPERTY_AVE_PACKET_DELAY,
                     PerfData.JSON_PROPERTY_MAX_PACKET_DELAY,
                     PerfData.JSON_PROPERTY_AVG_PACKET_LOSS_RATE })
public class PerfData
{
    public static final String JSON_PROPERTY_AVG_TRAFFIC_RATE = "avgTrafficRate";
    private String avgTrafficRate;

    public static final String JSON_PROPERTY_MAX_TRAFFIC_RATE = "maxTrafficRate";
    private String maxTrafficRate;

    public static final String JSON_PROPERTY_AVE_PACKET_DELAY = "avePacketDelay";
    private Integer avePacketDelay;

    public static final String JSON_PROPERTY_MAX_PACKET_DELAY = "maxPacketDelay";
    private Integer maxPacketDelay;

    public static final String JSON_PROPERTY_AVG_PACKET_LOSS_RATE = "avgPacketLossRate";
    private Integer avgPacketLossRate;

    public PerfData()
    {
    }

    public PerfData avgTrafficRate(String avgTrafficRate)
    {

        this.avgTrafficRate = avgTrafficRate;
        return this;
    }

    /**
     * String representing a bit rate; the prefixes follow the standard symbols from
     * The International System of Units, and represent x1000 multipliers, with the
     * exception that prefix \&quot;K\&quot; is used to represent the standard
     * symbol \&quot;k\&quot;.
     * 
     * @return avgTrafficRate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ")
    @JsonProperty(JSON_PROPERTY_AVG_TRAFFIC_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAvgTrafficRate()
    {
        return avgTrafficRate;
    }

    @JsonProperty(JSON_PROPERTY_AVG_TRAFFIC_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAvgTrafficRate(String avgTrafficRate)
    {
        this.avgTrafficRate = avgTrafficRate;
    }

    public PerfData maxTrafficRate(String maxTrafficRate)
    {

        this.maxTrafficRate = maxTrafficRate;
        return this;
    }

    /**
     * String representing a bit rate; the prefixes follow the standard symbols from
     * The International System of Units, and represent x1000 multipliers, with the
     * exception that prefix \&quot;K\&quot; is used to represent the standard
     * symbol \&quot;k\&quot;.
     * 
     * @return maxTrafficRate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ")
    @JsonProperty(JSON_PROPERTY_MAX_TRAFFIC_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMaxTrafficRate()
    {
        return maxTrafficRate;
    }

    @JsonProperty(JSON_PROPERTY_MAX_TRAFFIC_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxTrafficRate(String maxTrafficRate)
    {
        this.maxTrafficRate = maxTrafficRate;
    }

    public PerfData avePacketDelay(Integer avePacketDelay)
    {

        this.avePacketDelay = avePacketDelay;
        return this;
    }

    /**
     * Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and
     * 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. minimum: 1
     * 
     * @return avePacketDelay
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. ")
    @JsonProperty(JSON_PROPERTY_AVE_PACKET_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getAvePacketDelay()
    {
        return avePacketDelay;
    }

    @JsonProperty(JSON_PROPERTY_AVE_PACKET_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAvePacketDelay(Integer avePacketDelay)
    {
        this.avePacketDelay = avePacketDelay;
    }

    public PerfData maxPacketDelay(Integer maxPacketDelay)
    {

        this.maxPacketDelay = maxPacketDelay;
        return this;
    }

    /**
     * Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and
     * 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. minimum: 1
     * 
     * @return maxPacketDelay
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. ")
    @JsonProperty(JSON_PROPERTY_MAX_PACKET_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getMaxPacketDelay()
    {
        return maxPacketDelay;
    }

    @JsonProperty(JSON_PROPERTY_MAX_PACKET_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxPacketDelay(Integer maxPacketDelay)
    {
        this.maxPacketDelay = maxPacketDelay;
    }

    public PerfData avgPacketLossRate(Integer avgPacketLossRate)
    {

        this.avgPacketLossRate = avgPacketLossRate;
        return this;
    }

    /**
     * Unsigned integer indicating Packet Loss Rate (see clauses 5.7.2.8 and 5.7.4
     * of 3GPP TS 23.501), expressed in tenth of percent. minimum: 0 maximum: 1000
     * 
     * @return avgPacketLossRate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Unsigned integer indicating Packet Loss Rate (see clauses 5.7.2.8 and 5.7.4 of 3GPP TS 23.501), expressed in tenth of percent. ")
    @JsonProperty(JSON_PROPERTY_AVG_PACKET_LOSS_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getAvgPacketLossRate()
    {
        return avgPacketLossRate;
    }

    @JsonProperty(JSON_PROPERTY_AVG_PACKET_LOSS_RATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAvgPacketLossRate(Integer avgPacketLossRate)
    {
        this.avgPacketLossRate = avgPacketLossRate;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        PerfData perfData = (PerfData) o;
        return Objects.equals(this.avgTrafficRate, perfData.avgTrafficRate) && Objects.equals(this.maxTrafficRate, perfData.maxTrafficRate)
               && Objects.equals(this.avePacketDelay, perfData.avePacketDelay) && Objects.equals(this.maxPacketDelay, perfData.maxPacketDelay)
               && Objects.equals(this.avgPacketLossRate, perfData.avgPacketLossRate);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(avgTrafficRate, maxTrafficRate, avePacketDelay, maxPacketDelay, avgPacketLossRate);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class PerfData {\n");
        sb.append("    avgTrafficRate: ").append(toIndentedString(avgTrafficRate)).append("\n");
        sb.append("    maxTrafficRate: ").append(toIndentedString(maxTrafficRate)).append("\n");
        sb.append("    avePacketDelay: ").append(toIndentedString(avePacketDelay)).append("\n");
        sb.append("    maxPacketDelay: ").append(toIndentedString(maxPacketDelay)).append("\n");
        sb.append("    avgPacketLossRate: ").append(toIndentedString(avgPacketLossRate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
