# Copyright 2019 Ericsson GmbH
{{- if eq (include "eric-scp.tls" .) "true" }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-scp.name" . }}-manager-grpc-server-certificate
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
    app: {{ template "eric-scp.name" . }}-manager
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-scp.name" . }}-manager-grpc-server-certificate
    certificateName: tls.crt
    privateKeyName: tls.key
  certificate:
    subject:
      cn: {{ template "eric-scp.name" . }}-manager-grpc
    subjectAlternativeName:
      dns:
        - certified-scrape-target
    extendedKeyUsage:
      tlsClientAuth: false
      tlsServerAuth: true
{{- end }}

