apiVersion:  certm.sec.ericsson.com/v1 
kind: ExternalCertificate
metadata:
  name: {{ template "eric-scp.name" . }}-manager-nrf-ca-certificate
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
    app: {{ template "eric-scp.name" . }}-manager
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
spec:
  generated-secret-name: {{ template "eric-scp.name" . }}-manager-nrf-ca-certificate
  generated-secret-type: opaque
  trusted-certificates-file-name: "cert1.pem"
  trusted-certificate-list-name: {{ index .Values "certificates" "nrf" "caCertificate" | quote }}