apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-scp.name" . }}-rr
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
data:
  {{ template "eric-scp.name" . }}-rr.yml: |
{{- include "eric-scp.recording-rules" . | indent 4 }}
