{{- $key := index .Values "certificates" "traf" "key" }}
{{- $certificate := index .Values "certificates" "traf" "certificate" }}
apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata: 
  name: {{ template "eric-scp.name" . }}-worker-scp-server-certificate
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
    app: {{ template "eric-scp.name" . }}-worker
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
spec: 
  generated-secret-name: {{ template "eric-scp.name" . }}-worker-scp-server-certificate
  generated-secret-type: tls
  asymmetric-key-certificate-name:  {{ printf "%s/%s" $key $certificate | quote }}
