{{- if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-scp.name" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
    app: {{ template "eric-scp.name" . }}-worker
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "eric-scp.name" . }}-worker
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "eric-scp.name" . }}-worker
  apiGroup: rbac.authorization.k8s.io
{{- end }}