apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-scp.name" . }}-worker-loglevel-config
  labels:
{{- include "eric-scp.labels" . | indent 4 }}
    app: {{ template "eric-scp.name" . }}-worker
  annotations:
{{- include "eric-scp.helm-annotations" . | indent 4 }}
{{- include "eric-scp.config-annotations" . | indent 4 }}
data:
  logcontrol.json: |-
    [
        {
          "container": "eric-scp-cert-notifier",
          "severity": {{ .Values.log.certnotifier.level | quote }}
        },
        {
          "container": "eric-scp-sds",
          "severity": {{ .Values.log.sds.level | quote }}
        }{{- if eq (include "eric-scp.tapcollector.worker.enabled" .) "true" }},
        {
          "container": "tapcollector",
          "severity": {{ .Values.log.tapcollector.level | quote }}
        }{{- end }}{{- if eq (include "eric-scp.tapagent.worker.enabled" .) "true" }},
        {
          "container": "tlskeylogagent",
          "severity": {{ .Values.log.tlskeylogagent.level | quote }}
        }{{- end }}
    ]
