apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-sc-scp.name" . }}-hcagent-severities
  labels:
{{- include "eric-sc-scp.labels" . | indent 4 }}
    app: {{ template "eric-sc-scp.name" . }}
  annotations:
{{- include "eric-sc-scp.common-annotations" . | indent 4 }}
data:
  {{ template "eric-sc-scp.name" . }}-severities.json: |
{{ .Values.severities | toPrettyJson | indent 4 }}
