replicaCount:
  ingest: 1
  master: 1
  data: 1

persistence:
  data:
    persistentVolumeClaim:
      storageClassName: network-block
  master:
    persistentVolumeClaim:
      storageClassName: network-block

service:
  endpoints:
    internode:
      tls:
        verifyClientHostname: false
    rest:
      tls:
        enforce: optional
        verifyClientCertificate: optional
        verifyClientHostname: false

metrics:
  enabled: false
