{{- if .Values.rbac.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.rlf.name }}
  labels:
{{- include "eric-sc-rlf.labels" . | indent 4 }}
    app: {{ .Values.service.rlf.name }} 
  annotations:
{{- include "eric-sc-rlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-rlf.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
