{{- if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.service.rlf.name }}-{{ .Release.Namespace }}
  labels:
{{- include "eric-sc-rlf.labels" . | indent 4 }}
    app: {{ .Values.service.rlf.name }}
  annotations:
{{- include "eric-sc-rlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-rlf.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
#    - watch
#    - create
#    - update
    - patch
{{- end }}
