apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nighthawk
spec:
  selector:
    matchLabels:
      app: nighthawk
  replicas: 1
  template:
    metadata:
      labels:
        app: nighthawk
    spec:
      containers:
      - name: nighthawk
        image: envoyproxy/nighthawk-dev
        command:
        - tail
        - -f 
        - /dev/null
        ports:
        - containerPort: 80
