productName: "NF Lookup Function (eric-sc-nlf)"
productNumber: product_number
productRevision: product_revision
images:
  nlf:
    productName: "NLF"
    productNumber: "-"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-5g-bsf/eiffelesc"
    name: nlf_image_name
    tag: nlf_image_tag
  tapagent:
    productName: "NLF TAP agent"
    productNumber: "-"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-5g-bsf/eiffelesc"
    name: tap_agent_image_name
    tag: tap_agent_image_tag
  tlskeylogagent:
    productName: "SCPNLFTLS Keylog Agent"
    productNumber: "-"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: "proj-5g-bsf/eiffelesc"
    name: tlskeylogagent_image_name
    tag: tlskeylogagent_image_tag