productName: "Rate Limiting Function (eric-sc-rlf)"
productNumber: "CXC 174 4290"
images:
  rlf:
    productName: "RLF"
    productNumber: "-"
    registry: "armdocker.rnd.ericsson.se"
    repoPath: rlf_repo_path
    name: rlf_image_name
    tag: rlf_image_tag