# Copyright 2019 Ericsson GmbH
{{- if and (eq (include "eric-sc-rlf.tls" .) "true") (eq (include "eric-sc-rlf.dcedsc.tls" .) "true") }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-sc-rlf.name" . }}-dcedsc-client-certificate
  labels:
{{- include "eric-sc-rlf.labels" . | indent 4 }}
    app: {{ template "eric-sc-rlf.name" . }}
  annotations:
{{- include "eric-sc-rlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-rlf.config-annotations" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-sc-rlf.name" . }}-dcedsc-client-certificate
  certificate:
    subject:
      cn: root
    issuer:
      reference: {{ .Values.sc.common.etcd.hostname }}-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}
