apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-sc-rlf.name" . }}-loglevel-config
  labels:
{{- include "eric-sc-rlf.labels" . | indent 4 }}
    app: {{ template "eric-sc-rlf.name" . }}
  annotations:
{{- include "eric-sc-rlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-rlf.config-annotations" . | indent 4 }}
data:
  logcontrol.json: |-
    [
        {
          "container": "eric-sc-rlf",
          "severity": {{ .Values.log.rlf.level | quote }}
        }
    ]
