# Copyright 2022 Ericsson GmbH

apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-sc-rlf.name" . }}-mediator-client-certificate
  annotations:
{{- include "eric-sc-rlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-rlf.config-annotations" . | indent 4 }}
  labels:
{{- include "eric-sc-rlf.labels" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-sc-rlf.name" . }}-mediator-client-certificate
    certificateName: tls.crt
    privateKeyName: tls.key
  certificate:
    subject:
      cn: {{ template "eric-sc-rlf.name" . }}
    issuer:
      reference: {{ .Values.adp.cm.mediator.hostname }}-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false