{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-sc-rlf.name" . }}-default-access
  labels:
{{- include "eric-sc-rlf.labels" . | indent 4 }}
    app: {{ template "eric-sc-rlf.name" . }}
  annotations:
{{- include "eric-sc-rlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-rlf.config-annotations" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-sc-rlf.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          eric-sc-rlf-access: "true"
    ports:
    - port: {{ .Values.spec.rlf.portNameRestOam }}
      protocol: TCP
    - port: {{ .Values.spec.rlf.portNameRest }}
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}