{{- if .Values.rbac.createServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-sc-rlf.name" . }}
  labels:
{{- include "eric-sc-rlf.labels" . | indent 4 }}
    app: {{ template "eric-sc-rlf.name" . }}
  annotations:
{{- include "eric-sc-rlf.helm-annotations" . | indent 4 }}
{{- include "eric-sc-rlf.config-annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "eric-sc-rlf.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "eric-sc-rlf.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
