/*
 * Npcf_EventExposure
 * PCF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ericsson.cnal.openapi.r17.ts29523.npcf.eventexposure;

import java.util.Objects;
import java.util.Arrays;
import com.ericsson.cnal.openapi.r17.ts29571.commondata.Snssai;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Represents an Individual Policy Events Subscription resource.
 */
@ApiModel(description = "Represents an Individual Policy Events Subscription resource.")
@JsonPropertyOrder({ PcEventExposureSubsc.JSON_PROPERTY_EVENT_SUBS,
                     PcEventExposureSubsc.JSON_PROPERTY_EVENTS_REP_INFO,
                     PcEventExposureSubsc.JSON_PROPERTY_GROUP_ID,
                     PcEventExposureSubsc.JSON_PROPERTY_FILTER_DNNS,
                     PcEventExposureSubsc.JSON_PROPERTY_FILTER_SNSSAIS,
                     PcEventExposureSubsc.JSON_PROPERTY_SNSSAI_DNNS,
                     PcEventExposureSubsc.JSON_PROPERTY_FILTER_SERVICES,
                     PcEventExposureSubsc.JSON_PROPERTY_NOTIF_URI,
                     PcEventExposureSubsc.JSON_PROPERTY_NOTIF_ID,
                     PcEventExposureSubsc.JSON_PROPERTY_EVENT_NOTIFS,
                     PcEventExposureSubsc.JSON_PROPERTY_SUPP_FEAT })
public class PcEventExposureSubsc
{
    public static final String JSON_PROPERTY_EVENT_SUBS = "eventSubs";
    private List<String> eventSubs = new ArrayList<>();

    public static final String JSON_PROPERTY_EVENTS_REP_INFO = "eventsRepInfo";
    private ReportingInformation eventsRepInfo;

    public static final String JSON_PROPERTY_GROUP_ID = "groupId";
    private String groupId;

    public static final String JSON_PROPERTY_FILTER_DNNS = "filterDnns";
    private List<String> filterDnns = null;

    public static final String JSON_PROPERTY_FILTER_SNSSAIS = "filterSnssais";
    private List<Snssai> filterSnssais = null;

    public static final String JSON_PROPERTY_SNSSAI_DNNS = "snssaiDnns";
    private List<SnssaiDnnCombination> snssaiDnns = null;

    public static final String JSON_PROPERTY_FILTER_SERVICES = "filterServices";
    private List<ServiceIdentification> filterServices = null;

    public static final String JSON_PROPERTY_NOTIF_URI = "notifUri";
    private String notifUri;

    public static final String JSON_PROPERTY_NOTIF_ID = "notifId";
    private String notifId;

    public static final String JSON_PROPERTY_EVENT_NOTIFS = "eventNotifs";
    private List<PcEventNotification> eventNotifs = null;

    public static final String JSON_PROPERTY_SUPP_FEAT = "suppFeat";
    private String suppFeat;

    public PcEventExposureSubsc()
    {
    }

    public PcEventExposureSubsc eventSubs(List<String> eventSubs)
    {

        this.eventSubs = eventSubs;
        return this;
    }

    public PcEventExposureSubsc addEventSubsItem(String eventSubsItem)
    {
        this.eventSubs.add(eventSubsItem);
        return this;
    }

    /**
     * Get eventSubs
     * 
     * @return eventSubs
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_EVENT_SUBS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<String> getEventSubs()
    {
        return eventSubs;
    }

    @JsonProperty(JSON_PROPERTY_EVENT_SUBS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setEventSubs(List<String> eventSubs)
    {
        this.eventSubs = eventSubs;
    }

    public PcEventExposureSubsc eventsRepInfo(ReportingInformation eventsRepInfo)
    {

        this.eventsRepInfo = eventsRepInfo;
        return this;
    }

    /**
     * Get eventsRepInfo
     * 
     * @return eventsRepInfo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_EVENTS_REP_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ReportingInformation getEventsRepInfo()
    {
        return eventsRepInfo;
    }

    @JsonProperty(JSON_PROPERTY_EVENTS_REP_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEventsRepInfo(ReportingInformation eventsRepInfo)
    {
        this.eventsRepInfo = eventsRepInfo;
    }

    public PcEventExposureSubsc groupId(String groupId)
    {

        this.groupId = groupId;
        return this;
    }

    /**
     * String identifying a group of devices network internal globally unique ID
     * which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS
     * 23.003.
     * 
     * @return groupId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String identifying a group of devices network internal globally unique ID which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS 23.003.  ")
    @JsonProperty(JSON_PROPERTY_GROUP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getGroupId()
    {
        return groupId;
    }

    @JsonProperty(JSON_PROPERTY_GROUP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGroupId(String groupId)
    {
        this.groupId = groupId;
    }

    public PcEventExposureSubsc filterDnns(List<String> filterDnns)
    {

        this.filterDnns = filterDnns;
        return this;
    }

    public PcEventExposureSubsc addFilterDnnsItem(String filterDnnsItem)
    {
        if (this.filterDnns == null)
        {
            this.filterDnns = new ArrayList<>();
        }
        this.filterDnns.add(filterDnnsItem);
        return this;
    }

    /**
     * Get filterDnns
     * 
     * @return filterDnns
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_FILTER_DNNS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getFilterDnns()
    {
        return filterDnns;
    }

    @JsonProperty(JSON_PROPERTY_FILTER_DNNS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFilterDnns(List<String> filterDnns)
    {
        this.filterDnns = filterDnns;
    }

    public PcEventExposureSubsc filterSnssais(List<Snssai> filterSnssais)
    {

        this.filterSnssais = filterSnssais;
        return this;
    }

    public PcEventExposureSubsc addFilterSnssaisItem(Snssai filterSnssaisItem)
    {
        if (this.filterSnssais == null)
        {
            this.filterSnssais = new ArrayList<>();
        }
        this.filterSnssais.add(filterSnssaisItem);
        return this;
    }

    /**
     * Get filterSnssais
     * 
     * @return filterSnssais
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_FILTER_SNSSAIS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Snssai> getFilterSnssais()
    {
        return filterSnssais;
    }

    @JsonProperty(JSON_PROPERTY_FILTER_SNSSAIS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFilterSnssais(List<Snssai> filterSnssais)
    {
        this.filterSnssais = filterSnssais;
    }

    public PcEventExposureSubsc snssaiDnns(List<SnssaiDnnCombination> snssaiDnns)
    {

        this.snssaiDnns = snssaiDnns;
        return this;
    }

    public PcEventExposureSubsc addSnssaiDnnsItem(SnssaiDnnCombination snssaiDnnsItem)
    {
        if (this.snssaiDnns == null)
        {
            this.snssaiDnns = new ArrayList<>();
        }
        this.snssaiDnns.add(snssaiDnnsItem);
        return this;
    }

    /**
     * Get snssaiDnns
     * 
     * @return snssaiDnns
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SNSSAI_DNNS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<SnssaiDnnCombination> getSnssaiDnns()
    {
        return snssaiDnns;
    }

    @JsonProperty(JSON_PROPERTY_SNSSAI_DNNS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSnssaiDnns(List<SnssaiDnnCombination> snssaiDnns)
    {
        this.snssaiDnns = snssaiDnns;
    }

    public PcEventExposureSubsc filterServices(List<ServiceIdentification> filterServices)
    {

        this.filterServices = filterServices;
        return this;
    }

    public PcEventExposureSubsc addFilterServicesItem(ServiceIdentification filterServicesItem)
    {
        if (this.filterServices == null)
        {
            this.filterServices = new ArrayList<>();
        }
        this.filterServices.add(filterServicesItem);
        return this;
    }

    /**
     * Get filterServices
     * 
     * @return filterServices
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_FILTER_SERVICES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ServiceIdentification> getFilterServices()
    {
        return filterServices;
    }

    @JsonProperty(JSON_PROPERTY_FILTER_SERVICES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFilterServices(List<ServiceIdentification> filterServices)
    {
        this.filterServices = filterServices;
    }

    public PcEventExposureSubsc notifUri(String notifUri)
    {

        this.notifUri = notifUri;
        return this;
    }

    /**
     * String providing an URI formatted according to RFC 3986.
     * 
     * @return notifUri
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "String providing an URI formatted according to RFC 3986.")
    @JsonProperty(JSON_PROPERTY_NOTIF_URI)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getNotifUri()
    {
        return notifUri;
    }

    @JsonProperty(JSON_PROPERTY_NOTIF_URI)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNotifUri(String notifUri)
    {
        this.notifUri = notifUri;
    }

    public PcEventExposureSubsc notifId(String notifId)
    {

        this.notifId = notifId;
        return this;
    }

    /**
     * Get notifId
     * 
     * @return notifId
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_NOTIF_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getNotifId()
    {
        return notifId;
    }

    @JsonProperty(JSON_PROPERTY_NOTIF_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNotifId(String notifId)
    {
        this.notifId = notifId;
    }

    public PcEventExposureSubsc eventNotifs(List<PcEventNotification> eventNotifs)
    {

        this.eventNotifs = eventNotifs;
        return this;
    }

    public PcEventExposureSubsc addEventNotifsItem(PcEventNotification eventNotifsItem)
    {
        if (this.eventNotifs == null)
        {
            this.eventNotifs = new ArrayList<>();
        }
        this.eventNotifs.add(eventNotifsItem);
        return this;
    }

    /**
     * Get eventNotifs
     * 
     * @return eventNotifs
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_EVENT_NOTIFS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<PcEventNotification> getEventNotifs()
    {
        return eventNotifs;
    }

    @JsonProperty(JSON_PROPERTY_EVENT_NOTIFS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEventNotifs(List<PcEventNotification> eventNotifs)
    {
        this.eventNotifs = eventNotifs;
    }

    public PcEventExposureSubsc suppFeat(String suppFeat)
    {

        this.suppFeat = suppFeat;
        return this;
    }

    /**
     * A string used to indicate the features supported by an API that is used as
     * defined in clause 6.6 in 3GPP TS 29.500. The string shall contain a bitmask
     * indicating supported features in hexadecimal representation Each character in
     * the string shall take a value of \&quot;0\&quot; to \&quot;9\&quot;,
     * \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to \&quot;F\&quot; and
     * shall represent the support of 4 features as described in table 5.2.2-3. The
     * most significant character representing the highest-numbered features shall
     * appear first in the string, and the character representing features 1 to 4
     * shall appear last in the string. The list of features and their numbering
     * (starting with 1) are defined separately for each API. If the string contains
     * a lower number of characters than there are defined features for an API, all
     * features that would be represented by characters that are not present in the
     * string are not supported.
     * 
     * @return suppFeat
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. ")
    @JsonProperty(JSON_PROPERTY_SUPP_FEAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSuppFeat()
    {
        return suppFeat;
    }

    @JsonProperty(JSON_PROPERTY_SUPP_FEAT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSuppFeat(String suppFeat)
    {
        this.suppFeat = suppFeat;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        PcEventExposureSubsc pcEventExposureSubsc = (PcEventExposureSubsc) o;
        return Objects.equals(this.eventSubs, pcEventExposureSubsc.eventSubs) && Objects.equals(this.eventsRepInfo, pcEventExposureSubsc.eventsRepInfo)
               && Objects.equals(this.groupId, pcEventExposureSubsc.groupId) && Objects.equals(this.filterDnns, pcEventExposureSubsc.filterDnns)
               && Objects.equals(this.filterSnssais, pcEventExposureSubsc.filterSnssais) && Objects.equals(this.snssaiDnns, pcEventExposureSubsc.snssaiDnns)
               && Objects.equals(this.filterServices, pcEventExposureSubsc.filterServices) && Objects.equals(this.notifUri, pcEventExposureSubsc.notifUri)
               && Objects.equals(this.notifId, pcEventExposureSubsc.notifId) && Objects.equals(this.eventNotifs, pcEventExposureSubsc.eventNotifs)
               && Objects.equals(this.suppFeat, pcEventExposureSubsc.suppFeat);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(eventSubs, eventsRepInfo, groupId, filterDnns, filterSnssais, snssaiDnns, filterServices, notifUri, notifId, eventNotifs, suppFeat);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class PcEventExposureSubsc {\n");
        sb.append("    eventSubs: ").append(toIndentedString(eventSubs)).append("\n");
        sb.append("    eventsRepInfo: ").append(toIndentedString(eventsRepInfo)).append("\n");
        sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
        sb.append("    filterDnns: ").append(toIndentedString(filterDnns)).append("\n");
        sb.append("    filterSnssais: ").append(toIndentedString(filterSnssais)).append("\n");
        sb.append("    snssaiDnns: ").append(toIndentedString(snssaiDnns)).append("\n");
        sb.append("    filterServices: ").append(toIndentedString(filterServices)).append("\n");
        sb.append("    notifUri: ").append(toIndentedString(notifUri)).append("\n");
        sb.append("    notifId: ").append(toIndentedString(notifId)).append("\n");
        sb.append("    eventNotifs: ").append(toIndentedString(eventNotifs)).append("\n");
        sb.append("    suppFeat: ").append(toIndentedString(suppFeat)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
