Version: v2
Decription: FOSS list
LastUpdate: 2019-07-03 16:00
FOSS:
    # Available in Bazaar
    FOSSName: Apache Commons Configuration
    # Available in Bazaar
    FOSSVersion: 2.3
    # Available in Bazaar >>> used as kind of ID.
    FOSSURL: http://central.maven.org/maven2/org/apache/commons/commons-configuration2/2.3/commons-configuration2-2.3-sources.jar
    # Available in Bazaar
    PRIMNumber(CAX/CTX): 14/CAX1053383
    # Not Available in Bazaar
    PRIMNumber(CTC): CTC 101 5210
    # Not Available in Bazaar    
    FunctionalityUsedInTheEricssonProduct: Commons Configuration provides a generic configuration interface which enables a Java application to read configuration data from a variety of sources.
    # Available in Bazaar. Not used for specific report. >>> Includes _list_ of licenses taken from Bazaar
    AvailableLicenses: Apache License 2.0
    # Not available in Bazaar, >>> FAL should be factored out into separate mapping file
    ChoiceOfLicense: Apache License 2.0
    # Not Available in Bazaar >>> list of algorithms used (instead of bool)
    CryptographicAlgorithmsUsed: ()
    # Not Available in Bazaar
    CryptographicAlgorithmsUsedDescription: NA
    # Not Available in Bazaar >>> list
    SecureProtocolsUsed: ()
    # Not Available in Bazaar
    SecureProtocolsUsedDescription: NA
    # Select one of the following: Statically, Dynamically, Classpath, NotLinked. Not Available in Bazaar
    EricssonCodeLinkedWithTheFOSSCode: Dynamically
    # Not Available in Bazaar
    MavenDependency: 
    - 'org.apache.commons:commons-configuration2:jar:{{FOSSVersion}}'
    # >>> New attribute:
    # If yes, the default values of /scripts/fossReport/templates/defaultTemplate.yaml are not taken into account.
    # In this case, the yaml attributes of the defaultTemplate.yaml should be copied in this file with the desired values.
    ManualSpecificFOSSEvaluation: NO
    ReportAuthor: ENTNGRG Georgios Antoniou
