Version: v2
Decription: FOSS list
LastUpdate: 2019-07-12 12:24
FOSS:
    # Available in Bazaar
    FOSSName: Swagger-Core
    # Available in Bazaar
    FOSSVersion: 2.0.7
    # Available in Bazaar >>> used as kind of ID.
    FOSSURL: https://github.com/swagger-api/swagger-core/archive/v{{FOSSVersion}}.tar.gz
    # Available in Bazaar
    PRIMNumber(CAX/CTX): 19/CAX1056692
    # Not Available in Bazaar
    PRIMNumber(CTC): CTC 101 5349
    # Not Available in Bazaar    
    FunctionalityUsedInTheEricssonProduct: Swagger-core is the Java implementation of Swagger.
    # Available in Bazaar. Not used for specific report. >>> Includes _list_ of licenses taken from Bazaar
    AvailableLicenses: Apache License 2.0 
    # Not available in Bazaar, >>> FAL should be factored out into separate mapping file
    ChoiceOfLicense: Apache License 2.0
    # Not Available in Bazaar >>> list of algorithms used (instead of bool)
    CryptographicAlgorithmsUsed: ()
    # Not Available in Bazaar
    CryptographicAlgorithmsUsedDescription: NA
    # Not Available in Bazaar >>> list
    SecureProtocolsUsed: ()
    # Not Available in Bazaar
    SecureProtocolsUsedDescription: NA
    # Select one of the following: Statically, Dynamically, Classpath, NotLinked. Not Available in Bazaar
    EricssonCodeLinkedWithTheFOSSCode: Dynamically
    # Not Available in Bazaar
    MavenDependency: 
    - 'io.swagger.core.v3:swagger-annotations:jar:{{FOSSVersion}}'
    - 'io.swagger.core.v3:swagger-core:jar:{{FOSSVersion}}'
    - 'io.swagger.core.v3:swagger-models:jar:{{FOSSVersion}}'
    # >>> New attribute:
    # If yes, the default values of /scripts/fossReport/templates/defaultTemplate.yaml are not taken into account.
    # In this case, the yaml attributes of the defaultTemplate.yaml should be copied in this file with the desired values.
    ManualSpecificFOSSEvaluation: NO
    ReportAuthor: ENTNGRG Georgios Antoniou
