apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-sc-monitor.name" . }}-loglevel-config
  labels:
{{- include "eric-sc-monitor.labels" . | indent 4 }}
  annotations:
{{- include "eric-sc-monitor.helm-annotations" . | indent 4 }}
{{- include "eric-sc-monitor.config-annotations" . | indent 4 }}
data:
  logcontrol.json: |-
    [
        {
          "container": "monitor",
          "severity": {{ .Values.log.monitor.level | quote }}
        }
    ]